// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'error.freezed.dart';

@freezed
sealed class XueHuaAudioError with _$XueHuaAudioError implements FrbException {
  const XueHuaAudioError._();

  const factory XueHuaAudioError.device(String field0) =
      XueHuaAudioError_Device;
  const factory XueHuaAudioError.localFile(String field0) =
      XueHuaAudioError_LocalFile;
  const factory XueHuaAudioError.decode(String field0) =
      XueHuaAudioError_Decode;
  const factory XueHuaAudioError.alreadyStopped() =
      XueHuaAudioError_AlreadyStopped;
  const factory XueHuaAudioError.recording(String field0) =
      XueHuaAudioError_Recording;
  const factory XueHuaAudioError.alreadyRecording() =
      XueHuaAudioError_AlreadyRecording;
  const factory XueHuaAudioError.notRecording() = XueHuaAudioError_NotRecording;
}
