// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `compute_progress_ratio`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`

/// 单轨播放状态与进度快照。
class XueHuaPlaybackProgress {
  final bool isPlaying;
  final bool isPaused;
  final bool isFinished;
  final double positionSecs;
  final double? durationSecs;

  /// 0.0~1.0；duration 未知时为 None
  final double? progress;

  const XueHuaPlaybackProgress({
    required this.isPlaying,
    required this.isPaused,
    required this.isFinished,
    required this.positionSecs,
    this.durationSecs,
    this.progress,
  });

  @override
  int get hashCode =>
      isPlaying.hashCode ^
      isPaused.hashCode ^
      isFinished.hashCode ^
      positionSecs.hashCode ^
      durationSecs.hashCode ^
      progress.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is XueHuaPlaybackProgress &&
          runtimeType == other.runtimeType &&
          isPlaying == other.isPlaying &&
          isPaused == other.isPaused &&
          isFinished == other.isFinished &&
          positionSecs == other.positionSecs &&
          durationSecs == other.durationSecs &&
          progress == other.progress;
}
