// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'error.dart';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'recording.dart';
import 'track.dart';

// These functions are ignored because they are not marked as `pub`: `connect_new_player`, `list_output_device_infos`, `lock_mutex`, `next_recorder_id`, `next_track_id`, `open_output_sink`, `unregister_recorder`, `unregister_track`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `RecorderRegistryEntry`, `RegistryEntry`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `eq`, `fmt`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<XueHuaAudioEngine>>
abstract class XueHuaAudioEngine implements RustOpaqueInterface {
  /// 创建一条独立录制会话。
  Future<XueHuaAudioRecorder> createRecorder();

  /// 当前引擎偏好的输出设备；未设置偏好时返回系统默认输出。
  Future<XueHuaOutputDevice?> currentOutputDevice();

  /// 列出可用麦克风输入设备名称。
  Future<List<String>> listInputDevices();

  /// 列出可用输出设备（名称与是否为系统默认，对应 rodio `Output` 公开信息）。
  Future<List<XueHuaOutputDevice>> listOutputDevices();

  /// 从内存字节加载并播放（小文件 / 测试用；生产 Asset/URL 请走临时文件 + load_from_path）。
  Future<XueHuaAudioTrack> loadFromBytes({
    required List<int> data,
    required bool loop,
  });

  /// 从本地文件系统绝对路径加载并播放（流式解码）。
  Future<XueHuaAudioTrack> loadFromPath({
    required String path,
    required bool loop,
  });

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  /// 创建空引擎壳（不打开音频设备）。
  static Future<XueHuaAudioEngine> newInstance() =>
      RustLib.instance.api.crateEngineXueHuaAudioEngineNew();

  /// 设置输出设备。`None` 表示系统默认。
  ///
  /// 会先 [`Self::stop_all`]；若输出 sink 已打开则立即按新偏好重建。
  Future<void> setOutputDevice({int? deviceIndex});

  /// 停止并注销所有仍活跃的音轨。
  Future<void> stopAll();

  /// 停止所有仍活跃的录制会话。
  Future<void> stopAllRecorders();
}

/// 输出设备信息（对应 rodio `speakers::Output` 的公开字段）。
class XueHuaOutputDevice {
  final String name;
  final bool isDefault;

  const XueHuaOutputDevice({required this.name, required this.isDefault});

  @override
  int get hashCode => name.hashCode ^ isDefault.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is XueHuaOutputDevice &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          isDefault == other.isDefault;
}
