// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'error.dart';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'recording.dart';
import 'track.dart';

// These functions are ignored because they are not marked as `pub`: `next_recorder_id`, `next_track_id`, `unregister_recorder`, `unregister_track`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `RecorderRegistryEntry`, `RegistryEntry`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<XueHuaAudioEngine>>
abstract class XueHuaAudioEngine implements RustOpaqueInterface {
  /// 创建一条独立录制会话。
  Future<XueHuaAudioRecorder> createRecorder();

  /// 列出可用麦克风输入设备名称。
  Future<List<String>> listInputDevices();

  /// 从内存字节加载并播放（小文件 / 测试用；生产 Asset/URL 请走临时文件 + load_from_path）。
  Future<XueHuaAudioTrack> loadFromBytes({required List<int> data});

  /// 从本地文件系统绝对路径加载并播放（流式解码）。
  Future<XueHuaAudioTrack> loadFromPath({required String path});

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  /// 打开系统默认音频输出设备。
  static Future<XueHuaAudioEngine> newInstance() =>
      RustLib.instance.api.crateEngineXueHuaAudioEngineNew();

  /// 停止并注销所有仍活跃的音轨。
  Future<void> stopAll();

  /// 停止所有仍活跃的录制会话。
  Future<void> stopAllRecorders();
}
