// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'dart:async';
import 'dart:convert';
import 'engine.dart';
import 'error.dart';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'playback.dart';
import 'recording.dart';
import 'track.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateInitInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => -29488223;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'xue_hua_audio_player',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<XueHuaAudioRecorder> crateEngineXueHuaAudioEngineCreateRecorder({
    required XueHuaAudioEngine that,
  });

  Future<List<String>> crateEngineXueHuaAudioEngineListInputDevices({
    required XueHuaAudioEngine that,
  });

  Future<XueHuaAudioTrack> crateEngineXueHuaAudioEngineLoadFromBytes({
    required XueHuaAudioEngine that,
    required List<int> data,
  });

  Future<XueHuaAudioTrack> crateEngineXueHuaAudioEngineLoadFromPath({
    required XueHuaAudioEngine that,
    required String path,
  });

  Future<XueHuaAudioEngine> crateEngineXueHuaAudioEngineNew();

  Future<void> crateEngineXueHuaAudioEngineStopAll({
    required XueHuaAudioEngine that,
  });

  Future<void> crateEngineXueHuaAudioEngineStopAllRecorders({
    required XueHuaAudioEngine that,
  });

  bool crateRecordingXueHuaAudioRecorderIsPaused({
    required XueHuaAudioRecorder that,
  });

  bool crateRecordingXueHuaAudioRecorderIsRecording({
    required XueHuaAudioRecorder that,
  });

  Future<void> crateRecordingXueHuaAudioRecorderPause({
    required XueHuaAudioRecorder that,
  });

  Future<void> crateRecordingXueHuaAudioRecorderResume({
    required XueHuaAudioRecorder that,
  });

  Stream<XueHuaRecordingEvent> crateRecordingXueHuaAudioRecorderStart({
    required XueHuaAudioRecorder that,
    required String outputPath,
    int? deviceIndex,
  });

  Future<String> crateRecordingXueHuaAudioRecorderStop({
    required XueHuaAudioRecorder that,
  });

  double? crateTrackXueHuaAudioTrackDurationSecs({
    required XueHuaAudioTrack that,
  });

  bool crateTrackXueHuaAudioTrackIsFinished({required XueHuaAudioTrack that});

  Future<bool> crateTrackXueHuaAudioTrackIsPaused({
    required XueHuaAudioTrack that,
  });

  bool crateTrackXueHuaAudioTrackIsPlaying({required XueHuaAudioTrack that});

  Future<void> crateTrackXueHuaAudioTrackPause({
    required XueHuaAudioTrack that,
  });

  XueHuaPlaybackProgress crateTrackXueHuaAudioTrackPlaybackProgress({
    required XueHuaAudioTrack that,
  });

  double crateTrackXueHuaAudioTrackPositionSecs({
    required XueHuaAudioTrack that,
  });

  Future<void> crateTrackXueHuaAudioTrackReplaceFromBytes({
    required XueHuaAudioTrack that,
    required List<int> data,
  });

  Future<void> crateTrackXueHuaAudioTrackReplaceFromPath({
    required XueHuaAudioTrack that,
    required String path,
  });

  Future<void> crateTrackXueHuaAudioTrackResume({
    required XueHuaAudioTrack that,
  });

  Future<void> crateTrackXueHuaAudioTrackSeekTo({
    required XueHuaAudioTrack that,
    required double positionSecs,
  });

  Future<void> crateTrackXueHuaAudioTrackSetVolume({
    required XueHuaAudioTrack that,
    required double volume,
  });

  Future<void> crateTrackXueHuaAudioTrackStop({required XueHuaAudioTrack that});

  Future<double> crateTrackXueHuaAudioTrackVolume({
    required XueHuaAudioTrack that,
  });

  Stream<XueHuaPlaybackProgress>
  crateTrackXueHuaAudioTrackWatchPlaybackProgress({
    required XueHuaAudioTrack that,
  });

  Future<void> crateInitInitApp();

  Future<List<String>> crateRecordingListInputDevices();

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_XueHuaAudioEngine;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_XueHuaAudioEngine;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_XueHuaAudioEnginePtr;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_XueHuaAudioRecorder;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_XueHuaAudioRecorder;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_XueHuaAudioRecorderPtr;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_XueHuaAudioTrack;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_XueHuaAudioTrack;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_XueHuaAudioTrackPtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<XueHuaAudioRecorder> crateEngineXueHuaAudioEngineCreateRecorder({
    required XueHuaAudioEngine that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerXueHuaAudioEngine(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerXueHuaAudioRecorder,
          decodeErrorData: null,
        ),
        constMeta: kCrateEngineXueHuaAudioEngineCreateRecorderConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateEngineXueHuaAudioEngineCreateRecorderConstMeta =>
      const TaskConstMeta(
        debugName: "XueHuaAudioEngine_create_recorder",
        argNames: ["that"],
      );

  @override
  Future<List<String>> crateEngineXueHuaAudioEngineListInputDevices({
    required XueHuaAudioEngine that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerXueHuaAudioEngine(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_String,
          decodeErrorData: sse_decode_xue_hua_audio_error,
        ),
        constMeta: kCrateEngineXueHuaAudioEngineListInputDevicesConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateEngineXueHuaAudioEngineListInputDevicesConstMeta =>
      const TaskConstMeta(
        debugName: "XueHuaAudioEngine_list_input_devices",
        argNames: ["that"],
      );

  @override
  Future<XueHuaAudioTrack> crateEngineXueHuaAudioEngineLoadFromBytes({
    required XueHuaAudioEngine that,
    required List<int> data,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerXueHuaAudioEngine(
            that,
            serializer,
          );
          sse_encode_list_prim_u_8_loose(data, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerXueHuaAudioTrack,
          decodeErrorData: sse_decode_xue_hua_audio_error,
        ),
        constMeta: kCrateEngineXueHuaAudioEngineLoadFromBytesConstMeta,
        argValues: [that, data],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateEngineXueHuaAudioEngineLoadFromBytesConstMeta =>
      const TaskConstMeta(
        debugName: "XueHuaAudioEngine_load_from_bytes",
        argNames: ["that", "data"],
      );

  @override
  Future<XueHuaAudioTrack> crateEngineXueHuaAudioEngineLoadFromPath({
    required XueHuaAudioEngine that,
    required String path,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerXueHuaAudioEngine(
            that,
            serializer,
          );
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerXueHuaAudioTrack,
          decodeErrorData: sse_decode_xue_hua_audio_error,
        ),
        constMeta: kCrateEngineXueHuaAudioEngineLoadFromPathConstMeta,
        argValues: [that, path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateEngineXueHuaAudioEngineLoadFromPathConstMeta =>
      const TaskConstMeta(
        debugName: "XueHuaAudioEngine_load_from_path",
        argNames: ["that", "path"],
      );

  @override
  Future<XueHuaAudioEngine> crateEngineXueHuaAudioEngineNew() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerXueHuaAudioEngine,
          decodeErrorData: sse_decode_xue_hua_audio_error,
        ),
        constMeta: kCrateEngineXueHuaAudioEngineNewConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateEngineXueHuaAudioEngineNewConstMeta =>
      const TaskConstMeta(debugName: "XueHuaAudioEngine_new", argNames: []);

  @override
  Future<void> crateEngineXueHuaAudioEngineStopAll({
    required XueHuaAudioEngine that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerXueHuaAudioEngine(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateEngineXueHuaAudioEngineStopAllConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateEngineXueHuaAudioEngineStopAllConstMeta =>
      const TaskConstMeta(
        debugName: "XueHuaAudioEngine_stop_all",
        argNames: ["that"],
      );

  @override
  Future<void> crateEngineXueHuaAudioEngineStopAllRecorders({
    required XueHuaAudioEngine that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerXueHuaAudioEngine(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateEngineXueHuaAudioEngineStopAllRecordersConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateEngineXueHuaAudioEngineStopAllRecordersConstMeta =>
      const TaskConstMeta(
        debugName: "XueHuaAudioEngine_stop_all_recorders",
        argNames: ["that"],
      );

  @override
  bool crateRecordingXueHuaAudioRecorderIsPaused({
    required XueHuaAudioRecorder that,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerXueHuaAudioRecorder(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateRecordingXueHuaAudioRecorderIsPausedConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateRecordingXueHuaAudioRecorderIsPausedConstMeta =>
      const TaskConstMeta(
        debugName: "XueHuaAudioRecorder_is_paused",
        argNames: ["that"],
      );

  @override
  bool crateRecordingXueHuaAudioRecorderIsRecording({
    required XueHuaAudioRecorder that,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerXueHuaAudioRecorder(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 9)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateRecordingXueHuaAudioRecorderIsRecordingConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateRecordingXueHuaAudioRecorderIsRecordingConstMeta =>
      const TaskConstMeta(
        debugName: "XueHuaAudioRecorder_is_recording",
        argNames: ["that"],
      );

  @override
  Future<void> crateRecordingXueHuaAudioRecorderPause({
    required XueHuaAudioRecorder that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerXueHuaAudioRecorder(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_xue_hua_audio_error,
        ),
        constMeta: kCrateRecordingXueHuaAudioRecorderPauseConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateRecordingXueHuaAudioRecorderPauseConstMeta =>
      const TaskConstMeta(
        debugName: "XueHuaAudioRecorder_pause",
        argNames: ["that"],
      );

  @override
  Future<void> crateRecordingXueHuaAudioRecorderResume({
    required XueHuaAudioRecorder that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerXueHuaAudioRecorder(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_xue_hua_audio_error,
        ),
        constMeta: kCrateRecordingXueHuaAudioRecorderResumeConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateRecordingXueHuaAudioRecorderResumeConstMeta =>
      const TaskConstMeta(
        debugName: "XueHuaAudioRecorder_resume",
        argNames: ["that"],
      );

  @override
  Stream<XueHuaRecordingEvent> crateRecordingXueHuaAudioRecorderStart({
    required XueHuaAudioRecorder that,
    required String outputPath,
    int? deviceIndex,
  }) {
    final progressSink = RustStreamSink<XueHuaRecordingEvent>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerXueHuaAudioRecorder(
              that,
              serializer,
            );
            sse_encode_String(outputPath, serializer);
            sse_encode_StreamSink_xue_hua_recording_event_Sse(
              progressSink,
              serializer,
            );
            sse_encode_opt_box_autoadd_u_32(deviceIndex, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 12,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_xue_hua_audio_error,
          ),
          constMeta: kCrateRecordingXueHuaAudioRecorderStartConstMeta,
          argValues: [that, outputPath, progressSink, deviceIndex],
          apiImpl: this,
        ),
      ),
    );
    return progressSink.stream;
  }

  TaskConstMeta get kCrateRecordingXueHuaAudioRecorderStartConstMeta =>
      const TaskConstMeta(
        debugName: "XueHuaAudioRecorder_start",
        argNames: ["that", "outputPath", "progressSink", "deviceIndex"],
      );

  @override
  Future<String> crateRecordingXueHuaAudioRecorderStop({
    required XueHuaAudioRecorder that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerXueHuaAudioRecorder(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_xue_hua_audio_error,
        ),
        constMeta: kCrateRecordingXueHuaAudioRecorderStopConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateRecordingXueHuaAudioRecorderStopConstMeta =>
      const TaskConstMeta(
        debugName: "XueHuaAudioRecorder_stop",
        argNames: ["that"],
      );

  @override
  double? crateTrackXueHuaAudioTrackDurationSecs({
    required XueHuaAudioTrack that,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerXueHuaAudioTrack(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 14)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_f_64,
          decodeErrorData: null,
        ),
        constMeta: kCrateTrackXueHuaAudioTrackDurationSecsConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateTrackXueHuaAudioTrackDurationSecsConstMeta =>
      const TaskConstMeta(
        debugName: "XueHuaAudioTrack_duration_secs",
        argNames: ["that"],
      );

  @override
  bool crateTrackXueHuaAudioTrackIsFinished({required XueHuaAudioTrack that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerXueHuaAudioTrack(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 15)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateTrackXueHuaAudioTrackIsFinishedConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateTrackXueHuaAudioTrackIsFinishedConstMeta =>
      const TaskConstMeta(
        debugName: "XueHuaAudioTrack_is_finished",
        argNames: ["that"],
      );

  @override
  Future<bool> crateTrackXueHuaAudioTrackIsPaused({
    required XueHuaAudioTrack that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerXueHuaAudioTrack(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateTrackXueHuaAudioTrackIsPausedConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateTrackXueHuaAudioTrackIsPausedConstMeta =>
      const TaskConstMeta(
        debugName: "XueHuaAudioTrack_is_paused",
        argNames: ["that"],
      );

  @override
  bool crateTrackXueHuaAudioTrackIsPlaying({required XueHuaAudioTrack that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerXueHuaAudioTrack(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 17)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateTrackXueHuaAudioTrackIsPlayingConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateTrackXueHuaAudioTrackIsPlayingConstMeta =>
      const TaskConstMeta(
        debugName: "XueHuaAudioTrack_is_playing",
        argNames: ["that"],
      );

  @override
  Future<void> crateTrackXueHuaAudioTrackPause({
    required XueHuaAudioTrack that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerXueHuaAudioTrack(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 18,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateTrackXueHuaAudioTrackPauseConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateTrackXueHuaAudioTrackPauseConstMeta =>
      const TaskConstMeta(
        debugName: "XueHuaAudioTrack_pause",
        argNames: ["that"],
      );

  @override
  XueHuaPlaybackProgress crateTrackXueHuaAudioTrackPlaybackProgress({
    required XueHuaAudioTrack that,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerXueHuaAudioTrack(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 19)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_xue_hua_playback_progress,
          decodeErrorData: null,
        ),
        constMeta: kCrateTrackXueHuaAudioTrackPlaybackProgressConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateTrackXueHuaAudioTrackPlaybackProgressConstMeta =>
      const TaskConstMeta(
        debugName: "XueHuaAudioTrack_playback_progress",
        argNames: ["that"],
      );

  @override
  double crateTrackXueHuaAudioTrackPositionSecs({
    required XueHuaAudioTrack that,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerXueHuaAudioTrack(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 20)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_f_64,
          decodeErrorData: null,
        ),
        constMeta: kCrateTrackXueHuaAudioTrackPositionSecsConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateTrackXueHuaAudioTrackPositionSecsConstMeta =>
      const TaskConstMeta(
        debugName: "XueHuaAudioTrack_position_secs",
        argNames: ["that"],
      );

  @override
  Future<void> crateTrackXueHuaAudioTrackReplaceFromBytes({
    required XueHuaAudioTrack that,
    required List<int> data,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerXueHuaAudioTrack(
            that,
            serializer,
          );
          sse_encode_list_prim_u_8_loose(data, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 21,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_xue_hua_audio_error,
        ),
        constMeta: kCrateTrackXueHuaAudioTrackReplaceFromBytesConstMeta,
        argValues: [that, data],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateTrackXueHuaAudioTrackReplaceFromBytesConstMeta =>
      const TaskConstMeta(
        debugName: "XueHuaAudioTrack_replace_from_bytes",
        argNames: ["that", "data"],
      );

  @override
  Future<void> crateTrackXueHuaAudioTrackReplaceFromPath({
    required XueHuaAudioTrack that,
    required String path,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerXueHuaAudioTrack(
            that,
            serializer,
          );
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 22,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_xue_hua_audio_error,
        ),
        constMeta: kCrateTrackXueHuaAudioTrackReplaceFromPathConstMeta,
        argValues: [that, path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateTrackXueHuaAudioTrackReplaceFromPathConstMeta =>
      const TaskConstMeta(
        debugName: "XueHuaAudioTrack_replace_from_path",
        argNames: ["that", "path"],
      );

  @override
  Future<void> crateTrackXueHuaAudioTrackResume({
    required XueHuaAudioTrack that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerXueHuaAudioTrack(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 23,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateTrackXueHuaAudioTrackResumeConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateTrackXueHuaAudioTrackResumeConstMeta =>
      const TaskConstMeta(
        debugName: "XueHuaAudioTrack_resume",
        argNames: ["that"],
      );

  @override
  Future<void> crateTrackXueHuaAudioTrackSeekTo({
    required XueHuaAudioTrack that,
    required double positionSecs,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerXueHuaAudioTrack(
            that,
            serializer,
          );
          sse_encode_f_64(positionSecs, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 24,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_xue_hua_audio_error,
        ),
        constMeta: kCrateTrackXueHuaAudioTrackSeekToConstMeta,
        argValues: [that, positionSecs],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateTrackXueHuaAudioTrackSeekToConstMeta =>
      const TaskConstMeta(
        debugName: "XueHuaAudioTrack_seek_to",
        argNames: ["that", "positionSecs"],
      );

  @override
  Future<void> crateTrackXueHuaAudioTrackSetVolume({
    required XueHuaAudioTrack that,
    required double volume,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerXueHuaAudioTrack(
            that,
            serializer,
          );
          sse_encode_f_32(volume, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 25,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateTrackXueHuaAudioTrackSetVolumeConstMeta,
        argValues: [that, volume],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateTrackXueHuaAudioTrackSetVolumeConstMeta =>
      const TaskConstMeta(
        debugName: "XueHuaAudioTrack_set_volume",
        argNames: ["that", "volume"],
      );

  @override
  Future<void> crateTrackXueHuaAudioTrackStop({
    required XueHuaAudioTrack that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerXueHuaAudioTrack(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 26,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_xue_hua_audio_error,
        ),
        constMeta: kCrateTrackXueHuaAudioTrackStopConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateTrackXueHuaAudioTrackStopConstMeta =>
      const TaskConstMeta(
        debugName: "XueHuaAudioTrack_stop",
        argNames: ["that"],
      );

  @override
  Future<double> crateTrackXueHuaAudioTrackVolume({
    required XueHuaAudioTrack that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerXueHuaAudioTrack(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 27,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_f_32,
          decodeErrorData: null,
        ),
        constMeta: kCrateTrackXueHuaAudioTrackVolumeConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateTrackXueHuaAudioTrackVolumeConstMeta =>
      const TaskConstMeta(
        debugName: "XueHuaAudioTrack_volume",
        argNames: ["that"],
      );

  @override
  Stream<XueHuaPlaybackProgress>
  crateTrackXueHuaAudioTrackWatchPlaybackProgress({
    required XueHuaAudioTrack that,
  }) {
    final progressSink = RustStreamSink<XueHuaPlaybackProgress>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerXueHuaAudioTrack(
              that,
              serializer,
            );
            sse_encode_StreamSink_xue_hua_playback_progress_Sse(
              progressSink,
              serializer,
            );
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 28,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_xue_hua_audio_error,
          ),
          constMeta: kCrateTrackXueHuaAudioTrackWatchPlaybackProgressConstMeta,
          argValues: [that, progressSink],
          apiImpl: this,
        ),
      ),
    );
    return progressSink.stream;
  }

  TaskConstMeta get kCrateTrackXueHuaAudioTrackWatchPlaybackProgressConstMeta =>
      const TaskConstMeta(
        debugName: "XueHuaAudioTrack_watch_playback_progress",
        argNames: ["that", "progressSink"],
      );

  @override
  Future<void> crateInitInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 29,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateInitInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateInitInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<List<String>> crateRecordingListInputDevices() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 30,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_String,
          decodeErrorData: sse_decode_xue_hua_audio_error,
        ),
        constMeta: kCrateRecordingListInputDevicesConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateRecordingListInputDevicesConstMeta =>
      const TaskConstMeta(debugName: "list_input_devices", argNames: []);

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_XueHuaAudioEngine => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerXueHuaAudioEngine;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_XueHuaAudioEngine => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerXueHuaAudioEngine;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_XueHuaAudioRecorder => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerXueHuaAudioRecorder;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_XueHuaAudioRecorder => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerXueHuaAudioRecorder;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_XueHuaAudioTrack => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerXueHuaAudioTrack;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_XueHuaAudioTrack => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerXueHuaAudioTrack;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  XueHuaAudioEngine
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerXueHuaAudioEngine(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return XueHuaAudioEngineImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  XueHuaAudioRecorder
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerXueHuaAudioRecorder(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return XueHuaAudioRecorderImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  XueHuaAudioTrack
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerXueHuaAudioTrack(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return XueHuaAudioTrackImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  XueHuaAudioRecorder
  dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerXueHuaAudioRecorder(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return XueHuaAudioRecorderImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  XueHuaAudioTrack
  dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerXueHuaAudioTrack(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return XueHuaAudioTrackImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  XueHuaAudioEngine
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerXueHuaAudioEngine(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return XueHuaAudioEngineImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  XueHuaAudioRecorder
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerXueHuaAudioRecorder(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return XueHuaAudioRecorderImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  XueHuaAudioTrack
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerXueHuaAudioTrack(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return XueHuaAudioTrackImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  XueHuaAudioEngine
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerXueHuaAudioEngine(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return XueHuaAudioEngineImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  XueHuaAudioRecorder
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerXueHuaAudioRecorder(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return XueHuaAudioRecorderImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  XueHuaAudioTrack
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerXueHuaAudioTrack(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return XueHuaAudioTrackImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  RustStreamSink<XueHuaPlaybackProgress>
  dco_decode_StreamSink_xue_hua_playback_progress_Sse(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  RustStreamSink<XueHuaRecordingEvent>
  dco_decode_StreamSink_xue_hua_recording_event_Sse(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  double dco_decode_box_autoadd_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  XueHuaRecordingCompleted dco_decode_box_autoadd_xue_hua_recording_completed(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_xue_hua_recording_completed(raw);
  }

  @protected
  XueHuaRecordingProgress dco_decode_box_autoadd_xue_hua_recording_progress(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_xue_hua_recording_progress(raw);
  }

  @protected
  double dco_decode_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  double? dco_decode_opt_box_autoadd_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_f_64(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_32(raw);
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  XueHuaAudioError dco_decode_xue_hua_audio_error(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return XueHuaAudioError_Device(dco_decode_String(raw[1]));
      case 1:
        return XueHuaAudioError_LocalFile(dco_decode_String(raw[1]));
      case 2:
        return XueHuaAudioError_Decode(dco_decode_String(raw[1]));
      case 3:
        return XueHuaAudioError_AlreadyStopped();
      case 4:
        return XueHuaAudioError_Recording(dco_decode_String(raw[1]));
      case 5:
        return XueHuaAudioError_AlreadyRecording();
      case 6:
        return XueHuaAudioError_NotRecording();
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  XueHuaPlaybackProgress dco_decode_xue_hua_playback_progress(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return XueHuaPlaybackProgress(
      isPlaying: dco_decode_bool(arr[0]),
      isPaused: dco_decode_bool(arr[1]),
      isFinished: dco_decode_bool(arr[2]),
      positionSecs: dco_decode_f_64(arr[3]),
      durationSecs: dco_decode_opt_box_autoadd_f_64(arr[4]),
      progress: dco_decode_opt_box_autoadd_f_64(arr[5]),
    );
  }

  @protected
  XueHuaRecordingCompleted dco_decode_xue_hua_recording_completed(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return XueHuaRecordingCompleted(
      outputPath: dco_decode_String(arr[0]),
      durationSecs: dco_decode_f_64(arr[1]),
    );
  }

  @protected
  XueHuaRecordingEvent dco_decode_xue_hua_recording_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return XueHuaRecordingEvent_Progress(
          dco_decode_box_autoadd_xue_hua_recording_progress(raw[1]),
        );
      case 1:
        return XueHuaRecordingEvent_Completed(
          dco_decode_box_autoadd_xue_hua_recording_completed(raw[1]),
        );
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  XueHuaRecordingProgress dco_decode_xue_hua_recording_progress(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return XueHuaRecordingProgress(
      isRecording: dco_decode_bool(arr[0]),
      isPaused: dco_decode_bool(arr[1]),
      durationSecs: dco_decode_f_64(arr[2]),
      level: dco_decode_f_32(arr[3]),
    );
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  XueHuaAudioEngine
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerXueHuaAudioEngine(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return XueHuaAudioEngineImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  XueHuaAudioRecorder
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerXueHuaAudioRecorder(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return XueHuaAudioRecorderImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  XueHuaAudioTrack
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerXueHuaAudioTrack(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return XueHuaAudioTrackImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  XueHuaAudioRecorder
  sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerXueHuaAudioRecorder(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return XueHuaAudioRecorderImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  XueHuaAudioTrack
  sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerXueHuaAudioTrack(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return XueHuaAudioTrackImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  XueHuaAudioEngine
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerXueHuaAudioEngine(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return XueHuaAudioEngineImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  XueHuaAudioRecorder
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerXueHuaAudioRecorder(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return XueHuaAudioRecorderImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  XueHuaAudioTrack
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerXueHuaAudioTrack(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return XueHuaAudioTrackImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  XueHuaAudioEngine
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerXueHuaAudioEngine(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return XueHuaAudioEngineImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  XueHuaAudioRecorder
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerXueHuaAudioRecorder(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return XueHuaAudioRecorderImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  XueHuaAudioTrack
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerXueHuaAudioTrack(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return XueHuaAudioTrackImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  RustStreamSink<XueHuaPlaybackProgress>
  sse_decode_StreamSink_xue_hua_playback_progress_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  RustStreamSink<XueHuaRecordingEvent>
  sse_decode_StreamSink_xue_hua_recording_event_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  double sse_decode_box_autoadd_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_f_64(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_32(deserializer));
  }

  @protected
  XueHuaRecordingCompleted sse_decode_box_autoadd_xue_hua_recording_completed(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_xue_hua_recording_completed(deserializer));
  }

  @protected
  XueHuaRecordingProgress sse_decode_box_autoadd_xue_hua_recording_progress(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_xue_hua_recording_progress(deserializer));
  }

  @protected
  double sse_decode_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat32();
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_f_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  XueHuaAudioError sse_decode_xue_hua_audio_error(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_field0 = sse_decode_String(deserializer);
        return XueHuaAudioError_Device(var_field0);
      case 1:
        var var_field0 = sse_decode_String(deserializer);
        return XueHuaAudioError_LocalFile(var_field0);
      case 2:
        var var_field0 = sse_decode_String(deserializer);
        return XueHuaAudioError_Decode(var_field0);
      case 3:
        return XueHuaAudioError_AlreadyStopped();
      case 4:
        var var_field0 = sse_decode_String(deserializer);
        return XueHuaAudioError_Recording(var_field0);
      case 5:
        return XueHuaAudioError_AlreadyRecording();
      case 6:
        return XueHuaAudioError_NotRecording();
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  XueHuaPlaybackProgress sse_decode_xue_hua_playback_progress(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_isPlaying = sse_decode_bool(deserializer);
    var var_isPaused = sse_decode_bool(deserializer);
    var var_isFinished = sse_decode_bool(deserializer);
    var var_positionSecs = sse_decode_f_64(deserializer);
    var var_durationSecs = sse_decode_opt_box_autoadd_f_64(deserializer);
    var var_progress = sse_decode_opt_box_autoadd_f_64(deserializer);
    return XueHuaPlaybackProgress(
      isPlaying: var_isPlaying,
      isPaused: var_isPaused,
      isFinished: var_isFinished,
      positionSecs: var_positionSecs,
      durationSecs: var_durationSecs,
      progress: var_progress,
    );
  }

  @protected
  XueHuaRecordingCompleted sse_decode_xue_hua_recording_completed(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_outputPath = sse_decode_String(deserializer);
    var var_durationSecs = sse_decode_f_64(deserializer);
    return XueHuaRecordingCompleted(
      outputPath: var_outputPath,
      durationSecs: var_durationSecs,
    );
  }

  @protected
  XueHuaRecordingEvent sse_decode_xue_hua_recording_event(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_field0 = sse_decode_box_autoadd_xue_hua_recording_progress(
          deserializer,
        );
        return XueHuaRecordingEvent_Progress(var_field0);
      case 1:
        var var_field0 = sse_decode_box_autoadd_xue_hua_recording_completed(
          deserializer,
        );
        return XueHuaRecordingEvent_Completed(var_field0);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  XueHuaRecordingProgress sse_decode_xue_hua_recording_progress(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_isRecording = sse_decode_bool(deserializer);
    var var_isPaused = sse_decode_bool(deserializer);
    var var_durationSecs = sse_decode_f_64(deserializer);
    var var_level = sse_decode_f_32(deserializer);
    return XueHuaRecordingProgress(
      isRecording: var_isRecording,
      isPaused: var_isPaused,
      durationSecs: var_durationSecs,
      level: var_level,
    );
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerXueHuaAudioEngine(
    XueHuaAudioEngine self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as XueHuaAudioEngineImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerXueHuaAudioRecorder(
    XueHuaAudioRecorder self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as XueHuaAudioRecorderImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerXueHuaAudioTrack(
    XueHuaAudioTrack self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as XueHuaAudioTrackImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerXueHuaAudioRecorder(
    XueHuaAudioRecorder self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as XueHuaAudioRecorderImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerXueHuaAudioTrack(
    XueHuaAudioTrack self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as XueHuaAudioTrackImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerXueHuaAudioEngine(
    XueHuaAudioEngine self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as XueHuaAudioEngineImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerXueHuaAudioRecorder(
    XueHuaAudioRecorder self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as XueHuaAudioRecorderImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerXueHuaAudioTrack(
    XueHuaAudioTrack self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as XueHuaAudioTrackImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerXueHuaAudioEngine(
    XueHuaAudioEngine self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as XueHuaAudioEngineImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerXueHuaAudioRecorder(
    XueHuaAudioRecorder self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as XueHuaAudioRecorderImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerXueHuaAudioTrack(
    XueHuaAudioTrack self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as XueHuaAudioTrackImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_xue_hua_playback_progress_Sse(
    RustStreamSink<XueHuaPlaybackProgress> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_xue_hua_playback_progress,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_xue_hua_recording_event_Sse(
    RustStreamSink<XueHuaRecordingEvent> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_xue_hua_recording_event,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_xue_hua_recording_completed(
    XueHuaRecordingCompleted self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_xue_hua_recording_completed(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_xue_hua_recording_progress(
    XueHuaRecordingProgress self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_xue_hua_recording_progress(self, serializer);
  }

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat32(self);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(
      self is Uint8List ? self : Uint8List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_f_64(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_32(self, serializer);
    }
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_xue_hua_audio_error(
    XueHuaAudioError self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case XueHuaAudioError_Device(field0: final field0):
        sse_encode_i_32(0, serializer);
        sse_encode_String(field0, serializer);
      case XueHuaAudioError_LocalFile(field0: final field0):
        sse_encode_i_32(1, serializer);
        sse_encode_String(field0, serializer);
      case XueHuaAudioError_Decode(field0: final field0):
        sse_encode_i_32(2, serializer);
        sse_encode_String(field0, serializer);
      case XueHuaAudioError_AlreadyStopped():
        sse_encode_i_32(3, serializer);
      case XueHuaAudioError_Recording(field0: final field0):
        sse_encode_i_32(4, serializer);
        sse_encode_String(field0, serializer);
      case XueHuaAudioError_AlreadyRecording():
        sse_encode_i_32(5, serializer);
      case XueHuaAudioError_NotRecording():
        sse_encode_i_32(6, serializer);
    }
  }

  @protected
  void sse_encode_xue_hua_playback_progress(
    XueHuaPlaybackProgress self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.isPlaying, serializer);
    sse_encode_bool(self.isPaused, serializer);
    sse_encode_bool(self.isFinished, serializer);
    sse_encode_f_64(self.positionSecs, serializer);
    sse_encode_opt_box_autoadd_f_64(self.durationSecs, serializer);
    sse_encode_opt_box_autoadd_f_64(self.progress, serializer);
  }

  @protected
  void sse_encode_xue_hua_recording_completed(
    XueHuaRecordingCompleted self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.outputPath, serializer);
    sse_encode_f_64(self.durationSecs, serializer);
  }

  @protected
  void sse_encode_xue_hua_recording_event(
    XueHuaRecordingEvent self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case XueHuaRecordingEvent_Progress(field0: final field0):
        sse_encode_i_32(0, serializer);
        sse_encode_box_autoadd_xue_hua_recording_progress(field0, serializer);
      case XueHuaRecordingEvent_Completed(field0: final field0):
        sse_encode_i_32(1, serializer);
        sse_encode_box_autoadd_xue_hua_recording_completed(field0, serializer);
    }
  }

  @protected
  void sse_encode_xue_hua_recording_progress(
    XueHuaRecordingProgress self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.isRecording, serializer);
    sse_encode_bool(self.isPaused, serializer);
    sse_encode_f_64(self.durationSecs, serializer);
    sse_encode_f_32(self.level, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}

@sealed
class XueHuaAudioEngineImpl extends RustOpaque implements XueHuaAudioEngine {
  // Not to be used by end users
  XueHuaAudioEngineImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  XueHuaAudioEngineImpl.frbInternalSseDecode(
    BigInt ptr,
    int externalSizeOnNative,
  ) : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_XueHuaAudioEngine,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_XueHuaAudioEngine,
    rustArcDecrementStrongCountPtr: RustLib
        .instance
        .api
        .rust_arc_decrement_strong_count_XueHuaAudioEnginePtr,
  );

  /// 创建一条独立录制会话。
  Future<XueHuaAudioRecorder> createRecorder() => RustLib.instance.api
      .crateEngineXueHuaAudioEngineCreateRecorder(that: this);

  /// 列出可用麦克风输入设备名称。
  Future<List<String>> listInputDevices() => RustLib.instance.api
      .crateEngineXueHuaAudioEngineListInputDevices(that: this);

  /// 从内存字节加载并播放（小文件 / 测试用；生产 Asset/URL 请走临时文件 + load_from_path）。
  Future<XueHuaAudioTrack> loadFromBytes({required List<int> data}) => RustLib
      .instance
      .api
      .crateEngineXueHuaAudioEngineLoadFromBytes(that: this, data: data);

  /// 从本地文件系统绝对路径加载并播放（流式解码）。
  Future<XueHuaAudioTrack> loadFromPath({required String path}) => RustLib
      .instance
      .api
      .crateEngineXueHuaAudioEngineLoadFromPath(that: this, path: path);

  /// 停止并注销所有仍活跃的音轨。
  Future<void> stopAll() =>
      RustLib.instance.api.crateEngineXueHuaAudioEngineStopAll(that: this);

  /// 停止所有仍活跃的录制会话。
  Future<void> stopAllRecorders() => RustLib.instance.api
      .crateEngineXueHuaAudioEngineStopAllRecorders(that: this);
}

@sealed
class XueHuaAudioRecorderImpl extends RustOpaque
    implements XueHuaAudioRecorder {
  // Not to be used by end users
  XueHuaAudioRecorderImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  XueHuaAudioRecorderImpl.frbInternalSseDecode(
    BigInt ptr,
    int externalSizeOnNative,
  ) : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount: RustLib
        .instance
        .api
        .rust_arc_increment_strong_count_XueHuaAudioRecorder,
    rustArcDecrementStrongCount: RustLib
        .instance
        .api
        .rust_arc_decrement_strong_count_XueHuaAudioRecorder,
    rustArcDecrementStrongCountPtr: RustLib
        .instance
        .api
        .rust_arc_decrement_strong_count_XueHuaAudioRecorderPtr,
  );

  bool isPaused() => RustLib.instance.api
      .crateRecordingXueHuaAudioRecorderIsPaused(that: this);

  bool isRecording() => RustLib.instance.api
      .crateRecordingXueHuaAudioRecorderIsRecording(that: this);

  Future<void> pause() =>
      RustLib.instance.api.crateRecordingXueHuaAudioRecorderPause(that: this);

  Future<void> resume() =>
      RustLib.instance.api.crateRecordingXueHuaAudioRecorderResume(that: this);

  /// 立即返回；后台线程写入 WAV 并约每 100ms 推送 Progress 事件。
  Stream<XueHuaRecordingEvent> start({
    required String outputPath,
    int? deviceIndex,
  }) => RustLib.instance.api.crateRecordingXueHuaAudioRecorderStart(
    that: this,
    outputPath: outputPath,
    deviceIndex: deviceIndex,
  );

  /// 停止录制、finalize WAV，并推送 Completed 事件。
  Future<String> stop() =>
      RustLib.instance.api.crateRecordingXueHuaAudioRecorderStop(that: this);
}

@sealed
class XueHuaAudioTrackImpl extends RustOpaque implements XueHuaAudioTrack {
  // Not to be used by end users
  XueHuaAudioTrackImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  XueHuaAudioTrackImpl.frbInternalSseDecode(
    BigInt ptr,
    int externalSizeOnNative,
  ) : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_XueHuaAudioTrack,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_XueHuaAudioTrack,
    rustArcDecrementStrongCountPtr: RustLib
        .instance
        .api
        .rust_arc_decrement_strong_count_XueHuaAudioTrackPtr,
  );

  double? durationSecs() =>
      RustLib.instance.api.crateTrackXueHuaAudioTrackDurationSecs(that: this);

  bool isFinished() =>
      RustLib.instance.api.crateTrackXueHuaAudioTrackIsFinished(that: this);

  Future<bool> isPaused() =>
      RustLib.instance.api.crateTrackXueHuaAudioTrackIsPaused(that: this);

  bool isPlaying() =>
      RustLib.instance.api.crateTrackXueHuaAudioTrackIsPlaying(that: this);

  Future<void> pause() =>
      RustLib.instance.api.crateTrackXueHuaAudioTrackPause(that: this);

  XueHuaPlaybackProgress playbackProgress() => RustLib.instance.api
      .crateTrackXueHuaAudioTrackPlaybackProgress(that: this);

  double positionSecs() =>
      RustLib.instance.api.crateTrackXueHuaAudioTrackPositionSecs(that: this);

  /// 用内存字节替换当前音源（小文件 / 测试用）。
  Future<void> replaceFromBytes({required List<int> data}) => RustLib
      .instance
      .api
      .crateTrackXueHuaAudioTrackReplaceFromBytes(that: this, data: data);

  /// 用本地文件替换当前音源（先清空队列再 append 新 Decoder）。
  Future<void> replaceFromPath({required String path}) => RustLib.instance.api
      .crateTrackXueHuaAudioTrackReplaceFromPath(that: this, path: path);

  Future<void> resume() =>
      RustLib.instance.api.crateTrackXueHuaAudioTrackResume(that: this);

  /// 跳转到指定位置（秒）。底层调用 rodio `Player::try_seek`。
  Future<void> seekTo({required double positionSecs}) => RustLib.instance.api
      .crateTrackXueHuaAudioTrackSeekTo(that: this, positionSecs: positionSecs);

  Future<void> setVolume({required double volume}) => RustLib.instance.api
      .crateTrackXueHuaAudioTrackSetVolume(that: this, volume: volume);

  /// 停止播放、清空队列，并从 Engine 注册表注销。
  Future<void> stop() =>
      RustLib.instance.api.crateTrackXueHuaAudioTrackStop(that: this);

  Future<double> volume() =>
      RustLib.instance.api.crateTrackXueHuaAudioTrackVolume(that: this);

  /// 通过 Stream 推送播放进度（约每 100ms），播完或 stop 后结束。
  Stream<XueHuaPlaybackProgress> watchPlaybackProgress() => RustLib.instance.api
      .crateTrackXueHuaAudioTrackWatchPlaybackProgress(that: this);
}
