// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'engine.dart';
import 'error.dart';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';
import 'playback.dart';
import 'recording.dart';
import 'track.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_XueHuaAudioEnginePtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerXueHuaAudioEnginePtr;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_XueHuaAudioRecorderPtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerXueHuaAudioRecorderPtr;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_XueHuaAudioTrackPtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerXueHuaAudioTrackPtr;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  XueHuaAudioEngine
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerXueHuaAudioEngine(
    dynamic raw,
  );

  @protected
  XueHuaAudioRecorder
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerXueHuaAudioRecorder(
    dynamic raw,
  );

  @protected
  XueHuaAudioTrack
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerXueHuaAudioTrack(
    dynamic raw,
  );

  @protected
  XueHuaAudioRecorder
  dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerXueHuaAudioRecorder(
    dynamic raw,
  );

  @protected
  XueHuaAudioTrack
  dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerXueHuaAudioTrack(
    dynamic raw,
  );

  @protected
  XueHuaAudioEngine
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerXueHuaAudioEngine(
    dynamic raw,
  );

  @protected
  XueHuaAudioRecorder
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerXueHuaAudioRecorder(
    dynamic raw,
  );

  @protected
  XueHuaAudioTrack
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerXueHuaAudioTrack(
    dynamic raw,
  );

  @protected
  XueHuaAudioEngine
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerXueHuaAudioEngine(
    dynamic raw,
  );

  @protected
  XueHuaAudioRecorder
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerXueHuaAudioRecorder(
    dynamic raw,
  );

  @protected
  XueHuaAudioTrack
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerXueHuaAudioTrack(
    dynamic raw,
  );

  @protected
  RustStreamSink<XueHuaPlaybackProgress>
  dco_decode_StreamSink_xue_hua_playback_progress_Sse(dynamic raw);

  @protected
  RustStreamSink<XueHuaRecordingEvent>
  dco_decode_StreamSink_xue_hua_recording_event_Sse(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  double dco_decode_box_autoadd_f_64(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  XueHuaRecordingCompleted dco_decode_box_autoadd_xue_hua_recording_completed(
    dynamic raw,
  );

  @protected
  XueHuaRecordingProgress dco_decode_box_autoadd_xue_hua_recording_progress(
    dynamic raw,
  );

  @protected
  double dco_decode_f_32(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  double? dco_decode_opt_box_autoadd_f_64(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  XueHuaAudioError dco_decode_xue_hua_audio_error(dynamic raw);

  @protected
  XueHuaPlaybackProgress dco_decode_xue_hua_playback_progress(dynamic raw);

  @protected
  XueHuaRecordingCompleted dco_decode_xue_hua_recording_completed(dynamic raw);

  @protected
  XueHuaRecordingEvent dco_decode_xue_hua_recording_event(dynamic raw);

  @protected
  XueHuaRecordingProgress dco_decode_xue_hua_recording_progress(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  XueHuaAudioEngine
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerXueHuaAudioEngine(
    SseDeserializer deserializer,
  );

  @protected
  XueHuaAudioRecorder
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerXueHuaAudioRecorder(
    SseDeserializer deserializer,
  );

  @protected
  XueHuaAudioTrack
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerXueHuaAudioTrack(
    SseDeserializer deserializer,
  );

  @protected
  XueHuaAudioRecorder
  sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerXueHuaAudioRecorder(
    SseDeserializer deserializer,
  );

  @protected
  XueHuaAudioTrack
  sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerXueHuaAudioTrack(
    SseDeserializer deserializer,
  );

  @protected
  XueHuaAudioEngine
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerXueHuaAudioEngine(
    SseDeserializer deserializer,
  );

  @protected
  XueHuaAudioRecorder
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerXueHuaAudioRecorder(
    SseDeserializer deserializer,
  );

  @protected
  XueHuaAudioTrack
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerXueHuaAudioTrack(
    SseDeserializer deserializer,
  );

  @protected
  XueHuaAudioEngine
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerXueHuaAudioEngine(
    SseDeserializer deserializer,
  );

  @protected
  XueHuaAudioRecorder
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerXueHuaAudioRecorder(
    SseDeserializer deserializer,
  );

  @protected
  XueHuaAudioTrack
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerXueHuaAudioTrack(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<XueHuaPlaybackProgress>
  sse_decode_StreamSink_xue_hua_playback_progress_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<XueHuaRecordingEvent>
  sse_decode_StreamSink_xue_hua_recording_event_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  double sse_decode_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  XueHuaRecordingCompleted sse_decode_box_autoadd_xue_hua_recording_completed(
    SseDeserializer deserializer,
  );

  @protected
  XueHuaRecordingProgress sse_decode_box_autoadd_xue_hua_recording_progress(
    SseDeserializer deserializer,
  );

  @protected
  double sse_decode_f_32(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  XueHuaAudioError sse_decode_xue_hua_audio_error(SseDeserializer deserializer);

  @protected
  XueHuaPlaybackProgress sse_decode_xue_hua_playback_progress(
    SseDeserializer deserializer,
  );

  @protected
  XueHuaRecordingCompleted sse_decode_xue_hua_recording_completed(
    SseDeserializer deserializer,
  );

  @protected
  XueHuaRecordingEvent sse_decode_xue_hua_recording_event(
    SseDeserializer deserializer,
  );

  @protected
  XueHuaRecordingProgress sse_decode_xue_hua_recording_progress(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerXueHuaAudioEngine(
    XueHuaAudioEngine self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerXueHuaAudioRecorder(
    XueHuaAudioRecorder self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerXueHuaAudioTrack(
    XueHuaAudioTrack self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerXueHuaAudioRecorder(
    XueHuaAudioRecorder self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerXueHuaAudioTrack(
    XueHuaAudioTrack self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerXueHuaAudioEngine(
    XueHuaAudioEngine self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerXueHuaAudioRecorder(
    XueHuaAudioRecorder self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerXueHuaAudioTrack(
    XueHuaAudioTrack self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerXueHuaAudioEngine(
    XueHuaAudioEngine self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerXueHuaAudioRecorder(
    XueHuaAudioRecorder self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerXueHuaAudioTrack(
    XueHuaAudioTrack self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_xue_hua_playback_progress_Sse(
    RustStreamSink<XueHuaPlaybackProgress> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_xue_hua_recording_event_Sse(
    RustStreamSink<XueHuaRecordingEvent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_xue_hua_recording_completed(
    XueHuaRecordingCompleted self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_xue_hua_recording_progress(
    XueHuaRecordingProgress self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_xue_hua_audio_error(
    XueHuaAudioError self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_xue_hua_playback_progress(
    XueHuaPlaybackProgress self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_xue_hua_recording_completed(
    XueHuaRecordingCompleted self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_xue_hua_recording_event(
    XueHuaRecordingEvent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_xue_hua_recording_progress(
    XueHuaRecordingProgress self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerXueHuaAudioEngine(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerXueHuaAudioEngine(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerXueHuaAudioEnginePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_xue_hua_audio_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerXueHuaAudioEngine',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerXueHuaAudioEngine =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerXueHuaAudioEnginePtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerXueHuaAudioEngine(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerXueHuaAudioEngine(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerXueHuaAudioEnginePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_xue_hua_audio_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerXueHuaAudioEngine',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerXueHuaAudioEngine =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerXueHuaAudioEnginePtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerXueHuaAudioRecorder(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerXueHuaAudioRecorder(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerXueHuaAudioRecorderPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_xue_hua_audio_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerXueHuaAudioRecorder',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerXueHuaAudioRecorder =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerXueHuaAudioRecorderPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerXueHuaAudioRecorder(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerXueHuaAudioRecorder(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerXueHuaAudioRecorderPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_xue_hua_audio_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerXueHuaAudioRecorder',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerXueHuaAudioRecorder =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerXueHuaAudioRecorderPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerXueHuaAudioTrack(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerXueHuaAudioTrack(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerXueHuaAudioTrackPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_xue_hua_audio_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerXueHuaAudioTrack',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerXueHuaAudioTrack =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerXueHuaAudioTrackPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerXueHuaAudioTrack(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerXueHuaAudioTrack(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerXueHuaAudioTrackPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_xue_hua_audio_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerXueHuaAudioTrack',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerXueHuaAudioTrack =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerXueHuaAudioTrackPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();
}
