// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'error.dart';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'recording.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `duration_secs`, `join_writer_thread`, `new`, `new`, `open_microphone`, `progress_snapshot`, `request_stop`, `run_writer_thread`, `stop_shared_recorder`, `unregister`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `RecorderShared`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `drop`

Future<List<String>> listInputDevices() =>
    RustLib.instance.api.crateRecordingListInputDevices();

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<XueHuaAudioRecorder>>
abstract class XueHuaAudioRecorder implements RustOpaqueInterface {
  bool isPaused();

  bool isRecording();

  Future<void> pause();

  Future<void> resume();

  /// 立即返回；后台线程写入 WAV 并约每 100ms 推送 Progress 事件。
  Stream<XueHuaRecordingEvent> start({
    required String outputPath,
    int? deviceIndex,
  });

  /// 停止录制、finalize WAV，并推送 Completed 事件。
  Future<String> stop();
}

/// 录制完成事件。
class XueHuaRecordingCompleted {
  final String outputPath;
  final double durationSecs;

  const XueHuaRecordingCompleted({
    required this.outputPath,
    required this.durationSecs,
  });

  @override
  int get hashCode => outputPath.hashCode ^ durationSecs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is XueHuaRecordingCompleted &&
          runtimeType == other.runtimeType &&
          outputPath == other.outputPath &&
          durationSecs == other.durationSecs;
}

@freezed
sealed class XueHuaRecordingEvent with _$XueHuaRecordingEvent {
  const XueHuaRecordingEvent._();

  const factory XueHuaRecordingEvent.progress(XueHuaRecordingProgress field0) =
      XueHuaRecordingEvent_Progress;
  const factory XueHuaRecordingEvent.completed(
    XueHuaRecordingCompleted field0,
  ) = XueHuaRecordingEvent_Completed;
}

/// 录制进度快照（通过 Stream 推送）。
class XueHuaRecordingProgress {
  final bool isRecording;
  final bool isPaused;
  final double durationSecs;

  /// 最近 buffer 峰值 0.0~1.0
  final double level;

  const XueHuaRecordingProgress({
    required this.isRecording,
    required this.isPaused,
    required this.durationSecs,
    required this.level,
  });

  @override
  int get hashCode =>
      isRecording.hashCode ^
      isPaused.hashCode ^
      durationSecs.hashCode ^
      level.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is XueHuaRecordingProgress &&
          runtimeType == other.runtimeType &&
          isRecording == other.isRecording &&
          isPaused == other.isPaused &&
          durationSecs == other.durationSecs &&
          level == other.level;
}
