// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'error.dart';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'playback.dart';

// These functions are ignored because they are not marked as `pub`: `new`, `new`, `open_decoder_from_bytes`, `open_decoder_from_path`, `run_progress_watcher`, `snapshot_progress`, `stop_watching`, `unregister`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `ProgressWatcher`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `drop`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<XueHuaAudioTrack>>
abstract class XueHuaAudioTrack implements RustOpaqueInterface {
  double? durationSecs();

  bool isFinished();

  Future<bool> isPaused();

  bool isPlaying();

  Future<void> pause();

  XueHuaPlaybackProgress playbackProgress();

  double positionSecs();

  /// 用内存字节替换当前音源（小文件 / 测试用）。
  Future<void> replaceFromBytes({required List<int> data});

  /// 用本地文件替换当前音源（先清空队列再 append 新 Decoder）。
  Future<void> replaceFromPath({required String path});

  Future<void> resume();

  /// 跳转到指定位置（秒）。底层调用 rodio `Player::try_seek`。
  Future<void> seekTo({required double positionSecs});

  Future<void> setVolume({required double volume});

  /// 停止播放、清空队列，并从 Engine 注册表注销。
  Future<void> stop();

  Future<double> volume();

  /// 通过 Stream 推送播放进度（约每 100ms），播完或 stop 后结束。
  Stream<XueHuaPlaybackProgress> watchPlaybackProgress();
}
