// Autogenerated from Pigeon (v27.3.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#ifndef PIGEON_MESSAGES_G_H_
#define PIGEON_MESSAGES_G_H_

#include <flutter_linux/flutter_linux.h>

G_BEGIN_DECLS

/**
 * XhaMessagesSourceTypeMessage:
 * XUE_HUA_AUDIO_PLATFORM_INTERFACE_SOURCE_TYPE_MESSAGE_FILE:
 * A local file path. / 本地文件路径。
 * XUE_HUA_AUDIO_PLATFORM_INTERFACE_SOURCE_TYPE_MESSAGE_URL:
 * A remote HTTP(S) URL. / 远程 HTTP(S) 网络地址。
 * XUE_HUA_AUDIO_PLATFORM_INTERFACE_SOURCE_TYPE_MESSAGE_ASSET:
 * A Flutter asset key. / Flutter Asset 资源键。
 *
 * The kind of an audio source. / 音频源的种类。
 */
typedef enum {
  XUE_HUA_AUDIO_PLATFORM_INTERFACE_SOURCE_TYPE_MESSAGE_FILE = 0,
  XUE_HUA_AUDIO_PLATFORM_INTERFACE_SOURCE_TYPE_MESSAGE_URL = 1,
  XUE_HUA_AUDIO_PLATFORM_INTERFACE_SOURCE_TYPE_MESSAGE_ASSET = 2
} XhaMessagesSourceTypeMessage;

/**
 * XhaMessagesEncoderMessage:
 * XUE_HUA_AUDIO_PLATFORM_INTERFACE_ENCODER_MESSAGE_WAV:
 * Linear PCM in a WAV container. / WAV 容器中的线性 PCM。
 * XUE_HUA_AUDIO_PLATFORM_INTERFACE_ENCODER_MESSAGE_AAC_LC:
 * AAC-LC in an MPEG-4 container. / MPEG-4 容器中的 AAC-LC。
 * XUE_HUA_AUDIO_PLATFORM_INTERFACE_ENCODER_MESSAGE_OPUS:
 * Opus (Ogg or WebM container, platform dependent). / Opus 编码（Ogg 或 WebM 容器，视平台而定）。
 *
 * The audio encoder used when recording. / 录音时使用的编码器。
 */
typedef enum {
  XUE_HUA_AUDIO_PLATFORM_INTERFACE_ENCODER_MESSAGE_WAV = 0,
  XUE_HUA_AUDIO_PLATFORM_INTERFACE_ENCODER_MESSAGE_AAC_LC = 1,
  XUE_HUA_AUDIO_PLATFORM_INTERFACE_ENCODER_MESSAGE_OPUS = 2
} XhaMessagesEncoderMessage;

/**
 * XhaMessagesAudioSourceMessage:
 *
 * Wire representation of an audio source. / 音频源的跨端传输结构。
 */

G_DECLARE_FINAL_TYPE(XhaMessagesAudioSourceMessage, xha_messages_audio_source_message, XHA_MESSAGES, AUDIO_SOURCE_MESSAGE, GObject)

/**
 * xha_messages_audio_source_message_new:
 * type_: field in this object.
 * uri: field in this object.
 * headers: field in this object.
 *
 * Creates a new #AudioSourceMessage object.
 *
 * Returns: a new #XhaMessagesAudioSourceMessage
 */
XhaMessagesAudioSourceMessage* xha_messages_audio_source_message_new(XhaMessagesSourceTypeMessage type_, const gchar* uri, FlValue* headers);

/**
 * xha_messages_audio_source_message_get_type_
 * @object: a #XhaMessagesAudioSourceMessage.
 *
 * The kind of source. / 源的种类。
 *
 * Returns: the field value.
 */
XhaMessagesSourceTypeMessage xha_messages_audio_source_message_get_type_(XhaMessagesAudioSourceMessage* object);

/**
 * xha_messages_audio_source_message_get_uri
 * @object: a #XhaMessagesAudioSourceMessage.
 *
 * File path, URL, or fully-resolved asset key depending on [type].
 * 依据 [type] 不同，可能是文件路径、URL 或已解析的 asset 键。
 *
 * Returns: the field value.
 */
const gchar* xha_messages_audio_source_message_get_uri(XhaMessagesAudioSourceMessage* object);

/**
 * xha_messages_audio_source_message_get_headers
 * @object: a #XhaMessagesAudioSourceMessage.
 *
 * Optional HTTP headers, only meaningful for [SourceTypeMessage.url].
 * 可选的 HTTP 请求头，仅对 [SourceTypeMessage.url] 有意义。
 *
 * Returns: the field value.
 */
FlValue* xha_messages_audio_source_message_get_headers(XhaMessagesAudioSourceMessage* object);

/**
 * xha_messages_audio_source_message_equals:
 * @a: a #XhaMessagesAudioSourceMessage.
 * @b: another #XhaMessagesAudioSourceMessage.
 *
 * Checks if two #XhaMessagesAudioSourceMessage objects are equal.
 *
 * Returns: TRUE if @a and @b are equal.
 */
gboolean xha_messages_audio_source_message_equals(XhaMessagesAudioSourceMessage* a, XhaMessagesAudioSourceMessage* b);

/**
 * xha_messages_audio_source_message_hash:
 * @object: a #XhaMessagesAudioSourceMessage.
 *
 * Calculates a hash code for a #XhaMessagesAudioSourceMessage object.
 *
 * Returns: the hash code.
 */
guint xha_messages_audio_source_message_hash(XhaMessagesAudioSourceMessage* object);

/**
 * xha_messages_audio_source_message_to_string:
 * @object: a #XhaMessagesAudioSourceMessage.
 *
 * Returns a string representation of a #XhaMessagesAudioSourceMessage object.
 *
 * Returns: (transfer full): a new string, free with g_free().
 */
gchar* xha_messages_audio_source_message_to_string(XhaMessagesAudioSourceMessage* object);

/**
 * XhaMessagesRecordConfigMessage:
 *
 * Wire representation of a recording configuration. / 录音配置的跨端传输结构。
 */

G_DECLARE_FINAL_TYPE(XhaMessagesRecordConfigMessage, xha_messages_record_config_message, XHA_MESSAGES, RECORD_CONFIG_MESSAGE, GObject)

/**
 * xha_messages_record_config_message_new:
 * encoder: field in this object.
 * sample_rate: field in this object.
 * num_channels: field in this object.
 * bit_rate: field in this object.
 * amplitude_interval_ms: field in this object.
 * device_id: field in this object.
 *
 * Creates a new #RecordConfigMessage object.
 *
 * Returns: a new #XhaMessagesRecordConfigMessage
 */
XhaMessagesRecordConfigMessage* xha_messages_record_config_message_new(XhaMessagesEncoderMessage encoder, int64_t sample_rate, int64_t num_channels, int64_t bit_rate, int64_t amplitude_interval_ms, const gchar* device_id);

/**
 * xha_messages_record_config_message_get_encoder
 * @object: a #XhaMessagesRecordConfigMessage.
 *
 * Encoder to use. / 使用的编码器。
 *
 * Returns: the field value.
 */
XhaMessagesEncoderMessage xha_messages_record_config_message_get_encoder(XhaMessagesRecordConfigMessage* object);

/**
 * xha_messages_record_config_message_get_sample_rate
 * @object: a #XhaMessagesRecordConfigMessage.
 *
 * Sample rate in Hz. / 采样率（Hz）。
 *
 * Returns: the field value.
 */
int64_t xha_messages_record_config_message_get_sample_rate(XhaMessagesRecordConfigMessage* object);

/**
 * xha_messages_record_config_message_get_num_channels
 * @object: a #XhaMessagesRecordConfigMessage.
 *
 * Number of channels (1 = mono, 2 = stereo). / 声道数（1 单声道，2 立体声）。
 *
 * Returns: the field value.
 */
int64_t xha_messages_record_config_message_get_num_channels(XhaMessagesRecordConfigMessage* object);

/**
 * xha_messages_record_config_message_get_bit_rate
 * @object: a #XhaMessagesRecordConfigMessage.
 *
 * Bit rate in bits per second (compressed encoders only).
 * 比特率（bit/s，仅压缩编码器使用）。
 *
 * Returns: the field value.
 */
int64_t xha_messages_record_config_message_get_bit_rate(XhaMessagesRecordConfigMessage* object);

/**
 * xha_messages_record_config_message_get_amplitude_interval_ms
 * @object: a #XhaMessagesRecordConfigMessage.
 *
 * Interval between amplitude events in milliseconds.
 * 振幅事件的推送间隔（毫秒）。
 *
 * Returns: the field value.
 */
int64_t xha_messages_record_config_message_get_amplitude_interval_ms(XhaMessagesRecordConfigMessage* object);

/**
 * xha_messages_record_config_message_get_device_id
 * @object: a #XhaMessagesRecordConfigMessage.
 *
 * Preferred input device id, `null` for the system default.
 * 期望使用的输入设备 id，`null` 表示系统默认设备。
 *
 * Returns: the field value.
 */
const gchar* xha_messages_record_config_message_get_device_id(XhaMessagesRecordConfigMessage* object);

/**
 * xha_messages_record_config_message_equals:
 * @a: a #XhaMessagesRecordConfigMessage.
 * @b: another #XhaMessagesRecordConfigMessage.
 *
 * Checks if two #XhaMessagesRecordConfigMessage objects are equal.
 *
 * Returns: TRUE if @a and @b are equal.
 */
gboolean xha_messages_record_config_message_equals(XhaMessagesRecordConfigMessage* a, XhaMessagesRecordConfigMessage* b);

/**
 * xha_messages_record_config_message_hash:
 * @object: a #XhaMessagesRecordConfigMessage.
 *
 * Calculates a hash code for a #XhaMessagesRecordConfigMessage object.
 *
 * Returns: the hash code.
 */
guint xha_messages_record_config_message_hash(XhaMessagesRecordConfigMessage* object);

/**
 * xha_messages_record_config_message_to_string:
 * @object: a #XhaMessagesRecordConfigMessage.
 *
 * Returns a string representation of a #XhaMessagesRecordConfigMessage object.
 *
 * Returns: (transfer full): a new string, free with g_free().
 */
gchar* xha_messages_record_config_message_to_string(XhaMessagesRecordConfigMessage* object);

/**
 * XhaMessagesAudioDeviceMessage:
 *
 * Wire representation of an audio device (input or output).
 * 音频设备（输入或输出）的跨端传输结构。
 */

G_DECLARE_FINAL_TYPE(XhaMessagesAudioDeviceMessage, xha_messages_audio_device_message, XHA_MESSAGES, AUDIO_DEVICE_MESSAGE, GObject)

/**
 * xha_messages_audio_device_message_new:
 * id: field in this object.
 * label: field in this object.
 *
 * Creates a new #AudioDeviceMessage object.
 *
 * Returns: a new #XhaMessagesAudioDeviceMessage
 */
XhaMessagesAudioDeviceMessage* xha_messages_audio_device_message_new(const gchar* id, const gchar* label);

/**
 * xha_messages_audio_device_message_get_id
 * @object: a #XhaMessagesAudioDeviceMessage.
 *
 * Platform-specific stable device identifier. / 平台相关的稳定设备标识。
 *
 * Returns: the field value.
 */
const gchar* xha_messages_audio_device_message_get_id(XhaMessagesAudioDeviceMessage* object);

/**
 * xha_messages_audio_device_message_get_label
 * @object: a #XhaMessagesAudioDeviceMessage.
 *
 * Human-readable device name. / 供人阅读的设备名称。
 *
 * Returns: the field value.
 */
const gchar* xha_messages_audio_device_message_get_label(XhaMessagesAudioDeviceMessage* object);

/**
 * xha_messages_audio_device_message_equals:
 * @a: a #XhaMessagesAudioDeviceMessage.
 * @b: another #XhaMessagesAudioDeviceMessage.
 *
 * Checks if two #XhaMessagesAudioDeviceMessage objects are equal.
 *
 * Returns: TRUE if @a and @b are equal.
 */
gboolean xha_messages_audio_device_message_equals(XhaMessagesAudioDeviceMessage* a, XhaMessagesAudioDeviceMessage* b);

/**
 * xha_messages_audio_device_message_hash:
 * @object: a #XhaMessagesAudioDeviceMessage.
 *
 * Calculates a hash code for a #XhaMessagesAudioDeviceMessage object.
 *
 * Returns: the hash code.
 */
guint xha_messages_audio_device_message_hash(XhaMessagesAudioDeviceMessage* object);

/**
 * xha_messages_audio_device_message_to_string:
 * @object: a #XhaMessagesAudioDeviceMessage.
 *
 * Returns a string representation of a #XhaMessagesAudioDeviceMessage object.
 *
 * Returns: (transfer full): a new string, free with g_free().
 */
gchar* xha_messages_audio_device_message_to_string(XhaMessagesAudioDeviceMessage* object);

G_DECLARE_FINAL_TYPE(XhaMessagesMessageCodec, xha_messages_message_codec, XHA_MESSAGES, MESSAGE_CODEC, FlStandardMessageCodec)

/**
 * Custom type ID constants:
 *
 * Constants used to identify custom types in the codec.
 * They are used in the codec to encode and decode custom types.
 * They may be used in custom object creation functions to identify the type.
 */
extern const int xha_messages_source_type_message_type_id;
extern const int xha_messages_encoder_message_type_id;
extern const int xha_messages_audio_source_message_type_id;
extern const int xha_messages_record_config_message_type_id;
extern const int xha_messages_audio_device_message_type_id;

G_DECLARE_FINAL_TYPE(XhaMessagesAudioPlayerHostApi, xha_messages_audio_player_host_api, XHA_MESSAGES, AUDIO_PLAYER_HOST_API, GObject)

G_DECLARE_FINAL_TYPE(XhaMessagesAudioPlayerHostApiResponseHandle, xha_messages_audio_player_host_api_response_handle, XHA_MESSAGES, AUDIO_PLAYER_HOST_API_RESPONSE_HANDLE, GObject)

G_DECLARE_FINAL_TYPE(XhaMessagesAudioPlayerHostApiCreatePlayerResponse, xha_messages_audio_player_host_api_create_player_response, XHA_MESSAGES, AUDIO_PLAYER_HOST_API_CREATE_PLAYER_RESPONSE, GObject)

/**
 * xha_messages_audio_player_host_api_create_player_response_new:
 *
 * Creates a new response to AudioPlayerHostApi.createPlayer.
 *
 * Returns: a new #XhaMessagesAudioPlayerHostApiCreatePlayerResponse
 */
XhaMessagesAudioPlayerHostApiCreatePlayerResponse* xha_messages_audio_player_host_api_create_player_response_new(int64_t return_value);

/**
 * xha_messages_audio_player_host_api_create_player_response_new_error:
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Creates a new error response to AudioPlayerHostApi.createPlayer.
 *
 * Returns: a new #XhaMessagesAudioPlayerHostApiCreatePlayerResponse
 */
XhaMessagesAudioPlayerHostApiCreatePlayerResponse* xha_messages_audio_player_host_api_create_player_response_new_error(const gchar* code, const gchar* message, FlValue* details);

G_DECLARE_FINAL_TYPE(XhaMessagesAudioPlayerHostApiPlayResponse, xha_messages_audio_player_host_api_play_response, XHA_MESSAGES, AUDIO_PLAYER_HOST_API_PLAY_RESPONSE, GObject)

/**
 * xha_messages_audio_player_host_api_play_response_new:
 *
 * Creates a new response to AudioPlayerHostApi.play.
 *
 * Returns: a new #XhaMessagesAudioPlayerHostApiPlayResponse
 */
XhaMessagesAudioPlayerHostApiPlayResponse* xha_messages_audio_player_host_api_play_response_new();

/**
 * xha_messages_audio_player_host_api_play_response_new_error:
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Creates a new error response to AudioPlayerHostApi.play.
 *
 * Returns: a new #XhaMessagesAudioPlayerHostApiPlayResponse
 */
XhaMessagesAudioPlayerHostApiPlayResponse* xha_messages_audio_player_host_api_play_response_new_error(const gchar* code, const gchar* message, FlValue* details);

G_DECLARE_FINAL_TYPE(XhaMessagesAudioPlayerHostApiPauseResponse, xha_messages_audio_player_host_api_pause_response, XHA_MESSAGES, AUDIO_PLAYER_HOST_API_PAUSE_RESPONSE, GObject)

/**
 * xha_messages_audio_player_host_api_pause_response_new:
 *
 * Creates a new response to AudioPlayerHostApi.pause.
 *
 * Returns: a new #XhaMessagesAudioPlayerHostApiPauseResponse
 */
XhaMessagesAudioPlayerHostApiPauseResponse* xha_messages_audio_player_host_api_pause_response_new();

/**
 * xha_messages_audio_player_host_api_pause_response_new_error:
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Creates a new error response to AudioPlayerHostApi.pause.
 *
 * Returns: a new #XhaMessagesAudioPlayerHostApiPauseResponse
 */
XhaMessagesAudioPlayerHostApiPauseResponse* xha_messages_audio_player_host_api_pause_response_new_error(const gchar* code, const gchar* message, FlValue* details);

G_DECLARE_FINAL_TYPE(XhaMessagesAudioPlayerHostApiStopResponse, xha_messages_audio_player_host_api_stop_response, XHA_MESSAGES, AUDIO_PLAYER_HOST_API_STOP_RESPONSE, GObject)

/**
 * xha_messages_audio_player_host_api_stop_response_new:
 *
 * Creates a new response to AudioPlayerHostApi.stop.
 *
 * Returns: a new #XhaMessagesAudioPlayerHostApiStopResponse
 */
XhaMessagesAudioPlayerHostApiStopResponse* xha_messages_audio_player_host_api_stop_response_new();

/**
 * xha_messages_audio_player_host_api_stop_response_new_error:
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Creates a new error response to AudioPlayerHostApi.stop.
 *
 * Returns: a new #XhaMessagesAudioPlayerHostApiStopResponse
 */
XhaMessagesAudioPlayerHostApiStopResponse* xha_messages_audio_player_host_api_stop_response_new_error(const gchar* code, const gchar* message, FlValue* details);

G_DECLARE_FINAL_TYPE(XhaMessagesAudioPlayerHostApiSetVolumeResponse, xha_messages_audio_player_host_api_set_volume_response, XHA_MESSAGES, AUDIO_PLAYER_HOST_API_SET_VOLUME_RESPONSE, GObject)

/**
 * xha_messages_audio_player_host_api_set_volume_response_new:
 *
 * Creates a new response to AudioPlayerHostApi.setVolume.
 *
 * Returns: a new #XhaMessagesAudioPlayerHostApiSetVolumeResponse
 */
XhaMessagesAudioPlayerHostApiSetVolumeResponse* xha_messages_audio_player_host_api_set_volume_response_new();

/**
 * xha_messages_audio_player_host_api_set_volume_response_new_error:
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Creates a new error response to AudioPlayerHostApi.setVolume.
 *
 * Returns: a new #XhaMessagesAudioPlayerHostApiSetVolumeResponse
 */
XhaMessagesAudioPlayerHostApiSetVolumeResponse* xha_messages_audio_player_host_api_set_volume_response_new_error(const gchar* code, const gchar* message, FlValue* details);

G_DECLARE_FINAL_TYPE(XhaMessagesAudioPlayerHostApiSetSpeedResponse, xha_messages_audio_player_host_api_set_speed_response, XHA_MESSAGES, AUDIO_PLAYER_HOST_API_SET_SPEED_RESPONSE, GObject)

/**
 * xha_messages_audio_player_host_api_set_speed_response_new:
 *
 * Creates a new response to AudioPlayerHostApi.setSpeed.
 *
 * Returns: a new #XhaMessagesAudioPlayerHostApiSetSpeedResponse
 */
XhaMessagesAudioPlayerHostApiSetSpeedResponse* xha_messages_audio_player_host_api_set_speed_response_new();

/**
 * xha_messages_audio_player_host_api_set_speed_response_new_error:
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Creates a new error response to AudioPlayerHostApi.setSpeed.
 *
 * Returns: a new #XhaMessagesAudioPlayerHostApiSetSpeedResponse
 */
XhaMessagesAudioPlayerHostApiSetSpeedResponse* xha_messages_audio_player_host_api_set_speed_response_new_error(const gchar* code, const gchar* message, FlValue* details);

G_DECLARE_FINAL_TYPE(XhaMessagesAudioPlayerHostApiSetLoopingResponse, xha_messages_audio_player_host_api_set_looping_response, XHA_MESSAGES, AUDIO_PLAYER_HOST_API_SET_LOOPING_RESPONSE, GObject)

/**
 * xha_messages_audio_player_host_api_set_looping_response_new:
 *
 * Creates a new response to AudioPlayerHostApi.setLooping.
 *
 * Returns: a new #XhaMessagesAudioPlayerHostApiSetLoopingResponse
 */
XhaMessagesAudioPlayerHostApiSetLoopingResponse* xha_messages_audio_player_host_api_set_looping_response_new();

/**
 * xha_messages_audio_player_host_api_set_looping_response_new_error:
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Creates a new error response to AudioPlayerHostApi.setLooping.
 *
 * Returns: a new #XhaMessagesAudioPlayerHostApiSetLoopingResponse
 */
XhaMessagesAudioPlayerHostApiSetLoopingResponse* xha_messages_audio_player_host_api_set_looping_response_new_error(const gchar* code, const gchar* message, FlValue* details);

G_DECLARE_FINAL_TYPE(XhaMessagesAudioPlayerHostApiGetPositionResponse, xha_messages_audio_player_host_api_get_position_response, XHA_MESSAGES, AUDIO_PLAYER_HOST_API_GET_POSITION_RESPONSE, GObject)

/**
 * xha_messages_audio_player_host_api_get_position_response_new:
 *
 * Creates a new response to AudioPlayerHostApi.getPosition.
 *
 * Returns: a new #XhaMessagesAudioPlayerHostApiGetPositionResponse
 */
XhaMessagesAudioPlayerHostApiGetPositionResponse* xha_messages_audio_player_host_api_get_position_response_new(int64_t return_value);

/**
 * xha_messages_audio_player_host_api_get_position_response_new_error:
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Creates a new error response to AudioPlayerHostApi.getPosition.
 *
 * Returns: a new #XhaMessagesAudioPlayerHostApiGetPositionResponse
 */
XhaMessagesAudioPlayerHostApiGetPositionResponse* xha_messages_audio_player_host_api_get_position_response_new_error(const gchar* code, const gchar* message, FlValue* details);

G_DECLARE_FINAL_TYPE(XhaMessagesAudioPlayerHostApiGetDurationResponse, xha_messages_audio_player_host_api_get_duration_response, XHA_MESSAGES, AUDIO_PLAYER_HOST_API_GET_DURATION_RESPONSE, GObject)

/**
 * xha_messages_audio_player_host_api_get_duration_response_new:
 *
 * Creates a new response to AudioPlayerHostApi.getDuration.
 *
 * Returns: a new #XhaMessagesAudioPlayerHostApiGetDurationResponse
 */
XhaMessagesAudioPlayerHostApiGetDurationResponse* xha_messages_audio_player_host_api_get_duration_response_new(int64_t* return_value);

/**
 * xha_messages_audio_player_host_api_get_duration_response_new_error:
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Creates a new error response to AudioPlayerHostApi.getDuration.
 *
 * Returns: a new #XhaMessagesAudioPlayerHostApiGetDurationResponse
 */
XhaMessagesAudioPlayerHostApiGetDurationResponse* xha_messages_audio_player_host_api_get_duration_response_new_error(const gchar* code, const gchar* message, FlValue* details);

G_DECLARE_FINAL_TYPE(XhaMessagesAudioPlayerHostApiDisposePlayerResponse, xha_messages_audio_player_host_api_dispose_player_response, XHA_MESSAGES, AUDIO_PLAYER_HOST_API_DISPOSE_PLAYER_RESPONSE, GObject)

/**
 * xha_messages_audio_player_host_api_dispose_player_response_new:
 *
 * Creates a new response to AudioPlayerHostApi.disposePlayer.
 *
 * Returns: a new #XhaMessagesAudioPlayerHostApiDisposePlayerResponse
 */
XhaMessagesAudioPlayerHostApiDisposePlayerResponse* xha_messages_audio_player_host_api_dispose_player_response_new();

/**
 * xha_messages_audio_player_host_api_dispose_player_response_new_error:
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Creates a new error response to AudioPlayerHostApi.disposePlayer.
 *
 * Returns: a new #XhaMessagesAudioPlayerHostApiDisposePlayerResponse
 */
XhaMessagesAudioPlayerHostApiDisposePlayerResponse* xha_messages_audio_player_host_api_dispose_player_response_new_error(const gchar* code, const gchar* message, FlValue* details);

/**
 * XhaMessagesAudioPlayerHostApiVTable:
 *
 * Table of functions exposed by AudioPlayerHostApi to be implemented by the API provider.
 */
typedef struct {
  XhaMessagesAudioPlayerHostApiCreatePlayerResponse* (*create_player)(gpointer user_data);
  void (*set_source)(int64_t player_id, XhaMessagesAudioSourceMessage* source, XhaMessagesAudioPlayerHostApiResponseHandle* response_handle, gpointer user_data);
  XhaMessagesAudioPlayerHostApiPlayResponse* (*play)(int64_t player_id, gpointer user_data);
  XhaMessagesAudioPlayerHostApiPauseResponse* (*pause)(int64_t player_id, gpointer user_data);
  XhaMessagesAudioPlayerHostApiStopResponse* (*stop)(int64_t player_id, gpointer user_data);
  void (*seek_to)(int64_t player_id, int64_t position_ms, XhaMessagesAudioPlayerHostApiResponseHandle* response_handle, gpointer user_data);
  XhaMessagesAudioPlayerHostApiSetVolumeResponse* (*set_volume)(int64_t player_id, double volume, gpointer user_data);
  XhaMessagesAudioPlayerHostApiSetSpeedResponse* (*set_speed)(int64_t player_id, double speed, gpointer user_data);
  XhaMessagesAudioPlayerHostApiSetLoopingResponse* (*set_looping)(int64_t player_id, gboolean looping, gpointer user_data);
  XhaMessagesAudioPlayerHostApiGetPositionResponse* (*get_position)(int64_t player_id, gpointer user_data);
  XhaMessagesAudioPlayerHostApiGetDurationResponse* (*get_duration)(int64_t player_id, gpointer user_data);
  void (*list_output_devices)(XhaMessagesAudioPlayerHostApiResponseHandle* response_handle, gpointer user_data);
  void (*get_output_device)(int64_t player_id, XhaMessagesAudioPlayerHostApiResponseHandle* response_handle, gpointer user_data);
  void (*set_output_device)(int64_t player_id, const gchar* device_id, XhaMessagesAudioPlayerHostApiResponseHandle* response_handle, gpointer user_data);
  XhaMessagesAudioPlayerHostApiDisposePlayerResponse* (*dispose_player)(int64_t player_id, gpointer user_data);
} XhaMessagesAudioPlayerHostApiVTable;

/**
 * xha_messages_audio_player_host_api_set_method_handlers:
 *
 * @messenger: an #FlBinaryMessenger.
 * @suffix: (allow-none): a suffix to add to the API or %NULL for none.
 * @vtable: implementations of the methods in this API.
 * @user_data: (closure): user data to pass to the functions in @vtable.
 * @user_data_free_func: (allow-none): a function which gets called to free @user_data, or %NULL.
 *
 * Connects the method handlers in the AudioPlayerHostApi API.
 */
void xha_messages_audio_player_host_api_set_method_handlers(FlBinaryMessenger* messenger, const gchar* suffix, const XhaMessagesAudioPlayerHostApiVTable* vtable, gpointer user_data, GDestroyNotify user_data_free_func);

/**
 * xha_messages_audio_player_host_api_clear_method_handlers:
 *
 * @messenger: an #FlBinaryMessenger.
 * @suffix: (allow-none): a suffix to add to the API or %NULL for none.
 *
 * Clears the method handlers in the AudioPlayerHostApi API.
 */
void xha_messages_audio_player_host_api_clear_method_handlers(FlBinaryMessenger* messenger, const gchar* suffix);

/**
 * xha_messages_audio_player_host_api_respond_set_source:
 * @response_handle: a #XhaMessagesAudioPlayerHostApiResponseHandle.
 * @return_value: location to write the value returned by this method.
 *
 * Responds to AudioPlayerHostApi.setSource. 
 */
void xha_messages_audio_player_host_api_respond_set_source(XhaMessagesAudioPlayerHostApiResponseHandle* response_handle, int64_t* return_value);

/**
 * xha_messages_audio_player_host_api_respond_error_set_source:
 * @response_handle: a #XhaMessagesAudioPlayerHostApiResponseHandle.
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Responds with an error to AudioPlayerHostApi.setSource. 
 */
void xha_messages_audio_player_host_api_respond_error_set_source(XhaMessagesAudioPlayerHostApiResponseHandle* response_handle, const gchar* code, const gchar* message, FlValue* details);

/**
 * xha_messages_audio_player_host_api_respond_seek_to:
 * @response_handle: a #XhaMessagesAudioPlayerHostApiResponseHandle.
 *
 * Responds to AudioPlayerHostApi.seekTo. 
 */
void xha_messages_audio_player_host_api_respond_seek_to(XhaMessagesAudioPlayerHostApiResponseHandle* response_handle);

/**
 * xha_messages_audio_player_host_api_respond_error_seek_to:
 * @response_handle: a #XhaMessagesAudioPlayerHostApiResponseHandle.
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Responds with an error to AudioPlayerHostApi.seekTo. 
 */
void xha_messages_audio_player_host_api_respond_error_seek_to(XhaMessagesAudioPlayerHostApiResponseHandle* response_handle, const gchar* code, const gchar* message, FlValue* details);

/**
 * xha_messages_audio_player_host_api_respond_list_output_devices:
 * @response_handle: a #XhaMessagesAudioPlayerHostApiResponseHandle.
 * @return_value: location to write the value returned by this method.
 *
 * Responds to AudioPlayerHostApi.listOutputDevices. 
 */
void xha_messages_audio_player_host_api_respond_list_output_devices(XhaMessagesAudioPlayerHostApiResponseHandle* response_handle, FlValue* return_value);

/**
 * xha_messages_audio_player_host_api_respond_error_list_output_devices:
 * @response_handle: a #XhaMessagesAudioPlayerHostApiResponseHandle.
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Responds with an error to AudioPlayerHostApi.listOutputDevices. 
 */
void xha_messages_audio_player_host_api_respond_error_list_output_devices(XhaMessagesAudioPlayerHostApiResponseHandle* response_handle, const gchar* code, const gchar* message, FlValue* details);

/**
 * xha_messages_audio_player_host_api_respond_get_output_device:
 * @response_handle: a #XhaMessagesAudioPlayerHostApiResponseHandle.
 * @return_value: location to write the value returned by this method.
 *
 * Responds to AudioPlayerHostApi.getOutputDevice. 
 */
void xha_messages_audio_player_host_api_respond_get_output_device(XhaMessagesAudioPlayerHostApiResponseHandle* response_handle, XhaMessagesAudioDeviceMessage* return_value);

/**
 * xha_messages_audio_player_host_api_respond_error_get_output_device:
 * @response_handle: a #XhaMessagesAudioPlayerHostApiResponseHandle.
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Responds with an error to AudioPlayerHostApi.getOutputDevice. 
 */
void xha_messages_audio_player_host_api_respond_error_get_output_device(XhaMessagesAudioPlayerHostApiResponseHandle* response_handle, const gchar* code, const gchar* message, FlValue* details);

/**
 * xha_messages_audio_player_host_api_respond_set_output_device:
 * @response_handle: a #XhaMessagesAudioPlayerHostApiResponseHandle.
 *
 * Responds to AudioPlayerHostApi.setOutputDevice. 
 */
void xha_messages_audio_player_host_api_respond_set_output_device(XhaMessagesAudioPlayerHostApiResponseHandle* response_handle);

/**
 * xha_messages_audio_player_host_api_respond_error_set_output_device:
 * @response_handle: a #XhaMessagesAudioPlayerHostApiResponseHandle.
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Responds with an error to AudioPlayerHostApi.setOutputDevice. 
 */
void xha_messages_audio_player_host_api_respond_error_set_output_device(XhaMessagesAudioPlayerHostApiResponseHandle* response_handle, const gchar* code, const gchar* message, FlValue* details);

G_DECLARE_FINAL_TYPE(XhaMessagesAudioRecorderHostApi, xha_messages_audio_recorder_host_api, XHA_MESSAGES, AUDIO_RECORDER_HOST_API, GObject)

G_DECLARE_FINAL_TYPE(XhaMessagesAudioRecorderHostApiResponseHandle, xha_messages_audio_recorder_host_api_response_handle, XHA_MESSAGES, AUDIO_RECORDER_HOST_API_RESPONSE_HANDLE, GObject)

G_DECLARE_FINAL_TYPE(XhaMessagesAudioRecorderHostApiCreateRecorderResponse, xha_messages_audio_recorder_host_api_create_recorder_response, XHA_MESSAGES, AUDIO_RECORDER_HOST_API_CREATE_RECORDER_RESPONSE, GObject)

/**
 * xha_messages_audio_recorder_host_api_create_recorder_response_new:
 *
 * Creates a new response to AudioRecorderHostApi.createRecorder.
 *
 * Returns: a new #XhaMessagesAudioRecorderHostApiCreateRecorderResponse
 */
XhaMessagesAudioRecorderHostApiCreateRecorderResponse* xha_messages_audio_recorder_host_api_create_recorder_response_new(int64_t return_value);

/**
 * xha_messages_audio_recorder_host_api_create_recorder_response_new_error:
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Creates a new error response to AudioRecorderHostApi.createRecorder.
 *
 * Returns: a new #XhaMessagesAudioRecorderHostApiCreateRecorderResponse
 */
XhaMessagesAudioRecorderHostApiCreateRecorderResponse* xha_messages_audio_recorder_host_api_create_recorder_response_new_error(const gchar* code, const gchar* message, FlValue* details);

G_DECLARE_FINAL_TYPE(XhaMessagesAudioRecorderHostApiPauseResponse, xha_messages_audio_recorder_host_api_pause_response, XHA_MESSAGES, AUDIO_RECORDER_HOST_API_PAUSE_RESPONSE, GObject)

/**
 * xha_messages_audio_recorder_host_api_pause_response_new:
 *
 * Creates a new response to AudioRecorderHostApi.pause.
 *
 * Returns: a new #XhaMessagesAudioRecorderHostApiPauseResponse
 */
XhaMessagesAudioRecorderHostApiPauseResponse* xha_messages_audio_recorder_host_api_pause_response_new();

/**
 * xha_messages_audio_recorder_host_api_pause_response_new_error:
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Creates a new error response to AudioRecorderHostApi.pause.
 *
 * Returns: a new #XhaMessagesAudioRecorderHostApiPauseResponse
 */
XhaMessagesAudioRecorderHostApiPauseResponse* xha_messages_audio_recorder_host_api_pause_response_new_error(const gchar* code, const gchar* message, FlValue* details);

G_DECLARE_FINAL_TYPE(XhaMessagesAudioRecorderHostApiResumeResponse, xha_messages_audio_recorder_host_api_resume_response, XHA_MESSAGES, AUDIO_RECORDER_HOST_API_RESUME_RESPONSE, GObject)

/**
 * xha_messages_audio_recorder_host_api_resume_response_new:
 *
 * Creates a new response to AudioRecorderHostApi.resume.
 *
 * Returns: a new #XhaMessagesAudioRecorderHostApiResumeResponse
 */
XhaMessagesAudioRecorderHostApiResumeResponse* xha_messages_audio_recorder_host_api_resume_response_new();

/**
 * xha_messages_audio_recorder_host_api_resume_response_new_error:
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Creates a new error response to AudioRecorderHostApi.resume.
 *
 * Returns: a new #XhaMessagesAudioRecorderHostApiResumeResponse
 */
XhaMessagesAudioRecorderHostApiResumeResponse* xha_messages_audio_recorder_host_api_resume_response_new_error(const gchar* code, const gchar* message, FlValue* details);

G_DECLARE_FINAL_TYPE(XhaMessagesAudioRecorderHostApiDisposeRecorderResponse, xha_messages_audio_recorder_host_api_dispose_recorder_response, XHA_MESSAGES, AUDIO_RECORDER_HOST_API_DISPOSE_RECORDER_RESPONSE, GObject)

/**
 * xha_messages_audio_recorder_host_api_dispose_recorder_response_new:
 *
 * Creates a new response to AudioRecorderHostApi.disposeRecorder.
 *
 * Returns: a new #XhaMessagesAudioRecorderHostApiDisposeRecorderResponse
 */
XhaMessagesAudioRecorderHostApiDisposeRecorderResponse* xha_messages_audio_recorder_host_api_dispose_recorder_response_new();

/**
 * xha_messages_audio_recorder_host_api_dispose_recorder_response_new_error:
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Creates a new error response to AudioRecorderHostApi.disposeRecorder.
 *
 * Returns: a new #XhaMessagesAudioRecorderHostApiDisposeRecorderResponse
 */
XhaMessagesAudioRecorderHostApiDisposeRecorderResponse* xha_messages_audio_recorder_host_api_dispose_recorder_response_new_error(const gchar* code, const gchar* message, FlValue* details);

/**
 * XhaMessagesAudioRecorderHostApiVTable:
 *
 * Table of functions exposed by AudioRecorderHostApi to be implemented by the API provider.
 */
typedef struct {
  XhaMessagesAudioRecorderHostApiCreateRecorderResponse* (*create_recorder)(gpointer user_data);
  void (*has_permission)(XhaMessagesAudioRecorderHostApiResponseHandle* response_handle, gpointer user_data);
  void (*list_input_devices)(XhaMessagesAudioRecorderHostApiResponseHandle* response_handle, gpointer user_data);
  void (*get_input_device)(int64_t recorder_id, XhaMessagesAudioRecorderHostApiResponseHandle* response_handle, gpointer user_data);
  void (*set_input_device)(int64_t recorder_id, const gchar* device_id, XhaMessagesAudioRecorderHostApiResponseHandle* response_handle, gpointer user_data);
  void (*start)(int64_t recorder_id, XhaMessagesRecordConfigMessage* config, const gchar* path, XhaMessagesAudioRecorderHostApiResponseHandle* response_handle, gpointer user_data);
  XhaMessagesAudioRecorderHostApiPauseResponse* (*pause)(int64_t recorder_id, gpointer user_data);
  XhaMessagesAudioRecorderHostApiResumeResponse* (*resume)(int64_t recorder_id, gpointer user_data);
  void (*stop)(int64_t recorder_id, XhaMessagesAudioRecorderHostApiResponseHandle* response_handle, gpointer user_data);
  void (*cancel)(int64_t recorder_id, XhaMessagesAudioRecorderHostApiResponseHandle* response_handle, gpointer user_data);
  XhaMessagesAudioRecorderHostApiDisposeRecorderResponse* (*dispose_recorder)(int64_t recorder_id, gpointer user_data);
} XhaMessagesAudioRecorderHostApiVTable;

/**
 * xha_messages_audio_recorder_host_api_set_method_handlers:
 *
 * @messenger: an #FlBinaryMessenger.
 * @suffix: (allow-none): a suffix to add to the API or %NULL for none.
 * @vtable: implementations of the methods in this API.
 * @user_data: (closure): user data to pass to the functions in @vtable.
 * @user_data_free_func: (allow-none): a function which gets called to free @user_data, or %NULL.
 *
 * Connects the method handlers in the AudioRecorderHostApi API.
 */
void xha_messages_audio_recorder_host_api_set_method_handlers(FlBinaryMessenger* messenger, const gchar* suffix, const XhaMessagesAudioRecorderHostApiVTable* vtable, gpointer user_data, GDestroyNotify user_data_free_func);

/**
 * xha_messages_audio_recorder_host_api_clear_method_handlers:
 *
 * @messenger: an #FlBinaryMessenger.
 * @suffix: (allow-none): a suffix to add to the API or %NULL for none.
 *
 * Clears the method handlers in the AudioRecorderHostApi API.
 */
void xha_messages_audio_recorder_host_api_clear_method_handlers(FlBinaryMessenger* messenger, const gchar* suffix);

/**
 * xha_messages_audio_recorder_host_api_respond_has_permission:
 * @response_handle: a #XhaMessagesAudioRecorderHostApiResponseHandle.
 * @return_value: location to write the value returned by this method.
 *
 * Responds to AudioRecorderHostApi.hasPermission. 
 */
void xha_messages_audio_recorder_host_api_respond_has_permission(XhaMessagesAudioRecorderHostApiResponseHandle* response_handle, gboolean return_value);

/**
 * xha_messages_audio_recorder_host_api_respond_error_has_permission:
 * @response_handle: a #XhaMessagesAudioRecorderHostApiResponseHandle.
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Responds with an error to AudioRecorderHostApi.hasPermission. 
 */
void xha_messages_audio_recorder_host_api_respond_error_has_permission(XhaMessagesAudioRecorderHostApiResponseHandle* response_handle, const gchar* code, const gchar* message, FlValue* details);

/**
 * xha_messages_audio_recorder_host_api_respond_list_input_devices:
 * @response_handle: a #XhaMessagesAudioRecorderHostApiResponseHandle.
 * @return_value: location to write the value returned by this method.
 *
 * Responds to AudioRecorderHostApi.listInputDevices. 
 */
void xha_messages_audio_recorder_host_api_respond_list_input_devices(XhaMessagesAudioRecorderHostApiResponseHandle* response_handle, FlValue* return_value);

/**
 * xha_messages_audio_recorder_host_api_respond_error_list_input_devices:
 * @response_handle: a #XhaMessagesAudioRecorderHostApiResponseHandle.
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Responds with an error to AudioRecorderHostApi.listInputDevices. 
 */
void xha_messages_audio_recorder_host_api_respond_error_list_input_devices(XhaMessagesAudioRecorderHostApiResponseHandle* response_handle, const gchar* code, const gchar* message, FlValue* details);

/**
 * xha_messages_audio_recorder_host_api_respond_get_input_device:
 * @response_handle: a #XhaMessagesAudioRecorderHostApiResponseHandle.
 * @return_value: location to write the value returned by this method.
 *
 * Responds to AudioRecorderHostApi.getInputDevice. 
 */
void xha_messages_audio_recorder_host_api_respond_get_input_device(XhaMessagesAudioRecorderHostApiResponseHandle* response_handle, XhaMessagesAudioDeviceMessage* return_value);

/**
 * xha_messages_audio_recorder_host_api_respond_error_get_input_device:
 * @response_handle: a #XhaMessagesAudioRecorderHostApiResponseHandle.
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Responds with an error to AudioRecorderHostApi.getInputDevice. 
 */
void xha_messages_audio_recorder_host_api_respond_error_get_input_device(XhaMessagesAudioRecorderHostApiResponseHandle* response_handle, const gchar* code, const gchar* message, FlValue* details);

/**
 * xha_messages_audio_recorder_host_api_respond_set_input_device:
 * @response_handle: a #XhaMessagesAudioRecorderHostApiResponseHandle.
 *
 * Responds to AudioRecorderHostApi.setInputDevice. 
 */
void xha_messages_audio_recorder_host_api_respond_set_input_device(XhaMessagesAudioRecorderHostApiResponseHandle* response_handle);

/**
 * xha_messages_audio_recorder_host_api_respond_error_set_input_device:
 * @response_handle: a #XhaMessagesAudioRecorderHostApiResponseHandle.
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Responds with an error to AudioRecorderHostApi.setInputDevice. 
 */
void xha_messages_audio_recorder_host_api_respond_error_set_input_device(XhaMessagesAudioRecorderHostApiResponseHandle* response_handle, const gchar* code, const gchar* message, FlValue* details);

/**
 * xha_messages_audio_recorder_host_api_respond_start:
 * @response_handle: a #XhaMessagesAudioRecorderHostApiResponseHandle.
 *
 * Responds to AudioRecorderHostApi.start. 
 */
void xha_messages_audio_recorder_host_api_respond_start(XhaMessagesAudioRecorderHostApiResponseHandle* response_handle);

/**
 * xha_messages_audio_recorder_host_api_respond_error_start:
 * @response_handle: a #XhaMessagesAudioRecorderHostApiResponseHandle.
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Responds with an error to AudioRecorderHostApi.start. 
 */
void xha_messages_audio_recorder_host_api_respond_error_start(XhaMessagesAudioRecorderHostApiResponseHandle* response_handle, const gchar* code, const gchar* message, FlValue* details);

/**
 * xha_messages_audio_recorder_host_api_respond_stop:
 * @response_handle: a #XhaMessagesAudioRecorderHostApiResponseHandle.
 * @return_value: location to write the value returned by this method.
 *
 * Responds to AudioRecorderHostApi.stop. 
 */
void xha_messages_audio_recorder_host_api_respond_stop(XhaMessagesAudioRecorderHostApiResponseHandle* response_handle, const gchar* return_value);

/**
 * xha_messages_audio_recorder_host_api_respond_error_stop:
 * @response_handle: a #XhaMessagesAudioRecorderHostApiResponseHandle.
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Responds with an error to AudioRecorderHostApi.stop. 
 */
void xha_messages_audio_recorder_host_api_respond_error_stop(XhaMessagesAudioRecorderHostApiResponseHandle* response_handle, const gchar* code, const gchar* message, FlValue* details);

/**
 * xha_messages_audio_recorder_host_api_respond_cancel:
 * @response_handle: a #XhaMessagesAudioRecorderHostApiResponseHandle.
 *
 * Responds to AudioRecorderHostApi.cancel. 
 */
void xha_messages_audio_recorder_host_api_respond_cancel(XhaMessagesAudioRecorderHostApiResponseHandle* response_handle);

/**
 * xha_messages_audio_recorder_host_api_respond_error_cancel:
 * @response_handle: a #XhaMessagesAudioRecorderHostApiResponseHandle.
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Responds with an error to AudioRecorderHostApi.cancel. 
 */
void xha_messages_audio_recorder_host_api_respond_error_cancel(XhaMessagesAudioRecorderHostApiResponseHandle* response_handle, const gchar* code, const gchar* message, FlValue* details);

G_END_DECLS

#endif  // PIGEON_MESSAGES_G_H_
