// Autogenerated from Pigeon (v27.3.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

enum MessagesPigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
  static func doubleEquals(_ lhs: Double, _ rhs: Double) -> Bool {
    return (lhs.isNaN && rhs.isNaN) || lhs == rhs
  }

  static func doubleHash(_ value: Double, _ hasher: inout Hasher) {
    if value.isNaN {
      hasher.combine(0x7FF8000000000000)
    } else {
      // Normalize -0.0 to 0.0
      hasher.combine(value == 0 ? 0 : value)
    }
  }

  static func deepEquals(_ lhs: Any?, _ rhs: Any?) -> Bool {
    let cleanLhs = nilOrValue(lhs) as Any?
    let cleanRhs = nilOrValue(rhs) as Any?
    switch (cleanLhs, cleanRhs) {
    case (nil, nil):
      return true

    case (nil, _), (_, nil):
      return false

    case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
      return true

    case is (Void, Void):
      return true

    case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !deepEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsArray, let rhsArray) as ([Double], [Double]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !doubleEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
      guard lhsDictionary.count == rhsDictionary.count else { return false }
      for (lhsKey, lhsValue) in lhsDictionary {
        var found = false
        for (rhsKey, rhsValue) in rhsDictionary {
          if deepEquals(lhsKey, rhsKey) {
            if deepEquals(lhsValue, rhsValue) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if !found { return false }
      }
      return true

    case (let lhs as Double, let rhs as Double):
      return doubleEquals(lhs, rhs)

    case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
      return lhsHashable == rhsHashable

    default:
      return false
    }
  }

  static func deepHash(value: Any?, hasher: inout Hasher) {
    let cleanValue = nilOrValue(value) as Any?
    if let cleanValue = cleanValue {
      if let doubleValue = cleanValue as? Double {
        doubleHash(doubleValue, &hasher)
      } else if let valueList = cleanValue as? [Any?] {
        for item in valueList {
          deepHash(value: item, hasher: &hasher)
        }
      } else if let valueList = cleanValue as? [Double] {
        for item in valueList {
          doubleHash(item, &hasher)
        }
      } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
        var result = 0
        for (key, value) in valueDict {
          var entryKeyHasher = Hasher()
          deepHash(value: key, hasher: &entryKeyHasher)
          var entryValueHasher = Hasher()
          deepHash(value: value, hasher: &entryValueHasher)
          result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
        }
        hasher.combine(result)
      } else if let hashableValue = cleanValue as? AnyHashable {
        hasher.combine(hashableValue)
      } else {
        hasher.combine(String(describing: cleanValue))
      }
    } else {
      hasher.combine(0)
    }
  }

}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


/// The kind of an audio source. / 音频源的种类。
enum SourceTypeMessage: Int, CaseIterable {
  /// A local file path. / 本地文件路径。
  case file = 0
  /// A remote HTTP(S) URL. / 远程 HTTP(S) 网络地址。
  case url = 1
  /// A Flutter asset key. / Flutter Asset 资源键。
  case asset = 2
}

/// The audio encoder used when recording. / 录音时使用的编码器。
enum EncoderMessage: Int, CaseIterable {
  /// Linear PCM in a WAV container. / WAV 容器中的线性 PCM。
  case wav = 0
  /// AAC-LC in an MPEG-4 container. / MPEG-4 容器中的 AAC-LC。
  case aacLc = 1
  /// Opus (Ogg or WebM container, platform dependent). / Opus 编码（Ogg 或 WebM 容器，视平台而定）。
  case opus = 2
}

/// Wire representation of an audio source. / 音频源的跨端传输结构。
///
/// Generated class from Pigeon that represents data sent in messages.
struct AudioSourceMessage: Hashable, CustomStringConvertible {
  /// The kind of source. / 源的种类。
  var type: SourceTypeMessage
  /// File path, URL, or fully-resolved asset key depending on [type].
  /// 依据 [type] 不同，可能是文件路径、URL 或已解析的 asset 键。
  var uri: String
  /// Optional HTTP headers, only meaningful for [SourceTypeMessage.url].
  /// 可选的 HTTP 请求头，仅对 [SourceTypeMessage.url] 有意义。
  var headers: [String: String]? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> AudioSourceMessage? {
    let type = pigeonVar_list[0] as! SourceTypeMessage
    let uri = pigeonVar_list[1] as! String
    let headers: [String: String]? = nilOrValue(pigeonVar_list[2])

    return AudioSourceMessage(
      type: type,
      uri: uri,
      headers: headers
    )
  }
  func toList() -> [Any?] {
    return [
      type,
      uri,
      headers,
    ]
  }
  static func == (lhs: AudioSourceMessage, rhs: AudioSourceMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.type, rhs.type) && MessagesPigeonInternal.deepEquals(lhs.uri, rhs.uri) && MessagesPigeonInternal.deepEquals(lhs.headers, rhs.headers)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("AudioSourceMessage")
    MessagesPigeonInternal.deepHash(value: type, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: uri, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: headers, hasher: &hasher)
  }

  public var description: String {
    return "AudioSourceMessage(type: \(String(describing: type)), uri: \(String(describing: uri)), headers: \(String(describing: headers)))"
  }
}

/// Wire representation of a recording configuration. / 录音配置的跨端传输结构。
///
/// Generated class from Pigeon that represents data sent in messages.
struct RecordConfigMessage: Hashable, CustomStringConvertible {
  /// Encoder to use. / 使用的编码器。
  var encoder: EncoderMessage
  /// Sample rate in Hz. / 采样率（Hz）。
  var sampleRate: Int64
  /// Number of channels (1 = mono, 2 = stereo). / 声道数（1 单声道，2 立体声）。
  var numChannels: Int64
  /// Bit rate in bits per second (compressed encoders only).
  /// 比特率（bit/s，仅压缩编码器使用）。
  var bitRate: Int64
  /// Interval between amplitude events in milliseconds.
  /// 振幅事件的推送间隔（毫秒）。
  var amplitudeIntervalMs: Int64
  /// Preferred input device id, `null` for the system default.
  /// 期望使用的输入设备 id，`null` 表示系统默认设备。
  var deviceId: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> RecordConfigMessage? {
    let encoder = pigeonVar_list[0] as! EncoderMessage
    let sampleRate = pigeonVar_list[1] as! Int64
    let numChannels = pigeonVar_list[2] as! Int64
    let bitRate = pigeonVar_list[3] as! Int64
    let amplitudeIntervalMs = pigeonVar_list[4] as! Int64
    let deviceId: String? = nilOrValue(pigeonVar_list[5])

    return RecordConfigMessage(
      encoder: encoder,
      sampleRate: sampleRate,
      numChannels: numChannels,
      bitRate: bitRate,
      amplitudeIntervalMs: amplitudeIntervalMs,
      deviceId: deviceId
    )
  }
  func toList() -> [Any?] {
    return [
      encoder,
      sampleRate,
      numChannels,
      bitRate,
      amplitudeIntervalMs,
      deviceId,
    ]
  }
  static func == (lhs: RecordConfigMessage, rhs: RecordConfigMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.encoder, rhs.encoder) && MessagesPigeonInternal.deepEquals(lhs.sampleRate, rhs.sampleRate) && MessagesPigeonInternal.deepEquals(lhs.numChannels, rhs.numChannels) && MessagesPigeonInternal.deepEquals(lhs.bitRate, rhs.bitRate) && MessagesPigeonInternal.deepEquals(lhs.amplitudeIntervalMs, rhs.amplitudeIntervalMs) && MessagesPigeonInternal.deepEquals(lhs.deviceId, rhs.deviceId)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("RecordConfigMessage")
    MessagesPigeonInternal.deepHash(value: encoder, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: sampleRate, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: numChannels, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: bitRate, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: amplitudeIntervalMs, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: deviceId, hasher: &hasher)
  }

  public var description: String {
    return "RecordConfigMessage(encoder: \(String(describing: encoder)), sampleRate: \(String(describing: sampleRate)), numChannels: \(String(describing: numChannels)), bitRate: \(String(describing: bitRate)), amplitudeIntervalMs: \(String(describing: amplitudeIntervalMs)), deviceId: \(String(describing: deviceId)))"
  }
}

/// Wire representation of an audio device (input or output).
/// 音频设备（输入或输出）的跨端传输结构。
///
/// Generated class from Pigeon that represents data sent in messages.
struct AudioDeviceMessage: Hashable, CustomStringConvertible {
  /// Platform-specific stable device identifier. / 平台相关的稳定设备标识。
  var id: String
  /// Human-readable device name. / 供人阅读的设备名称。
  var label: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> AudioDeviceMessage? {
    let id = pigeonVar_list[0] as! String
    let label = pigeonVar_list[1] as! String

    return AudioDeviceMessage(
      id: id,
      label: label
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      label,
    ]
  }
  static func == (lhs: AudioDeviceMessage, rhs: AudioDeviceMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.id, rhs.id) && MessagesPigeonInternal.deepEquals(lhs.label, rhs.label)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("AudioDeviceMessage")
    MessagesPigeonInternal.deepHash(value: id, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: label, hasher: &hasher)
  }

  public var description: String {
    return "AudioDeviceMessage(id: \(String(describing: id)), label: \(String(describing: label)))"
  }
}

private class MessagesPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return SourceTypeMessage(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return EncoderMessage(rawValue: enumResultAsInt)
      }
      return nil
    case 131:
      return AudioSourceMessage.fromList(self.readValue() as! [Any?])
    case 132:
      return RecordConfigMessage.fromList(self.readValue() as! [Any?])
    case 133:
      return AudioDeviceMessage.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class MessagesPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? SourceTypeMessage {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? EncoderMessage {
      super.writeByte(130)
      super.writeValue(value.rawValue)
    } else if let value = value as? AudioSourceMessage {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? RecordConfigMessage {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else if let value = value as? AudioDeviceMessage {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class MessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return MessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return MessagesPigeonCodecWriter(data: data)
  }
}

class MessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = MessagesPigeonCodec(readerWriter: MessagesPigeonCodecReaderWriter())
}


/// Host API implemented natively for audio playback control.
/// 由原生端实现的音频播放控制接口。
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol AudioPlayerHostApi {
  /// Creates a native player instance and returns its id.
  /// 创建一个原生播放器实例并返回其 id。
  func createPlayer() throws -> Int64
  /// Loads [source] into the player and returns the duration in
  /// milliseconds, or `null` when unknown (e.g. live streams).
  /// 加载音频源 [source]，返回音频时长（毫秒）；未知时（如直播流）返回 `null`。
  func setSource(playerId: Int64, source: AudioSourceMessage, completion: @escaping (Result<Int64?, Error>) -> Void)
  /// Starts or resumes playback. / 开始或恢复播放。
  func play(playerId: Int64) throws
  /// Pauses playback keeping the position. / 暂停播放并保留进度。
  func pause(playerId: Int64) throws
  /// Stops playback and rewinds to the beginning. / 停止播放并回到起点。
  func stop(playerId: Int64) throws
  /// Seeks to [positionMs] milliseconds. / 跳转到 [positionMs]（毫秒）。
  func seekTo(playerId: Int64, positionMs: Int64, completion: @escaping (Result<Void, Error>) -> Void)
  /// Sets the volume, 0.0 to 1.0. / 设置音量（0.0 ~ 1.0）。
  func setVolume(playerId: Int64, volume: Double) throws
  /// Sets the playback speed, e.g. 0.5 to 2.0. / 设置播放速度（如 0.5 ~ 2.0）。
  func setSpeed(playerId: Int64, speed: Double) throws
  /// Enables or disables looping. / 开启或关闭循环播放。
  func setLooping(playerId: Int64, looping: Bool) throws
  /// Returns the current position in milliseconds. / 返回当前播放位置（毫秒）。
  func getPosition(playerId: Int64) throws -> Int64
  /// Returns the duration in milliseconds or `null` when unknown.
  /// 返回音频时长（毫秒），未知时返回 `null`。
  func getDuration(playerId: Int64) throws -> Int64?
  /// Lists the available audio output devices. / 列出可用的音频输出设备。
  func listOutputDevices(completion: @escaping (Result<[AudioDeviceMessage], Error>) -> Void)
  /// Returns the output device used by the player, or `null` when following
  /// the system default. / 返回播放器当前使用的输出设备；跟随系统默认时返回 `null`。
  func getOutputDevice(playerId: Int64, completion: @escaping (Result<AudioDeviceMessage?, Error>) -> Void)
  /// Routes the player to the output device [deviceId], or back to the
  /// system default when `null`.
  /// 将播放器路由到输出设备 [deviceId]；传 `null` 恢复系统默认设备。
  func setOutputDevice(playerId: Int64, deviceId: String?, completion: @escaping (Result<Void, Error>) -> Void)
  /// Releases all native resources of the player. / 释放播放器的全部原生资源。
  func disposePlayer(playerId: Int64) throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class AudioPlayerHostApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `AudioPlayerHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: AudioPlayerHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Creates a native player instance and returns its id.
    /// 创建一个原生播放器实例并返回其 id。
    let createPlayerChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.xue_hua_audio_platform_interface.AudioPlayerHostApi.createPlayer\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      createPlayerChannel.setMessageHandler { _, reply in
        do {
          let result = try api.createPlayer()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      createPlayerChannel.setMessageHandler(nil)
    }
    /// Loads [source] into the player and returns the duration in
    /// milliseconds, or `null` when unknown (e.g. live streams).
    /// 加载音频源 [source]，返回音频时长（毫秒）；未知时（如直播流）返回 `null`。
    let setSourceChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.xue_hua_audio_platform_interface.AudioPlayerHostApi.setSource\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setSourceChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let playerIdArg = args[0] as! Int64
        let sourceArg = args[1] as! AudioSourceMessage
        api.setSource(playerId: playerIdArg, source: sourceArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      setSourceChannel.setMessageHandler(nil)
    }
    /// Starts or resumes playback. / 开始或恢复播放。
    let playChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.xue_hua_audio_platform_interface.AudioPlayerHostApi.play\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      playChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let playerIdArg = args[0] as! Int64
        do {
          try api.play(playerId: playerIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      playChannel.setMessageHandler(nil)
    }
    /// Pauses playback keeping the position. / 暂停播放并保留进度。
    let pauseChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.xue_hua_audio_platform_interface.AudioPlayerHostApi.pause\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      pauseChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let playerIdArg = args[0] as! Int64
        do {
          try api.pause(playerId: playerIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      pauseChannel.setMessageHandler(nil)
    }
    /// Stops playback and rewinds to the beginning. / 停止播放并回到起点。
    let stopChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.xue_hua_audio_platform_interface.AudioPlayerHostApi.stop\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      stopChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let playerIdArg = args[0] as! Int64
        do {
          try api.stop(playerId: playerIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      stopChannel.setMessageHandler(nil)
    }
    /// Seeks to [positionMs] milliseconds. / 跳转到 [positionMs]（毫秒）。
    let seekToChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.xue_hua_audio_platform_interface.AudioPlayerHostApi.seekTo\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      seekToChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let playerIdArg = args[0] as! Int64
        let positionMsArg = args[1] as! Int64
        api.seekTo(playerId: playerIdArg, positionMs: positionMsArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      seekToChannel.setMessageHandler(nil)
    }
    /// Sets the volume, 0.0 to 1.0. / 设置音量（0.0 ~ 1.0）。
    let setVolumeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.xue_hua_audio_platform_interface.AudioPlayerHostApi.setVolume\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setVolumeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let playerIdArg = args[0] as! Int64
        let volumeArg = args[1] as! Double
        do {
          try api.setVolume(playerId: playerIdArg, volume: volumeArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setVolumeChannel.setMessageHandler(nil)
    }
    /// Sets the playback speed, e.g. 0.5 to 2.0. / 设置播放速度（如 0.5 ~ 2.0）。
    let setSpeedChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.xue_hua_audio_platform_interface.AudioPlayerHostApi.setSpeed\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setSpeedChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let playerIdArg = args[0] as! Int64
        let speedArg = args[1] as! Double
        do {
          try api.setSpeed(playerId: playerIdArg, speed: speedArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setSpeedChannel.setMessageHandler(nil)
    }
    /// Enables or disables looping. / 开启或关闭循环播放。
    let setLoopingChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.xue_hua_audio_platform_interface.AudioPlayerHostApi.setLooping\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setLoopingChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let playerIdArg = args[0] as! Int64
        let loopingArg = args[1] as! Bool
        do {
          try api.setLooping(playerId: playerIdArg, looping: loopingArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setLoopingChannel.setMessageHandler(nil)
    }
    /// Returns the current position in milliseconds. / 返回当前播放位置（毫秒）。
    let getPositionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.xue_hua_audio_platform_interface.AudioPlayerHostApi.getPosition\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getPositionChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let playerIdArg = args[0] as! Int64
        do {
          let result = try api.getPosition(playerId: playerIdArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getPositionChannel.setMessageHandler(nil)
    }
    /// Returns the duration in milliseconds or `null` when unknown.
    /// 返回音频时长（毫秒），未知时返回 `null`。
    let getDurationChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.xue_hua_audio_platform_interface.AudioPlayerHostApi.getDuration\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getDurationChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let playerIdArg = args[0] as! Int64
        do {
          let result = try api.getDuration(playerId: playerIdArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getDurationChannel.setMessageHandler(nil)
    }
    /// Lists the available audio output devices. / 列出可用的音频输出设备。
    let listOutputDevicesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.xue_hua_audio_platform_interface.AudioPlayerHostApi.listOutputDevices\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      listOutputDevicesChannel.setMessageHandler { _, reply in
        api.listOutputDevices { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      listOutputDevicesChannel.setMessageHandler(nil)
    }
    /// Returns the output device used by the player, or `null` when following
    /// the system default. / 返回播放器当前使用的输出设备；跟随系统默认时返回 `null`。
    let getOutputDeviceChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.xue_hua_audio_platform_interface.AudioPlayerHostApi.getOutputDevice\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getOutputDeviceChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let playerIdArg = args[0] as! Int64
        api.getOutputDevice(playerId: playerIdArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getOutputDeviceChannel.setMessageHandler(nil)
    }
    /// Routes the player to the output device [deviceId], or back to the
    /// system default when `null`.
    /// 将播放器路由到输出设备 [deviceId]；传 `null` 恢复系统默认设备。
    let setOutputDeviceChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.xue_hua_audio_platform_interface.AudioPlayerHostApi.setOutputDevice\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setOutputDeviceChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let playerIdArg = args[0] as! Int64
        let deviceIdArg: String? = nilOrValue(args[1])
        api.setOutputDevice(playerId: playerIdArg, deviceId: deviceIdArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      setOutputDeviceChannel.setMessageHandler(nil)
    }
    /// Releases all native resources of the player. / 释放播放器的全部原生资源。
    let disposePlayerChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.xue_hua_audio_platform_interface.AudioPlayerHostApi.disposePlayer\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      disposePlayerChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let playerIdArg = args[0] as! Int64
        do {
          try api.disposePlayer(playerId: playerIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      disposePlayerChannel.setMessageHandler(nil)
    }
  }
}
/// Host API implemented natively for microphone recording control.
/// 由原生端实现的麦克风录音控制接口。
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol AudioRecorderHostApi {
  /// Creates a native recorder instance and returns its id.
  /// 创建一个原生录音机实例并返回其 id。
  func createRecorder() throws -> Int64
  /// Checks (and requests when possible) microphone permission.
  /// Returns `true` when recording is permitted.
  /// 检查（并在可能时请求）麦克风权限；允许录音时返回 `true`。
  func hasPermission(completion: @escaping (Result<Bool, Error>) -> Void)
  /// Lists the available audio input devices. / 列出可用的音频输入设备。
  func listInputDevices(completion: @escaping (Result<[AudioDeviceMessage], Error>) -> Void)
  /// Returns the input device used by the recorder, or `null` when following
  /// the system default. / 返回录音机当前使用的输入设备；跟随系统默认时返回 `null`。
  func getInputDevice(recorderId: Int64, completion: @escaping (Result<AudioDeviceMessage?, Error>) -> Void)
  /// Selects the input device [deviceId] for the recorder, or the system
  /// default when `null`. Live switching support is platform dependent.
  /// 为录音机选择输入设备 [deviceId]；传 `null` 使用系统默认设备。
  /// 录音过程中切换的支持情况视平台而定。
  func setInputDevice(recorderId: Int64, deviceId: String?, completion: @escaping (Result<Void, Error>) -> Void)
  /// Starts recording to [path] using [config]. Completes once recording
  /// has actually started.
  /// 使用 [config] 开始录音并写入 [path]；录音真正启动后才完成。
  func start(recorderId: Int64, config: RecordConfigMessage, path: String, completion: @escaping (Result<Void, Error>) -> Void)
  /// Pauses recording. / 暂停录音。
  func pause(recorderId: Int64) throws
  /// Resumes a paused recording. / 恢复已暂停的录音。
  func resume(recorderId: Int64) throws
  /// Stops recording and returns the recorded file path, or `null` when
  /// nothing was recorded.
  /// 停止录音并返回录音文件路径；未产生录音时返回 `null`。
  func stop(recorderId: Int64, completion: @escaping (Result<String?, Error>) -> Void)
  /// Stops recording and deletes the partial file. / 停止录音并删除未完成的文件。
  func cancel(recorderId: Int64, completion: @escaping (Result<Void, Error>) -> Void)
  /// Releases all native resources of the recorder. / 释放录音机的全部原生资源。
  func disposeRecorder(recorderId: Int64) throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class AudioRecorderHostApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `AudioRecorderHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: AudioRecorderHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Creates a native recorder instance and returns its id.
    /// 创建一个原生录音机实例并返回其 id。
    let createRecorderChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.xue_hua_audio_platform_interface.AudioRecorderHostApi.createRecorder\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      createRecorderChannel.setMessageHandler { _, reply in
        do {
          let result = try api.createRecorder()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      createRecorderChannel.setMessageHandler(nil)
    }
    /// Checks (and requests when possible) microphone permission.
    /// Returns `true` when recording is permitted.
    /// 检查（并在可能时请求）麦克风权限；允许录音时返回 `true`。
    let hasPermissionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.xue_hua_audio_platform_interface.AudioRecorderHostApi.hasPermission\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      hasPermissionChannel.setMessageHandler { _, reply in
        api.hasPermission { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      hasPermissionChannel.setMessageHandler(nil)
    }
    /// Lists the available audio input devices. / 列出可用的音频输入设备。
    let listInputDevicesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.xue_hua_audio_platform_interface.AudioRecorderHostApi.listInputDevices\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      listInputDevicesChannel.setMessageHandler { _, reply in
        api.listInputDevices { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      listInputDevicesChannel.setMessageHandler(nil)
    }
    /// Returns the input device used by the recorder, or `null` when following
    /// the system default. / 返回录音机当前使用的输入设备；跟随系统默认时返回 `null`。
    let getInputDeviceChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.xue_hua_audio_platform_interface.AudioRecorderHostApi.getInputDevice\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getInputDeviceChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let recorderIdArg = args[0] as! Int64
        api.getInputDevice(recorderId: recorderIdArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getInputDeviceChannel.setMessageHandler(nil)
    }
    /// Selects the input device [deviceId] for the recorder, or the system
    /// default when `null`. Live switching support is platform dependent.
    /// 为录音机选择输入设备 [deviceId]；传 `null` 使用系统默认设备。
    /// 录音过程中切换的支持情况视平台而定。
    let setInputDeviceChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.xue_hua_audio_platform_interface.AudioRecorderHostApi.setInputDevice\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setInputDeviceChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let recorderIdArg = args[0] as! Int64
        let deviceIdArg: String? = nilOrValue(args[1])
        api.setInputDevice(recorderId: recorderIdArg, deviceId: deviceIdArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      setInputDeviceChannel.setMessageHandler(nil)
    }
    /// Starts recording to [path] using [config]. Completes once recording
    /// has actually started.
    /// 使用 [config] 开始录音并写入 [path]；录音真正启动后才完成。
    let startChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.xue_hua_audio_platform_interface.AudioRecorderHostApi.start\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let recorderIdArg = args[0] as! Int64
        let configArg = args[1] as! RecordConfigMessage
        let pathArg = args[2] as! String
        api.start(recorderId: recorderIdArg, config: configArg, path: pathArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      startChannel.setMessageHandler(nil)
    }
    /// Pauses recording. / 暂停录音。
    let pauseChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.xue_hua_audio_platform_interface.AudioRecorderHostApi.pause\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      pauseChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let recorderIdArg = args[0] as! Int64
        do {
          try api.pause(recorderId: recorderIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      pauseChannel.setMessageHandler(nil)
    }
    /// Resumes a paused recording. / 恢复已暂停的录音。
    let resumeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.xue_hua_audio_platform_interface.AudioRecorderHostApi.resume\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      resumeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let recorderIdArg = args[0] as! Int64
        do {
          try api.resume(recorderId: recorderIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      resumeChannel.setMessageHandler(nil)
    }
    /// Stops recording and returns the recorded file path, or `null` when
    /// nothing was recorded.
    /// 停止录音并返回录音文件路径；未产生录音时返回 `null`。
    let stopChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.xue_hua_audio_platform_interface.AudioRecorderHostApi.stop\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      stopChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let recorderIdArg = args[0] as! Int64
        api.stop(recorderId: recorderIdArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      stopChannel.setMessageHandler(nil)
    }
    /// Stops recording and deletes the partial file. / 停止录音并删除未完成的文件。
    let cancelChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.xue_hua_audio_platform_interface.AudioRecorderHostApi.cancel\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      cancelChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let recorderIdArg = args[0] as! Int64
        api.cancel(recorderId: recorderIdArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      cancelChannel.setMessageHandler(nil)
    }
    /// Releases all native resources of the recorder. / 释放录音机的全部原生资源。
    let disposeRecorderChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.xue_hua_audio_platform_interface.AudioRecorderHostApi.disposeRecorder\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      disposeRecorderChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let recorderIdArg = args[0] as! Int64
        do {
          try api.disposeRecorder(recorderId: recorderIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      disposeRecorderChannel.setMessageHandler(nil)
    }
  }
}
