// Autogenerated from Pigeon (v27.3.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#ifndef PIGEON_MESSAGES_G_H_
#define PIGEON_MESSAGES_G_H_
#include <flutter/basic_message_channel.h>
#include <flutter/binary_messenger.h>
#include <flutter/encodable_value.h>
#include <flutter/standard_message_codec.h>

#include <map>
#include <optional>
#include <ostream>
#include <string>

namespace xue_hua_audio_windows {


// Generated class from Pigeon.

class FlutterError {
 public:
  explicit FlutterError(const std::string& code)
    : code_(code) {}
  explicit FlutterError(const std::string& code, const std::string& message)
    : code_(code), message_(message) {}
  explicit FlutterError(const std::string& code, const std::string& message, const ::flutter::EncodableValue& details)
    : code_(code), message_(message), details_(details) {}

  const std::string& code() const { return code_; }
  const std::string& message() const { return message_; }
  const ::flutter::EncodableValue& details() const { return details_; }

 private:
  std::string code_;
  std::string message_;
  ::flutter::EncodableValue details_;
};

template<class T> class ErrorOr {
 public:
  ErrorOr(const T& rhs) : v_(rhs) {}
  ErrorOr(const T&& rhs) : v_(std::move(rhs)) {}
  ErrorOr(const FlutterError& rhs) : v_(rhs) {}
  ErrorOr(const FlutterError&& rhs) : v_(std::move(rhs)) {}

  bool has_error() const { return std::holds_alternative<FlutterError>(v_); }
  const T& value() const { return std::get<T>(v_); };
  const FlutterError& error() const { return std::get<FlutterError>(v_); };

 private:
  friend class AudioPlayerHostApi;
  friend class AudioRecorderHostApi;
  ErrorOr() = default;
  T TakeValue() && { return std::get<T>(std::move(v_)); }

  std::variant<T, FlutterError> v_;
};


// The kind of an audio source. / 音频源的种类。
enum class SourceTypeMessage {
  // A local file path. / 本地文件路径。
  kFile = 0,
  // A remote HTTP(S) URL. / 远程 HTTP(S) 网络地址。
  kUrl = 1,
  // A Flutter asset key. / Flutter Asset 资源键。
  kAsset = 2
};

// The audio encoder used when recording. / 录音时使用的编码器。
enum class EncoderMessage {
  // Linear PCM in a WAV container. / WAV 容器中的线性 PCM。
  kWav = 0,
  // AAC-LC in an MPEG-4 container. / MPEG-4 容器中的 AAC-LC。
  kAacLc = 1,
  // Opus (Ogg or WebM container, platform dependent). / Opus 编码（Ogg 或 WebM 容器，视平台而定）。
  kOpus = 2
};


// Wire representation of an audio source. / 音频源的跨端传输结构。
//
// Generated class from Pigeon that represents data sent in messages.
class AudioSourceMessage {
 public:
  // Constructs an object setting all non-nullable fields.
  explicit AudioSourceMessage(
    const SourceTypeMessage& type,
    const std::string& uri);

  // Constructs an object setting all fields.
  explicit AudioSourceMessage(
    const SourceTypeMessage& type,
    const std::string& uri,
    const ::flutter::EncodableMap* headers);

  // The kind of source. / 源的种类。
  const SourceTypeMessage& type() const;
  void set_type(const SourceTypeMessage& value_arg);

  // File path, URL, or fully-resolved asset key depending on [type].
  // 依据 [type] 不同，可能是文件路径、URL 或已解析的 asset 键。
  const std::string& uri() const;
  void set_uri(std::string_view value_arg);

  // Optional HTTP headers, only meaningful for [SourceTypeMessage.url].
  // 可选的 HTTP 请求头，仅对 [SourceTypeMessage.url] 有意义。
  const ::flutter::EncodableMap* headers() const;
  void set_headers(const ::flutter::EncodableMap* value_arg);
  void set_headers(const ::flutter::EncodableMap& value_arg);

  bool operator==(const AudioSourceMessage& other) const;
  bool operator!=(const AudioSourceMessage& other) const;
  /// Returns a hash code value for the object. This method is supported for the benefit of hash tables.
  size_t Hash() const;
  /// Stream output operator for formatted string representation.
  friend std::ostream& operator<<(std::ostream& os, const AudioSourceMessage& obj);
 private:
  static AudioSourceMessage FromEncodableList(const ::flutter::EncodableList& list);
  ::flutter::EncodableList ToEncodableList() const;
  friend class AudioPlayerHostApi;
  friend class AudioRecorderHostApi;
  friend class PigeonInternalCodecSerializer;
  SourceTypeMessage type_;
  std::string uri_;
  std::optional<::flutter::EncodableMap> headers_;
};


// Wire representation of a recording configuration. / 录音配置的跨端传输结构。
//
// Generated class from Pigeon that represents data sent in messages.
class RecordConfigMessage {
 public:
  // Constructs an object setting all non-nullable fields.
  explicit RecordConfigMessage(
    const EncoderMessage& encoder,
    int64_t sample_rate,
    int64_t num_channels,
    int64_t bit_rate,
    int64_t amplitude_interval_ms);

  // Constructs an object setting all fields.
  explicit RecordConfigMessage(
    const EncoderMessage& encoder,
    int64_t sample_rate,
    int64_t num_channels,
    int64_t bit_rate,
    int64_t amplitude_interval_ms,
    const std::string* device_id);

  // Encoder to use. / 使用的编码器。
  const EncoderMessage& encoder() const;
  void set_encoder(const EncoderMessage& value_arg);

  // Sample rate in Hz. / 采样率（Hz）。
  int64_t sample_rate() const;
  void set_sample_rate(int64_t value_arg);

  // Number of channels (1 = mono, 2 = stereo). / 声道数（1 单声道，2 立体声）。
  int64_t num_channels() const;
  void set_num_channels(int64_t value_arg);

  // Bit rate in bits per second (compressed encoders only).
  // 比特率（bit/s，仅压缩编码器使用）。
  int64_t bit_rate() const;
  void set_bit_rate(int64_t value_arg);

  // Interval between amplitude events in milliseconds.
  // 振幅事件的推送间隔（毫秒）。
  int64_t amplitude_interval_ms() const;
  void set_amplitude_interval_ms(int64_t value_arg);

  // Preferred input device id, `null` for the system default.
  // 期望使用的输入设备 id，`null` 表示系统默认设备。
  const std::string* device_id() const;
  void set_device_id(const std::string_view* value_arg);
  void set_device_id(std::string_view value_arg);

  bool operator==(const RecordConfigMessage& other) const;
  bool operator!=(const RecordConfigMessage& other) const;
  /// Returns a hash code value for the object. This method is supported for the benefit of hash tables.
  size_t Hash() const;
  /// Stream output operator for formatted string representation.
  friend std::ostream& operator<<(std::ostream& os, const RecordConfigMessage& obj);
 private:
  static RecordConfigMessage FromEncodableList(const ::flutter::EncodableList& list);
  ::flutter::EncodableList ToEncodableList() const;
  friend class AudioPlayerHostApi;
  friend class AudioRecorderHostApi;
  friend class PigeonInternalCodecSerializer;
  EncoderMessage encoder_;
  int64_t sample_rate_;
  int64_t num_channels_;
  int64_t bit_rate_;
  int64_t amplitude_interval_ms_;
  std::optional<std::string> device_id_;
};


// Wire representation of an audio device (input or output).
// 音频设备（输入或输出）的跨端传输结构。
//
// Generated class from Pigeon that represents data sent in messages.
class AudioDeviceMessage {
 public:
  // Constructs an object setting all fields.
  explicit AudioDeviceMessage(
    const std::string& id,
    const std::string& label);

  // Platform-specific stable device identifier. / 平台相关的稳定设备标识。
  const std::string& id() const;
  void set_id(std::string_view value_arg);

  // Human-readable device name. / 供人阅读的设备名称。
  const std::string& label() const;
  void set_label(std::string_view value_arg);

  bool operator==(const AudioDeviceMessage& other) const;
  bool operator!=(const AudioDeviceMessage& other) const;
  /// Returns a hash code value for the object. This method is supported for the benefit of hash tables.
  size_t Hash() const;
  /// Stream output operator for formatted string representation.
  friend std::ostream& operator<<(std::ostream& os, const AudioDeviceMessage& obj);
 private:
  static AudioDeviceMessage FromEncodableList(const ::flutter::EncodableList& list);
  ::flutter::EncodableList ToEncodableList() const;
  friend class AudioPlayerHostApi;
  friend class AudioRecorderHostApi;
  friend class PigeonInternalCodecSerializer;
  std::string id_;
  std::string label_;
};


class PigeonInternalCodecSerializer : public ::flutter::StandardCodecSerializer {
 public:
  PigeonInternalCodecSerializer();
  inline static PigeonInternalCodecSerializer& GetInstance() {
    static PigeonInternalCodecSerializer sInstance;
    return sInstance;
  }

  void WriteValue(
    const ::flutter::EncodableValue& value,
    ::flutter::ByteStreamWriter* stream) const override;
 protected:
  ::flutter::EncodableValue ReadValueOfType(
    uint8_t type,
    ::flutter::ByteStreamReader* stream) const override;
};

// Host API implemented natively for audio playback control.
// 由原生端实现的音频播放控制接口。
//
// Generated interface from Pigeon that represents a handler of messages from Flutter.
class AudioPlayerHostApi {
 public:
  AudioPlayerHostApi(const AudioPlayerHostApi&) = delete;
  AudioPlayerHostApi& operator=(const AudioPlayerHostApi&) = delete;
  virtual ~AudioPlayerHostApi() {}
  // Creates a native player instance and returns its id.
  // 创建一个原生播放器实例并返回其 id。
  virtual ErrorOr<int64_t> CreatePlayer() = 0;
  // Loads [source] into the player and returns the duration in
  // milliseconds, or `null` when unknown (e.g. live streams).
  // 加载音频源 [source]，返回音频时长（毫秒）；未知时（如直播流）返回 `null`。
  virtual void SetSource(
    int64_t player_id,
    const AudioSourceMessage& source,
    std::function<void(ErrorOr<std::optional<int64_t>> reply)> result) = 0;
  // Starts or resumes playback. / 开始或恢复播放。
  virtual std::optional<FlutterError> Play(int64_t player_id) = 0;
  // Pauses playback keeping the position. / 暂停播放并保留进度。
  virtual std::optional<FlutterError> Pause(int64_t player_id) = 0;
  // Stops playback and rewinds to the beginning. / 停止播放并回到起点。
  virtual std::optional<FlutterError> Stop(int64_t player_id) = 0;
  // Seeks to [positionMs] milliseconds. / 跳转到 [positionMs]（毫秒）。
  virtual void SeekTo(
    int64_t player_id,
    int64_t position_ms,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;
  // Sets the volume, 0.0 to 1.0. / 设置音量（0.0 ~ 1.0）。
  virtual std::optional<FlutterError> SetVolume(
    int64_t player_id,
    double volume) = 0;
  // Sets the playback speed, e.g. 0.5 to 2.0. / 设置播放速度（如 0.5 ~ 2.0）。
  virtual std::optional<FlutterError> SetSpeed(
    int64_t player_id,
    double speed) = 0;
  // Enables or disables looping. / 开启或关闭循环播放。
  virtual std::optional<FlutterError> SetLooping(
    int64_t player_id,
    bool looping) = 0;
  // Returns the current position in milliseconds. / 返回当前播放位置（毫秒）。
  virtual ErrorOr<int64_t> GetPosition(int64_t player_id) = 0;
  // Returns the duration in milliseconds or `null` when unknown.
  // 返回音频时长（毫秒），未知时返回 `null`。
  virtual ErrorOr<std::optional<int64_t>> GetDuration(int64_t player_id) = 0;
  // Lists the available audio output devices. / 列出可用的音频输出设备。
  virtual void ListOutputDevices(std::function<void(ErrorOr<::flutter::EncodableList> reply)> result) = 0;
  // Returns the output device used by the player, or `null` when following
  // the system default. / 返回播放器当前使用的输出设备；跟随系统默认时返回 `null`。
  virtual void GetOutputDevice(
    int64_t player_id,
    std::function<void(ErrorOr<std::optional<AudioDeviceMessage>> reply)> result) = 0;
  // Routes the player to the output device [deviceId], or back to the
  // system default when `null`.
  // 将播放器路由到输出设备 [deviceId]；传 `null` 恢复系统默认设备。
  virtual void SetOutputDevice(
    int64_t player_id,
    const std::string* device_id,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;
  // Releases all native resources of the player. / 释放播放器的全部原生资源。
  virtual std::optional<FlutterError> DisposePlayer(int64_t player_id) = 0;

  // The codec used by AudioPlayerHostApi.
  static const ::flutter::StandardMessageCodec& GetCodec();
  // Sets up an instance of `AudioPlayerHostApi` to handle messages through the `binary_messenger`.
  static void SetUp(
    ::flutter::BinaryMessenger* binary_messenger,
    AudioPlayerHostApi* api);
  static void SetUp(
    ::flutter::BinaryMessenger* binary_messenger,
    AudioPlayerHostApi* api,
    const std::string& message_channel_suffix);
  static ::flutter::EncodableValue WrapError(std::string_view error_message);
  static ::flutter::EncodableValue WrapError(const FlutterError& error);
 protected:
  AudioPlayerHostApi() = default;
};
// Host API implemented natively for microphone recording control.
// 由原生端实现的麦克风录音控制接口。
//
// Generated interface from Pigeon that represents a handler of messages from Flutter.
class AudioRecorderHostApi {
 public:
  AudioRecorderHostApi(const AudioRecorderHostApi&) = delete;
  AudioRecorderHostApi& operator=(const AudioRecorderHostApi&) = delete;
  virtual ~AudioRecorderHostApi() {}
  // Creates a native recorder instance and returns its id.
  // 创建一个原生录音机实例并返回其 id。
  virtual ErrorOr<int64_t> CreateRecorder() = 0;
  // Checks (and requests when possible) microphone permission.
  // Returns `true` when recording is permitted.
  // 检查（并在可能时请求）麦克风权限；允许录音时返回 `true`。
  virtual void HasPermission(std::function<void(ErrorOr<bool> reply)> result) = 0;
  // Lists the available audio input devices. / 列出可用的音频输入设备。
  virtual void ListInputDevices(std::function<void(ErrorOr<::flutter::EncodableList> reply)> result) = 0;
  // Returns the input device used by the recorder, or `null` when following
  // the system default. / 返回录音机当前使用的输入设备；跟随系统默认时返回 `null`。
  virtual void GetInputDevice(
    int64_t recorder_id,
    std::function<void(ErrorOr<std::optional<AudioDeviceMessage>> reply)> result) = 0;
  // Selects the input device [deviceId] for the recorder, or the system
  // default when `null`. Live switching support is platform dependent.
  // 为录音机选择输入设备 [deviceId]；传 `null` 使用系统默认设备。
  // 录音过程中切换的支持情况视平台而定。
  virtual void SetInputDevice(
    int64_t recorder_id,
    const std::string* device_id,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;
  // Starts recording to [path] using [config]. Completes once recording
  // has actually started.
  // 使用 [config] 开始录音并写入 [path]；录音真正启动后才完成。
  virtual void Start(
    int64_t recorder_id,
    const RecordConfigMessage& config,
    const std::string& path,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;
  // Pauses recording. / 暂停录音。
  virtual std::optional<FlutterError> Pause(int64_t recorder_id) = 0;
  // Resumes a paused recording. / 恢复已暂停的录音。
  virtual std::optional<FlutterError> Resume(int64_t recorder_id) = 0;
  // Stops recording and returns the recorded file path, or `null` when
  // nothing was recorded.
  // 停止录音并返回录音文件路径；未产生录音时返回 `null`。
  virtual void Stop(
    int64_t recorder_id,
    std::function<void(ErrorOr<std::optional<std::string>> reply)> result) = 0;
  // Stops recording and deletes the partial file. / 停止录音并删除未完成的文件。
  virtual void Cancel(
    int64_t recorder_id,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;
  // Releases all native resources of the recorder. / 释放录音机的全部原生资源。
  virtual std::optional<FlutterError> DisposeRecorder(int64_t recorder_id) = 0;

  // The codec used by AudioRecorderHostApi.
  static const ::flutter::StandardMessageCodec& GetCodec();
  // Sets up an instance of `AudioRecorderHostApi` to handle messages through the `binary_messenger`.
  static void SetUp(
    ::flutter::BinaryMessenger* binary_messenger,
    AudioRecorderHostApi* api);
  static void SetUp(
    ::flutter::BinaryMessenger* binary_messenger,
    AudioRecorderHostApi* api,
    const std::string& message_channel_suffix);
  static ::flutter::EncodableValue WrapError(std::string_view error_message);
  static ::flutter::EncodableValue WrapError(const FlutterError& error);
 protected:
  AudioRecorderHostApi() = default;
};
}  // namespace xue_hua_audio_windows
#endif  // PIGEON_MESSAGES_G_H_
