// Autogenerated from Pigeon (v27.3.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#undef _HAS_EXCEPTIONS

#include "messages.g.h"

#include <flutter/basic_message_channel.h>
#include <flutter/binary_messenger.h>
#include <flutter/encodable_value.h>
#include <flutter/standard_message_codec.h>

#include <cmath>
#include <limits>
#include <map>
#include <optional>
#include <sstream>
#include <string>

namespace xue_hua_audio_windows {
using ::flutter::BasicMessageChannel;
using ::flutter::CustomEncodableValue;
using ::flutter::EncodableList;
using ::flutter::EncodableMap;
using ::flutter::EncodableValue;

FlutterError CreateConnectionError(const std::string channel_name) {
  return FlutterError(
      "channel-error",
      "Unable to establish connection on channel: '" + channel_name + "'.",
      EncodableValue(""));
}

namespace {
template<typename T>
bool PigeonInternalDeepEquals(const T& a, const T& b);

bool PigeonInternalDeepEquals(const double& a, const double& b);

template<typename T>
bool PigeonInternalDeepEquals(const std::vector<T>& a, const std::vector<T>& b);

template<typename K, typename V>
bool PigeonInternalDeepEquals(const std::map<K, V>& a, const std::map<K, V>& b);

template<typename T>
bool PigeonInternalDeepEquals(const std::optional<T>& a, const std::optional<T>& b);

template<typename T>
bool PigeonInternalDeepEquals(const std::unique_ptr<T>& a, const std::unique_ptr<T>& b);

bool PigeonInternalDeepEquals(const ::flutter::EncodableValue& a, const ::flutter::EncodableValue& b);

template<typename T>
bool PigeonInternalDeepEquals(const T& a, const T& b) {
  return a == b;
}

template<typename T>
bool PigeonInternalDeepEquals(const std::vector<T>& a, const std::vector<T>& b) {
  if (a.size() != b.size()) {
    return false;
  }
  for (size_t i = 0; i < a.size(); ++i) {
    if (!PigeonInternalDeepEquals(a[i], b[i])) {
      return false;
    }
  }
  return true;
}

template <typename K, typename V>
bool PigeonInternalDeepEquals(const std::map<K, V>& a, const std::map<K, V>& b) {
  if (a.size() != b.size()) {
    return false;
  }
  for (const auto& kv : a) {
    bool found = false;
    for (const auto& b_kv : b) {
      if (PigeonInternalDeepEquals(kv.first, b_kv.first)) {
        if (PigeonInternalDeepEquals(kv.second, b_kv.second)) {
          found = true;
          break;
        } else {
          return false;
        }
      }
    }
    if (!found) {
      return false;
    }
  }
  return true;
}

bool PigeonInternalDeepEquals(const double& a, const double& b) {
  // Normalize -0.0 to 0.0 and handle NaN equality.
  return (a == b) || (std::isnan(a) && std::isnan(b));
}

template<typename T>
bool PigeonInternalDeepEquals(const std::optional<T>& a, const std::optional<T>& b) {
  if (!a && !b) {
    return true;
  }
  if (!a || !b) {
    return false;
  }
  return PigeonInternalDeepEquals(*a, *b);
}

template<typename T>
bool PigeonInternalDeepEquals(const std::unique_ptr<T>& a, const std::unique_ptr<T>& b) {
  if (a.get() == b.get()) {
    return true;
  }
  if (!a || !b) {
    return false;
  }
  return PigeonInternalDeepEquals(*a, *b);
}

bool PigeonInternalDeepEquals(const ::flutter::EncodableValue& a, const ::flutter::EncodableValue& b) {
  if (a.index() != b.index()) {
    return false;
  }
  if (const double* da = std::get_if<double>(&a)) {
    return PigeonInternalDeepEquals(*da, std::get<double>(b));
  } else if (const ::flutter::EncodableList* la = std::get_if<::flutter::EncodableList>(&a)) {
    return PigeonInternalDeepEquals(*la, std::get<::flutter::EncodableList>(b));
  } else if (const ::flutter::EncodableMap* ma = std::get_if<::flutter::EncodableMap>(&a)) {
    return PigeonInternalDeepEquals(*ma, std::get<::flutter::EncodableMap>(b));
  }
  return a == b;
}

template <typename T>
size_t PigeonInternalDeepHash(const T& v);

size_t PigeonInternalDeepHash(const double& v);

template <typename T>
size_t PigeonInternalDeepHash(const std::vector<T>& v);

template <typename K, typename V>
size_t PigeonInternalDeepHash(const std::map<K, V>& v);

template <typename T>
size_t PigeonInternalDeepHash(const std::optional<T>& v);

template <typename T>
size_t PigeonInternalDeepHash(const std::unique_ptr<T>& v);

size_t PigeonInternalDeepHash(const ::flutter::EncodableValue& v);

template <typename T>
size_t PigeonInternalDeepHash(const T& v) {
  return std::hash<T>()(v);
}

template <typename T>
size_t PigeonInternalDeepHash(const std::vector<T>& v) {
  size_t result = 1;
  for (const auto& item : v) {
    result = result * 31 + PigeonInternalDeepHash(item);
  }
  return result;
}

template <typename K, typename V>
size_t PigeonInternalDeepHash(const std::map<K, V>& v) {
  size_t result = 0;
  for (const auto& kv : v) {
    result += ((PigeonInternalDeepHash(kv.first) * 31) ^ PigeonInternalDeepHash(kv.second));
  }
  return result;
}

size_t PigeonInternalDeepHash(const double& v) {
  if (std::isnan(v)) {
    // Normalize NaN to a consistent hash.
    return std::hash<double>()(std::numeric_limits<double>::quiet_NaN());
  }
  if (v == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return std::hash<double>()(0.0);
  }
  return std::hash<double>()(v);
}

template <typename T>
size_t PigeonInternalDeepHash(const std::optional<T>& v) {
  return v ? PigeonInternalDeepHash(*v) : 0;
}

template <typename T>
size_t PigeonInternalDeepHash(const std::unique_ptr<T>& v) {
  return v ? PigeonInternalDeepHash(*v) : 0;
}

size_t PigeonInternalDeepHash(const ::flutter::EncodableValue& v) {
  size_t result = v.index();
  if (const double* dv = std::get_if<double>(&v)) {
    result = result * 31 + PigeonInternalDeepHash(*dv);
  } else if (const ::flutter::EncodableList* lv =
                 std::get_if<::flutter::EncodableList>(&v)) {
    result = result * 31 + PigeonInternalDeepHash(*lv);
  } else if (const ::flutter::EncodableMap* mv =
                 std::get_if<::flutter::EncodableMap>(&v)) {
    result = result * 31 + PigeonInternalDeepHash(*mv);
  } else {
    std::visit(
        [&result](const auto& val) {
          using T = std::decay_t<decltype(val)>;
          if constexpr (!std::is_same_v<T, double> &&
                        !std::is_same_v<T, ::flutter::EncodableList> &&
                        !std::is_same_v<T, ::flutter::EncodableMap> &&
                        !std::is_same_v<T, std::monostate> &&
                        !std::is_same_v<T, ::flutter::CustomEncodableValue>) {
            result = result * 31 + PigeonInternalDeepHash(val);
          }
        },
        v);
  }
  return result;
}

template <typename T>
std::string PigeonInternalToString(const T& v);

std::string PigeonInternalToString(const bool& v);

template <typename T>
std::string PigeonInternalToString(const std::vector<T>& v);

template <typename K, typename V>
std::string PigeonInternalToString(const std::map<K, V>& v);

template <typename T>
std::string PigeonInternalToString(const std::optional<T>& v);

template <typename T>
std::string PigeonInternalToString(const std::unique_ptr<T>& v);

std::string PigeonInternalToString(const ::flutter::EncodableValue& v);

template <typename T>
std::string PigeonInternalToString(const T& v) {
  std::stringstream ss;
  if constexpr (std::is_enum_v<T>) {
    ss << static_cast<int>(v);
  } else {
    ss << v;
  }
  return ss.str();
}

std::string PigeonInternalToString(const bool& v) {
  return v ? "true" : "false";
}

template <typename T>
std::string PigeonInternalToString(const std::vector<T>& v) {
  std::stringstream ss;
  ss << "[";
  for (size_t i = 0; i < v.size(); ++i) {
    if (i > 0) {
      ss << ", ";
    }
    ss << PigeonInternalToString(v[i]);
  }
  ss << "]";
  return ss.str();
}

template <typename K, typename V>
std::string PigeonInternalToString(const std::map<K, V>& v) {
  std::stringstream ss;
  ss << "{";
  bool first = true;
  for (const auto& kv : v) {
    if (!first) {
      ss << ", ";
    }
    first = false;
    ss << PigeonInternalToString(kv.first) << ": " << PigeonInternalToString(kv.second);
  }
  ss << "}";
  return ss.str();
}

template <typename T>
std::string PigeonInternalToString(const std::optional<T>& v) {
  return v ? PigeonInternalToString(*v) : "null";
}

template <typename T>
std::string PigeonInternalToString(const std::unique_ptr<T>& v) {
  return v ? PigeonInternalToString(*v) : "null";
}

std::string PigeonInternalToString(const ::flutter::EncodableValue& v) {
  return std::visit(
      [](const auto& val) {
        using T = std::decay_t<decltype(val)>;
        if constexpr (std::is_same_v<T, std::monostate>) {
          return std::string("null");
        } else if constexpr (std::is_same_v<T, bool>) {
          return val ? std::string("true") : std::string("false");
        } else if constexpr (std::is_same_v<T, std::string>) {
          return "\"" + val + "\"";
        } else if constexpr (std::is_same_v<T, ::flutter::CustomEncodableValue>) {
          return std::string("[custom]");
        } else {
          return PigeonInternalToString(val);
        }
      },
      v);
}

}  // namespace
// AudioSourceMessage

AudioSourceMessage::AudioSourceMessage(
  const SourceTypeMessage& type,
  const std::string& uri)
 : type_(type),
    uri_(uri) {}

AudioSourceMessage::AudioSourceMessage(
  const SourceTypeMessage& type,
  const std::string& uri,
  const EncodableMap* headers)
 : type_(type),
    uri_(uri),
    headers_(headers ? std::optional<EncodableMap>(*headers) : std::nullopt) {}

const SourceTypeMessage& AudioSourceMessage::type() const {
  return type_;
}

void AudioSourceMessage::set_type(const SourceTypeMessage& value_arg) {
  type_ = value_arg;
}


const std::string& AudioSourceMessage::uri() const {
  return uri_;
}

void AudioSourceMessage::set_uri(std::string_view value_arg) {
  uri_ = value_arg;
}


const EncodableMap* AudioSourceMessage::headers() const {
  return headers_ ? &(*headers_) : nullptr;
}

void AudioSourceMessage::set_headers(const EncodableMap* value_arg) {
  headers_ = value_arg ? std::optional<EncodableMap>(*value_arg) : std::nullopt;
}

void AudioSourceMessage::set_headers(const EncodableMap& value_arg) {
  headers_ = value_arg;
}


EncodableList AudioSourceMessage::ToEncodableList() const {
  EncodableList list;
  list.reserve(3);
  list.push_back(CustomEncodableValue(type_));
  list.push_back(EncodableValue(uri_));
  list.push_back(headers_ ? EncodableValue(*headers_) : EncodableValue());
  return list;
}

AudioSourceMessage AudioSourceMessage::FromEncodableList(const EncodableList& list) {
  AudioSourceMessage decoded(
    std::any_cast<const SourceTypeMessage&>(std::get<CustomEncodableValue>(list[0])),
    std::get<std::string>(list[1]));
  auto& encodable_headers = list[2];
  if (!encodable_headers.IsNull()) {
    decoded.set_headers(std::get<EncodableMap>(encodable_headers));
  }
  return decoded;
}

bool AudioSourceMessage::operator==(const AudioSourceMessage& other) const {
  return PigeonInternalDeepEquals(type_, other.type_) && PigeonInternalDeepEquals(uri_, other.uri_) && PigeonInternalDeepEquals(headers_, other.headers_);
}

bool AudioSourceMessage::operator!=(const AudioSourceMessage& other) const {
  return !(*this == other);
}

size_t AudioSourceMessage::Hash() const {
  size_t result = 1;
  result = result * 31 + PigeonInternalDeepHash(type_);
  result = result * 31 + PigeonInternalDeepHash(uri_);
  result = result * 31 + PigeonInternalDeepHash(headers_);
  return result;
}

std::ostream& operator<<(
  std::ostream& os,
  const AudioSourceMessage& obj) {
  os << "AudioSourceMessage(";
  os << "type: ";
  os << PigeonInternalToString(obj.type_);
  os << ", uri: ";
  os << PigeonInternalToString(obj.uri_);
  os << ", headers: ";
  if (obj.headers_) {
    os << PigeonInternalToString(*obj.headers_);
  }
  else {
    os << "null";
  }
  os << ")";
  return os;
}

size_t PigeonInternalDeepHash(const AudioSourceMessage& v) {
  return v.Hash();
}

// RecordConfigMessage

RecordConfigMessage::RecordConfigMessage(
  const EncoderMessage& encoder,
  int64_t sample_rate,
  int64_t num_channels,
  int64_t bit_rate,
  int64_t amplitude_interval_ms)
 : encoder_(encoder),
    sample_rate_(sample_rate),
    num_channels_(num_channels),
    bit_rate_(bit_rate),
    amplitude_interval_ms_(amplitude_interval_ms) {}

RecordConfigMessage::RecordConfigMessage(
  const EncoderMessage& encoder,
  int64_t sample_rate,
  int64_t num_channels,
  int64_t bit_rate,
  int64_t amplitude_interval_ms,
  const std::string* device_id)
 : encoder_(encoder),
    sample_rate_(sample_rate),
    num_channels_(num_channels),
    bit_rate_(bit_rate),
    amplitude_interval_ms_(amplitude_interval_ms),
    device_id_(device_id ? std::optional<std::string>(*device_id) : std::nullopt) {}

const EncoderMessage& RecordConfigMessage::encoder() const {
  return encoder_;
}

void RecordConfigMessage::set_encoder(const EncoderMessage& value_arg) {
  encoder_ = value_arg;
}


int64_t RecordConfigMessage::sample_rate() const {
  return sample_rate_;
}

void RecordConfigMessage::set_sample_rate(int64_t value_arg) {
  sample_rate_ = value_arg;
}


int64_t RecordConfigMessage::num_channels() const {
  return num_channels_;
}

void RecordConfigMessage::set_num_channels(int64_t value_arg) {
  num_channels_ = value_arg;
}


int64_t RecordConfigMessage::bit_rate() const {
  return bit_rate_;
}

void RecordConfigMessage::set_bit_rate(int64_t value_arg) {
  bit_rate_ = value_arg;
}


int64_t RecordConfigMessage::amplitude_interval_ms() const {
  return amplitude_interval_ms_;
}

void RecordConfigMessage::set_amplitude_interval_ms(int64_t value_arg) {
  amplitude_interval_ms_ = value_arg;
}


const std::string* RecordConfigMessage::device_id() const {
  return device_id_ ? &(*device_id_) : nullptr;
}

void RecordConfigMessage::set_device_id(const std::string_view* value_arg) {
  device_id_ = value_arg ? std::optional<std::string>(*value_arg) : std::nullopt;
}

void RecordConfigMessage::set_device_id(std::string_view value_arg) {
  device_id_ = value_arg;
}


EncodableList RecordConfigMessage::ToEncodableList() const {
  EncodableList list;
  list.reserve(6);
  list.push_back(CustomEncodableValue(encoder_));
  list.push_back(EncodableValue(sample_rate_));
  list.push_back(EncodableValue(num_channels_));
  list.push_back(EncodableValue(bit_rate_));
  list.push_back(EncodableValue(amplitude_interval_ms_));
  list.push_back(device_id_ ? EncodableValue(*device_id_) : EncodableValue());
  return list;
}

RecordConfigMessage RecordConfigMessage::FromEncodableList(const EncodableList& list) {
  RecordConfigMessage decoded(
    std::any_cast<const EncoderMessage&>(std::get<CustomEncodableValue>(list[0])),
    std::get<int64_t>(list[1]),
    std::get<int64_t>(list[2]),
    std::get<int64_t>(list[3]),
    std::get<int64_t>(list[4]));
  auto& encodable_device_id = list[5];
  if (!encodable_device_id.IsNull()) {
    decoded.set_device_id(std::get<std::string>(encodable_device_id));
  }
  return decoded;
}

bool RecordConfigMessage::operator==(const RecordConfigMessage& other) const {
  return PigeonInternalDeepEquals(encoder_, other.encoder_) && PigeonInternalDeepEquals(sample_rate_, other.sample_rate_) && PigeonInternalDeepEquals(num_channels_, other.num_channels_) && PigeonInternalDeepEquals(bit_rate_, other.bit_rate_) && PigeonInternalDeepEquals(amplitude_interval_ms_, other.amplitude_interval_ms_) && PigeonInternalDeepEquals(device_id_, other.device_id_);
}

bool RecordConfigMessage::operator!=(const RecordConfigMessage& other) const {
  return !(*this == other);
}

size_t RecordConfigMessage::Hash() const {
  size_t result = 1;
  result = result * 31 + PigeonInternalDeepHash(encoder_);
  result = result * 31 + PigeonInternalDeepHash(sample_rate_);
  result = result * 31 + PigeonInternalDeepHash(num_channels_);
  result = result * 31 + PigeonInternalDeepHash(bit_rate_);
  result = result * 31 + PigeonInternalDeepHash(amplitude_interval_ms_);
  result = result * 31 + PigeonInternalDeepHash(device_id_);
  return result;
}

std::ostream& operator<<(
  std::ostream& os,
  const RecordConfigMessage& obj) {
  os << "RecordConfigMessage(";
  os << "encoder: ";
  os << PigeonInternalToString(obj.encoder_);
  os << ", sample_rate: ";
  os << PigeonInternalToString(obj.sample_rate_);
  os << ", num_channels: ";
  os << PigeonInternalToString(obj.num_channels_);
  os << ", bit_rate: ";
  os << PigeonInternalToString(obj.bit_rate_);
  os << ", amplitude_interval_ms: ";
  os << PigeonInternalToString(obj.amplitude_interval_ms_);
  os << ", device_id: ";
  if (obj.device_id_) {
    os << PigeonInternalToString(*obj.device_id_);
  }
  else {
    os << "null";
  }
  os << ")";
  return os;
}

size_t PigeonInternalDeepHash(const RecordConfigMessage& v) {
  return v.Hash();
}

// AudioDeviceMessage

AudioDeviceMessage::AudioDeviceMessage(
  const std::string& id,
  const std::string& label)
 : id_(id),
    label_(label) {}

const std::string& AudioDeviceMessage::id() const {
  return id_;
}

void AudioDeviceMessage::set_id(std::string_view value_arg) {
  id_ = value_arg;
}


const std::string& AudioDeviceMessage::label() const {
  return label_;
}

void AudioDeviceMessage::set_label(std::string_view value_arg) {
  label_ = value_arg;
}


EncodableList AudioDeviceMessage::ToEncodableList() const {
  EncodableList list;
  list.reserve(2);
  list.push_back(EncodableValue(id_));
  list.push_back(EncodableValue(label_));
  return list;
}

AudioDeviceMessage AudioDeviceMessage::FromEncodableList(const EncodableList& list) {
  AudioDeviceMessage decoded(
    std::get<std::string>(list[0]),
    std::get<std::string>(list[1]));
  return decoded;
}

bool AudioDeviceMessage::operator==(const AudioDeviceMessage& other) const {
  return PigeonInternalDeepEquals(id_, other.id_) && PigeonInternalDeepEquals(label_, other.label_);
}

bool AudioDeviceMessage::operator!=(const AudioDeviceMessage& other) const {
  return !(*this == other);
}

size_t AudioDeviceMessage::Hash() const {
  size_t result = 1;
  result = result * 31 + PigeonInternalDeepHash(id_);
  result = result * 31 + PigeonInternalDeepHash(label_);
  return result;
}

std::ostream& operator<<(
  std::ostream& os,
  const AudioDeviceMessage& obj) {
  os << "AudioDeviceMessage(";
  os << "id: ";
  os << PigeonInternalToString(obj.id_);
  os << ", label: ";
  os << PigeonInternalToString(obj.label_);
  os << ")";
  return os;
}

size_t PigeonInternalDeepHash(const AudioDeviceMessage& v) {
  return v.Hash();
}


PigeonInternalCodecSerializer::PigeonInternalCodecSerializer() {}

EncodableValue PigeonInternalCodecSerializer::ReadValueOfType(
  uint8_t type,
  ::flutter::ByteStreamReader* stream) const {
  switch (type) {
    case 129: {
        const auto& encodable_enum_arg = ReadValue(stream);
        const int64_t enum_arg_value = encodable_enum_arg.IsNull() ? 0 : encodable_enum_arg.LongValue();
        return encodable_enum_arg.IsNull() ? EncodableValue() : CustomEncodableValue(static_cast<SourceTypeMessage>(enum_arg_value));
      }
    case 130: {
        const auto& encodable_enum_arg = ReadValue(stream);
        const int64_t enum_arg_value = encodable_enum_arg.IsNull() ? 0 : encodable_enum_arg.LongValue();
        return encodable_enum_arg.IsNull() ? EncodableValue() : CustomEncodableValue(static_cast<EncoderMessage>(enum_arg_value));
      }
    case 131: {
        return CustomEncodableValue(AudioSourceMessage::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
      }
    case 132: {
        return CustomEncodableValue(RecordConfigMessage::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
      }
    case 133: {
        return CustomEncodableValue(AudioDeviceMessage::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
      }
    default:
      return ::flutter::StandardCodecSerializer::ReadValueOfType(type, stream);
    }
}

void PigeonInternalCodecSerializer::WriteValue(
  const EncodableValue& value,
  ::flutter::ByteStreamWriter* stream) const {
  if (const CustomEncodableValue* custom_value = std::get_if<CustomEncodableValue>(&value)) {
    if (custom_value->type() == typeid(SourceTypeMessage)) {
      stream->WriteByte(129);
      WriteValue(EncodableValue(static_cast<int>(std::any_cast<SourceTypeMessage>(*custom_value))), stream);
      return;
    }
    if (custom_value->type() == typeid(EncoderMessage)) {
      stream->WriteByte(130);
      WriteValue(EncodableValue(static_cast<int>(std::any_cast<EncoderMessage>(*custom_value))), stream);
      return;
    }
    if (custom_value->type() == typeid(AudioSourceMessage)) {
      stream->WriteByte(131);
      WriteValue(EncodableValue(std::any_cast<AudioSourceMessage>(*custom_value).ToEncodableList()), stream);
      return;
    }
    if (custom_value->type() == typeid(RecordConfigMessage)) {
      stream->WriteByte(132);
      WriteValue(EncodableValue(std::any_cast<RecordConfigMessage>(*custom_value).ToEncodableList()), stream);
      return;
    }
    if (custom_value->type() == typeid(AudioDeviceMessage)) {
      stream->WriteByte(133);
      WriteValue(EncodableValue(std::any_cast<AudioDeviceMessage>(*custom_value).ToEncodableList()), stream);
      return;
    }
  }
  ::flutter::StandardCodecSerializer::WriteValue(value, stream);
}

/// The codec used by AudioPlayerHostApi.
const ::flutter::StandardMessageCodec& AudioPlayerHostApi::GetCodec() {
  return ::flutter::StandardMessageCodec::GetInstance(&PigeonInternalCodecSerializer::GetInstance());
}

// Sets up an instance of `AudioPlayerHostApi` to handle messages through the `binary_messenger`.
void AudioPlayerHostApi::SetUp(
  ::flutter::BinaryMessenger* binary_messenger,
  AudioPlayerHostApi* api) {
  AudioPlayerHostApi::SetUp(binary_messenger, api, "");
}

void AudioPlayerHostApi::SetUp(
  ::flutter::BinaryMessenger* binary_messenger,
  AudioPlayerHostApi* api,
  const std::string& message_channel_suffix) {
  const std::string prepended_suffix = message_channel_suffix.length() > 0 ? std::string(".") + message_channel_suffix : "";
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.xue_hua_audio_platform_interface.AudioPlayerHostApi.createPlayer" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const ::flutter::MessageReply<EncodableValue>& reply) {
        try {
          ErrorOr<int64_t> output = api->CreatePlayer();
          if (output.has_error()) {
            reply(WrapError(output.error()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(EncodableValue(std::move(output).TakeValue()));
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.xue_hua_audio_platform_interface.AudioPlayerHostApi.setSource" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const ::flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_player_id_arg = args.at(0);
          if (encodable_player_id_arg.IsNull()) {
            reply(WrapError("player_id_arg unexpectedly null."));
            return;
          }
          const int64_t player_id_arg = encodable_player_id_arg.LongValue();
          const auto& encodable_source_arg = args.at(1);
          if (encodable_source_arg.IsNull()) {
            reply(WrapError("source_arg unexpectedly null."));
            return;
          }
          const auto& source_arg = std::any_cast<const AudioSourceMessage&>(std::get<CustomEncodableValue>(encodable_source_arg));
          api->SetSource(player_id_arg, source_arg, [reply](ErrorOr<std::optional<int64_t>>&& output) {
            if (output.has_error()) {
              reply(WrapError(output.error()));
              return;
            }
            EncodableList wrapped;
            auto output_optional = std::move(output).TakeValue();
            if (output_optional) {
              wrapped.push_back(EncodableValue(std::move(output_optional).value()));
            } else {
              wrapped.push_back(EncodableValue());
            }
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.xue_hua_audio_platform_interface.AudioPlayerHostApi.play" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const ::flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_player_id_arg = args.at(0);
          if (encodable_player_id_arg.IsNull()) {
            reply(WrapError("player_id_arg unexpectedly null."));
            return;
          }
          const int64_t player_id_arg = encodable_player_id_arg.LongValue();
          std::optional<FlutterError> output = api->Play(player_id_arg);
          if (output.has_value()) {
            reply(WrapError(output.value()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(EncodableValue());
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.xue_hua_audio_platform_interface.AudioPlayerHostApi.pause" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const ::flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_player_id_arg = args.at(0);
          if (encodable_player_id_arg.IsNull()) {
            reply(WrapError("player_id_arg unexpectedly null."));
            return;
          }
          const int64_t player_id_arg = encodable_player_id_arg.LongValue();
          std::optional<FlutterError> output = api->Pause(player_id_arg);
          if (output.has_value()) {
            reply(WrapError(output.value()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(EncodableValue());
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.xue_hua_audio_platform_interface.AudioPlayerHostApi.stop" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const ::flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_player_id_arg = args.at(0);
          if (encodable_player_id_arg.IsNull()) {
            reply(WrapError("player_id_arg unexpectedly null."));
            return;
          }
          const int64_t player_id_arg = encodable_player_id_arg.LongValue();
          std::optional<FlutterError> output = api->Stop(player_id_arg);
          if (output.has_value()) {
            reply(WrapError(output.value()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(EncodableValue());
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.xue_hua_audio_platform_interface.AudioPlayerHostApi.seekTo" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const ::flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_player_id_arg = args.at(0);
          if (encodable_player_id_arg.IsNull()) {
            reply(WrapError("player_id_arg unexpectedly null."));
            return;
          }
          const int64_t player_id_arg = encodable_player_id_arg.LongValue();
          const auto& encodable_position_ms_arg = args.at(1);
          if (encodable_position_ms_arg.IsNull()) {
            reply(WrapError("position_ms_arg unexpectedly null."));
            return;
          }
          const int64_t position_ms_arg = encodable_position_ms_arg.LongValue();
          api->SeekTo(player_id_arg, position_ms_arg, [reply](std::optional<FlutterError>&& output) {
            if (output.has_value()) {
              reply(WrapError(output.value()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(EncodableValue());
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.xue_hua_audio_platform_interface.AudioPlayerHostApi.setVolume" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const ::flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_player_id_arg = args.at(0);
          if (encodable_player_id_arg.IsNull()) {
            reply(WrapError("player_id_arg unexpectedly null."));
            return;
          }
          const int64_t player_id_arg = encodable_player_id_arg.LongValue();
          const auto& encodable_volume_arg = args.at(1);
          if (encodable_volume_arg.IsNull()) {
            reply(WrapError("volume_arg unexpectedly null."));
            return;
          }
          const auto& volume_arg = std::get<double>(encodable_volume_arg);
          std::optional<FlutterError> output = api->SetVolume(player_id_arg, volume_arg);
          if (output.has_value()) {
            reply(WrapError(output.value()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(EncodableValue());
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.xue_hua_audio_platform_interface.AudioPlayerHostApi.setSpeed" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const ::flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_player_id_arg = args.at(0);
          if (encodable_player_id_arg.IsNull()) {
            reply(WrapError("player_id_arg unexpectedly null."));
            return;
          }
          const int64_t player_id_arg = encodable_player_id_arg.LongValue();
          const auto& encodable_speed_arg = args.at(1);
          if (encodable_speed_arg.IsNull()) {
            reply(WrapError("speed_arg unexpectedly null."));
            return;
          }
          const auto& speed_arg = std::get<double>(encodable_speed_arg);
          std::optional<FlutterError> output = api->SetSpeed(player_id_arg, speed_arg);
          if (output.has_value()) {
            reply(WrapError(output.value()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(EncodableValue());
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.xue_hua_audio_platform_interface.AudioPlayerHostApi.setLooping" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const ::flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_player_id_arg = args.at(0);
          if (encodable_player_id_arg.IsNull()) {
            reply(WrapError("player_id_arg unexpectedly null."));
            return;
          }
          const int64_t player_id_arg = encodable_player_id_arg.LongValue();
          const auto& encodable_looping_arg = args.at(1);
          if (encodable_looping_arg.IsNull()) {
            reply(WrapError("looping_arg unexpectedly null."));
            return;
          }
          const auto& looping_arg = std::get<bool>(encodable_looping_arg);
          std::optional<FlutterError> output = api->SetLooping(player_id_arg, looping_arg);
          if (output.has_value()) {
            reply(WrapError(output.value()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(EncodableValue());
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.xue_hua_audio_platform_interface.AudioPlayerHostApi.getPosition" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const ::flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_player_id_arg = args.at(0);
          if (encodable_player_id_arg.IsNull()) {
            reply(WrapError("player_id_arg unexpectedly null."));
            return;
          }
          const int64_t player_id_arg = encodable_player_id_arg.LongValue();
          ErrorOr<int64_t> output = api->GetPosition(player_id_arg);
          if (output.has_error()) {
            reply(WrapError(output.error()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(EncodableValue(std::move(output).TakeValue()));
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.xue_hua_audio_platform_interface.AudioPlayerHostApi.getDuration" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const ::flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_player_id_arg = args.at(0);
          if (encodable_player_id_arg.IsNull()) {
            reply(WrapError("player_id_arg unexpectedly null."));
            return;
          }
          const int64_t player_id_arg = encodable_player_id_arg.LongValue();
          ErrorOr<std::optional<int64_t>> output = api->GetDuration(player_id_arg);
          if (output.has_error()) {
            reply(WrapError(output.error()));
            return;
          }
          EncodableList wrapped;
          auto output_optional = std::move(output).TakeValue();
          if (output_optional) {
            wrapped.push_back(EncodableValue(std::move(output_optional).value()));
          } else {
            wrapped.push_back(EncodableValue());
          }
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.xue_hua_audio_platform_interface.AudioPlayerHostApi.listOutputDevices" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const ::flutter::MessageReply<EncodableValue>& reply) {
        try {
          api->ListOutputDevices([reply](ErrorOr<EncodableList>&& output) {
            if (output.has_error()) {
              reply(WrapError(output.error()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(EncodableValue(std::move(output).TakeValue()));
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.xue_hua_audio_platform_interface.AudioPlayerHostApi.getOutputDevice" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const ::flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_player_id_arg = args.at(0);
          if (encodable_player_id_arg.IsNull()) {
            reply(WrapError("player_id_arg unexpectedly null."));
            return;
          }
          const int64_t player_id_arg = encodable_player_id_arg.LongValue();
          api->GetOutputDevice(player_id_arg, [reply](ErrorOr<std::optional<AudioDeviceMessage>>&& output) {
            if (output.has_error()) {
              reply(WrapError(output.error()));
              return;
            }
            EncodableList wrapped;
            auto output_optional = std::move(output).TakeValue();
            if (output_optional) {
              wrapped.push_back(CustomEncodableValue(std::move(output_optional).value()));
            } else {
              wrapped.push_back(EncodableValue());
            }
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.xue_hua_audio_platform_interface.AudioPlayerHostApi.setOutputDevice" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const ::flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_player_id_arg = args.at(0);
          if (encodable_player_id_arg.IsNull()) {
            reply(WrapError("player_id_arg unexpectedly null."));
            return;
          }
          const int64_t player_id_arg = encodable_player_id_arg.LongValue();
          const auto& encodable_device_id_arg = args.at(1);
          const auto* device_id_arg = std::get_if<std::string>(&encodable_device_id_arg);
          api->SetOutputDevice(player_id_arg, device_id_arg, [reply](std::optional<FlutterError>&& output) {
            if (output.has_value()) {
              reply(WrapError(output.value()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(EncodableValue());
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.xue_hua_audio_platform_interface.AudioPlayerHostApi.disposePlayer" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const ::flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_player_id_arg = args.at(0);
          if (encodable_player_id_arg.IsNull()) {
            reply(WrapError("player_id_arg unexpectedly null."));
            return;
          }
          const int64_t player_id_arg = encodable_player_id_arg.LongValue();
          std::optional<FlutterError> output = api->DisposePlayer(player_id_arg);
          if (output.has_value()) {
            reply(WrapError(output.value()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(EncodableValue());
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
}

EncodableValue AudioPlayerHostApi::WrapError(std::string_view error_message) {
  return EncodableValue(EncodableList{
    EncodableValue(std::string(error_message)),
    EncodableValue("Error"),
    EncodableValue()
  });
}

EncodableValue AudioPlayerHostApi::WrapError(const FlutterError& error) {
  return EncodableValue(EncodableList{
    EncodableValue(error.code()),
    EncodableValue(error.message()),
    error.details()
  });
}

/// The codec used by AudioRecorderHostApi.
const ::flutter::StandardMessageCodec& AudioRecorderHostApi::GetCodec() {
  return ::flutter::StandardMessageCodec::GetInstance(&PigeonInternalCodecSerializer::GetInstance());
}

// Sets up an instance of `AudioRecorderHostApi` to handle messages through the `binary_messenger`.
void AudioRecorderHostApi::SetUp(
  ::flutter::BinaryMessenger* binary_messenger,
  AudioRecorderHostApi* api) {
  AudioRecorderHostApi::SetUp(binary_messenger, api, "");
}

void AudioRecorderHostApi::SetUp(
  ::flutter::BinaryMessenger* binary_messenger,
  AudioRecorderHostApi* api,
  const std::string& message_channel_suffix) {
  const std::string prepended_suffix = message_channel_suffix.length() > 0 ? std::string(".") + message_channel_suffix : "";
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.xue_hua_audio_platform_interface.AudioRecorderHostApi.createRecorder" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const ::flutter::MessageReply<EncodableValue>& reply) {
        try {
          ErrorOr<int64_t> output = api->CreateRecorder();
          if (output.has_error()) {
            reply(WrapError(output.error()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(EncodableValue(std::move(output).TakeValue()));
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.xue_hua_audio_platform_interface.AudioRecorderHostApi.hasPermission" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const ::flutter::MessageReply<EncodableValue>& reply) {
        try {
          api->HasPermission([reply](ErrorOr<bool>&& output) {
            if (output.has_error()) {
              reply(WrapError(output.error()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(EncodableValue(std::move(output).TakeValue()));
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.xue_hua_audio_platform_interface.AudioRecorderHostApi.listInputDevices" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const ::flutter::MessageReply<EncodableValue>& reply) {
        try {
          api->ListInputDevices([reply](ErrorOr<EncodableList>&& output) {
            if (output.has_error()) {
              reply(WrapError(output.error()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(EncodableValue(std::move(output).TakeValue()));
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.xue_hua_audio_platform_interface.AudioRecorderHostApi.getInputDevice" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const ::flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_recorder_id_arg = args.at(0);
          if (encodable_recorder_id_arg.IsNull()) {
            reply(WrapError("recorder_id_arg unexpectedly null."));
            return;
          }
          const int64_t recorder_id_arg = encodable_recorder_id_arg.LongValue();
          api->GetInputDevice(recorder_id_arg, [reply](ErrorOr<std::optional<AudioDeviceMessage>>&& output) {
            if (output.has_error()) {
              reply(WrapError(output.error()));
              return;
            }
            EncodableList wrapped;
            auto output_optional = std::move(output).TakeValue();
            if (output_optional) {
              wrapped.push_back(CustomEncodableValue(std::move(output_optional).value()));
            } else {
              wrapped.push_back(EncodableValue());
            }
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.xue_hua_audio_platform_interface.AudioRecorderHostApi.setInputDevice" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const ::flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_recorder_id_arg = args.at(0);
          if (encodable_recorder_id_arg.IsNull()) {
            reply(WrapError("recorder_id_arg unexpectedly null."));
            return;
          }
          const int64_t recorder_id_arg = encodable_recorder_id_arg.LongValue();
          const auto& encodable_device_id_arg = args.at(1);
          const auto* device_id_arg = std::get_if<std::string>(&encodable_device_id_arg);
          api->SetInputDevice(recorder_id_arg, device_id_arg, [reply](std::optional<FlutterError>&& output) {
            if (output.has_value()) {
              reply(WrapError(output.value()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(EncodableValue());
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.xue_hua_audio_platform_interface.AudioRecorderHostApi.start" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const ::flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_recorder_id_arg = args.at(0);
          if (encodable_recorder_id_arg.IsNull()) {
            reply(WrapError("recorder_id_arg unexpectedly null."));
            return;
          }
          const int64_t recorder_id_arg = encodable_recorder_id_arg.LongValue();
          const auto& encodable_config_arg = args.at(1);
          if (encodable_config_arg.IsNull()) {
            reply(WrapError("config_arg unexpectedly null."));
            return;
          }
          const auto& config_arg = std::any_cast<const RecordConfigMessage&>(std::get<CustomEncodableValue>(encodable_config_arg));
          const auto& encodable_path_arg = args.at(2);
          if (encodable_path_arg.IsNull()) {
            reply(WrapError("path_arg unexpectedly null."));
            return;
          }
          const auto& path_arg = std::get<std::string>(encodable_path_arg);
          api->Start(recorder_id_arg, config_arg, path_arg, [reply](std::optional<FlutterError>&& output) {
            if (output.has_value()) {
              reply(WrapError(output.value()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(EncodableValue());
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.xue_hua_audio_platform_interface.AudioRecorderHostApi.pause" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const ::flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_recorder_id_arg = args.at(0);
          if (encodable_recorder_id_arg.IsNull()) {
            reply(WrapError("recorder_id_arg unexpectedly null."));
            return;
          }
          const int64_t recorder_id_arg = encodable_recorder_id_arg.LongValue();
          std::optional<FlutterError> output = api->Pause(recorder_id_arg);
          if (output.has_value()) {
            reply(WrapError(output.value()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(EncodableValue());
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.xue_hua_audio_platform_interface.AudioRecorderHostApi.resume" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const ::flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_recorder_id_arg = args.at(0);
          if (encodable_recorder_id_arg.IsNull()) {
            reply(WrapError("recorder_id_arg unexpectedly null."));
            return;
          }
          const int64_t recorder_id_arg = encodable_recorder_id_arg.LongValue();
          std::optional<FlutterError> output = api->Resume(recorder_id_arg);
          if (output.has_value()) {
            reply(WrapError(output.value()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(EncodableValue());
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.xue_hua_audio_platform_interface.AudioRecorderHostApi.stop" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const ::flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_recorder_id_arg = args.at(0);
          if (encodable_recorder_id_arg.IsNull()) {
            reply(WrapError("recorder_id_arg unexpectedly null."));
            return;
          }
          const int64_t recorder_id_arg = encodable_recorder_id_arg.LongValue();
          api->Stop(recorder_id_arg, [reply](ErrorOr<std::optional<std::string>>&& output) {
            if (output.has_error()) {
              reply(WrapError(output.error()));
              return;
            }
            EncodableList wrapped;
            auto output_optional = std::move(output).TakeValue();
            if (output_optional) {
              wrapped.push_back(EncodableValue(std::move(output_optional).value()));
            } else {
              wrapped.push_back(EncodableValue());
            }
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.xue_hua_audio_platform_interface.AudioRecorderHostApi.cancel" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const ::flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_recorder_id_arg = args.at(0);
          if (encodable_recorder_id_arg.IsNull()) {
            reply(WrapError("recorder_id_arg unexpectedly null."));
            return;
          }
          const int64_t recorder_id_arg = encodable_recorder_id_arg.LongValue();
          api->Cancel(recorder_id_arg, [reply](std::optional<FlutterError>&& output) {
            if (output.has_value()) {
              reply(WrapError(output.value()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(EncodableValue());
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.xue_hua_audio_platform_interface.AudioRecorderHostApi.disposeRecorder" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const ::flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_recorder_id_arg = args.at(0);
          if (encodable_recorder_id_arg.IsNull()) {
            reply(WrapError("recorder_id_arg unexpectedly null."));
            return;
          }
          const int64_t recorder_id_arg = encodable_recorder_id_arg.LongValue();
          std::optional<FlutterError> output = api->DisposeRecorder(recorder_id_arg);
          if (output.has_value()) {
            reply(WrapError(output.value()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(EncodableValue());
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
}

EncodableValue AudioRecorderHostApi::WrapError(std::string_view error_message) {
  return EncodableValue(EncodableList{
    EncodableValue(std::string(error_message)),
    EncodableValue("Error"),
    EncodableValue()
  });
}

EncodableValue AudioRecorderHostApi::WrapError(const FlutterError& error) {
  return EncodableValue(EncodableList{
    EncodableValue(error.code()),
    EncodableValue(error.message()),
    error.details()
  });
}

}  // namespace xue_hua_audio_windows
