// Autogenerated from Pigeon (v27.3.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
  List<Object?>? replyList,
  String channelName, {
  required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed.every(
          ((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]),
        );
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}

/// The kind of an audio source. / 音频源的种类。
enum SourceTypeMessage {
  /// A local file path. / 本地文件路径。
  file,

  /// A remote HTTP(S) URL. / 远程 HTTP(S) 网络地址。
  url,

  /// A Flutter asset key. / Flutter Asset 资源键。
  asset,
}

/// The audio encoder used when recording. / 录音时使用的编码器。
enum EncoderMessage {
  /// Linear PCM in a WAV container. / WAV 容器中的线性 PCM。
  wav,

  /// AAC-LC in an MPEG-4 container. / MPEG-4 容器中的 AAC-LC。
  aacLc,

  /// Opus (Ogg or WebM container, platform dependent). / Opus 编码（Ogg 或 WebM 容器，视平台而定）。
  opus,
}

/// Wire representation of an audio source. / 音频源的跨端传输结构。
class AudioSourceMessage {
  AudioSourceMessage({required this.type, required this.uri, this.headers});

  /// The kind of source. / 源的种类。
  SourceTypeMessage type;

  /// File path, URL, or fully-resolved asset key depending on [type].
  /// 依据 [type] 不同，可能是文件路径、URL 或已解析的 asset 键。
  String uri;

  /// Optional HTTP headers, only meaningful for [SourceTypeMessage.url].
  /// 可选的 HTTP 请求头，仅对 [SourceTypeMessage.url] 有意义。
  Map<String, String>? headers;

  List<Object?> _toList() {
    return <Object?>[type, uri, headers];
  }

  Object encode() {
    return _toList();
  }

  static AudioSourceMessage decode(Object result) {
    result as List<Object?>;
    return AudioSourceMessage(
      type: result[0]! as SourceTypeMessage,
      uri: result[1]! as String,
      headers: (result[2] as Map<Object?, Object?>?)?.cast<String, String>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AudioSourceMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(type, other.type) &&
        _deepEquals(uri, other.uri) &&
        _deepEquals(headers, other.headers);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'AudioSourceMessage(type: $type, uri: $uri, headers: $headers)';
  }
}

/// Wire representation of a recording configuration. / 录音配置的跨端传输结构。
class RecordConfigMessage {
  RecordConfigMessage({
    required this.encoder,
    required this.sampleRate,
    required this.numChannels,
    required this.bitRate,
    required this.amplitudeIntervalMs,
    this.deviceId,
  });

  /// Encoder to use. / 使用的编码器。
  EncoderMessage encoder;

  /// Sample rate in Hz. / 采样率（Hz）。
  int sampleRate;

  /// Number of channels (1 = mono, 2 = stereo). / 声道数（1 单声道，2 立体声）。
  int numChannels;

  /// Bit rate in bits per second (compressed encoders only).
  /// 比特率（bit/s，仅压缩编码器使用）。
  int bitRate;

  /// Interval between amplitude events in milliseconds.
  /// 振幅事件的推送间隔（毫秒）。
  int amplitudeIntervalMs;

  /// Preferred input device id, `null` for the system default.
  /// 期望使用的输入设备 id，`null` 表示系统默认设备。
  String? deviceId;

  List<Object?> _toList() {
    return <Object?>[
      encoder,
      sampleRate,
      numChannels,
      bitRate,
      amplitudeIntervalMs,
      deviceId,
    ];
  }

  Object encode() {
    return _toList();
  }

  static RecordConfigMessage decode(Object result) {
    result as List<Object?>;
    return RecordConfigMessage(
      encoder: result[0]! as EncoderMessage,
      sampleRate: result[1]! as int,
      numChannels: result[2]! as int,
      bitRate: result[3]! as int,
      amplitudeIntervalMs: result[4]! as int,
      deviceId: result[5] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! RecordConfigMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encoder, other.encoder) &&
        _deepEquals(sampleRate, other.sampleRate) &&
        _deepEquals(numChannels, other.numChannels) &&
        _deepEquals(bitRate, other.bitRate) &&
        _deepEquals(amplitudeIntervalMs, other.amplitudeIntervalMs) &&
        _deepEquals(deviceId, other.deviceId);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'RecordConfigMessage(encoder: $encoder, sampleRate: $sampleRate, numChannels: $numChannels, bitRate: $bitRate, amplitudeIntervalMs: $amplitudeIntervalMs, deviceId: $deviceId)';
  }
}

/// Wire representation of an audio device (input or output).
/// 音频设备（输入或输出）的跨端传输结构。
class AudioDeviceMessage {
  AudioDeviceMessage({required this.id, required this.label});

  /// Platform-specific stable device identifier. / 平台相关的稳定设备标识。
  String id;

  /// Human-readable device name. / 供人阅读的设备名称。
  String label;

  List<Object?> _toList() {
    return <Object?>[id, label];
  }

  Object encode() {
    return _toList();
  }

  static AudioDeviceMessage decode(Object result) {
    result as List<Object?>;
    return AudioDeviceMessage(
      id: result[0]! as String,
      label: result[1]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AudioDeviceMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(id, other.id) && _deepEquals(label, other.label);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'AudioDeviceMessage(id: $id, label: $label)';
  }
}

class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    } else if (value is SourceTypeMessage) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    } else if (value is EncoderMessage) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    } else if (value is AudioSourceMessage) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    } else if (value is RecordConfigMessage) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    } else if (value is AudioDeviceMessage) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final value = readValue(buffer) as int?;
        return value == null ? null : SourceTypeMessage.values[value];
      case 130:
        final value = readValue(buffer) as int?;
        return value == null ? null : EncoderMessage.values[value];
      case 131:
        return AudioSourceMessage.decode(readValue(buffer)!);
      case 132:
        return RecordConfigMessage.decode(readValue(buffer)!);
      case 133:
        return AudioDeviceMessage.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

/// Host API implemented natively for audio playback control.
/// 由原生端实现的音频播放控制接口。
class AudioPlayerHostApi {
  /// Constructor for [AudioPlayerHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  AudioPlayerHostApi({
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) : pigeonVar_binaryMessenger = binaryMessenger,
       pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty
           ? '.$messageChannelSuffix'
           : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// Creates a native player instance and returns its id.
  /// 创建一个原生播放器实例并返回其 id。
  Future<int> createPlayer() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.xue_hua_audio_platform_interface.AudioPlayerHostApi.createPlayer$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as int;
  }

  /// Loads [source] into the player and returns the duration in
  /// milliseconds, or `null` when unknown (e.g. live streams).
  /// 加载音频源 [source]，返回音频时长（毫秒）；未知时（如直播流）返回 `null`。
  Future<int?> setSource(int playerId, AudioSourceMessage source) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.xue_hua_audio_platform_interface.AudioPlayerHostApi.setSource$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[playerId, source],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
    return pigeonVar_replyValue as int?;
  }

  /// Starts or resumes playback. / 开始或恢复播放。
  Future<void> play(int playerId) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.xue_hua_audio_platform_interface.AudioPlayerHostApi.play$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[playerId],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  /// Pauses playback keeping the position. / 暂停播放并保留进度。
  Future<void> pause(int playerId) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.xue_hua_audio_platform_interface.AudioPlayerHostApi.pause$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[playerId],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  /// Stops playback and rewinds to the beginning. / 停止播放并回到起点。
  Future<void> stop(int playerId) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.xue_hua_audio_platform_interface.AudioPlayerHostApi.stop$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[playerId],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  /// Seeks to [positionMs] milliseconds. / 跳转到 [positionMs]（毫秒）。
  Future<void> seekTo(int playerId, int positionMs) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.xue_hua_audio_platform_interface.AudioPlayerHostApi.seekTo$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[playerId, positionMs],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  /// Sets the volume, 0.0 to 1.0. / 设置音量（0.0 ~ 1.0）。
  Future<void> setVolume(int playerId, double volume) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.xue_hua_audio_platform_interface.AudioPlayerHostApi.setVolume$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[playerId, volume],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  /// Sets the playback speed, e.g. 0.5 to 2.0. / 设置播放速度（如 0.5 ~ 2.0）。
  Future<void> setSpeed(int playerId, double speed) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.xue_hua_audio_platform_interface.AudioPlayerHostApi.setSpeed$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[playerId, speed],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  /// Enables or disables looping. / 开启或关闭循环播放。
  Future<void> setLooping(int playerId, bool looping) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.xue_hua_audio_platform_interface.AudioPlayerHostApi.setLooping$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[playerId, looping],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  /// Returns the current position in milliseconds. / 返回当前播放位置（毫秒）。
  Future<int> getPosition(int playerId) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.xue_hua_audio_platform_interface.AudioPlayerHostApi.getPosition$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[playerId],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as int;
  }

  /// Returns the duration in milliseconds or `null` when unknown.
  /// 返回音频时长（毫秒），未知时返回 `null`。
  Future<int?> getDuration(int playerId) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.xue_hua_audio_platform_interface.AudioPlayerHostApi.getDuration$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[playerId],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
    return pigeonVar_replyValue as int?;
  }

  /// Lists the available audio output devices. / 列出可用的音频输出设备。
  Future<List<AudioDeviceMessage>> listOutputDevices() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.xue_hua_audio_platform_interface.AudioPlayerHostApi.listOutputDevices$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return (pigeonVar_replyValue! as List<Object?>).cast<AudioDeviceMessage>();
  }

  /// Returns the output device used by the player, or `null` when following
  /// the system default. / 返回播放器当前使用的输出设备；跟随系统默认时返回 `null`。
  Future<AudioDeviceMessage?> getOutputDevice(int playerId) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.xue_hua_audio_platform_interface.AudioPlayerHostApi.getOutputDevice$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[playerId],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
    return pigeonVar_replyValue as AudioDeviceMessage?;
  }

  /// Routes the player to the output device [deviceId], or back to the
  /// system default when `null`.
  /// 将播放器路由到输出设备 [deviceId]；传 `null` 恢复系统默认设备。
  Future<void> setOutputDevice(int playerId, String? deviceId) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.xue_hua_audio_platform_interface.AudioPlayerHostApi.setOutputDevice$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[playerId, deviceId],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  /// Releases all native resources of the player. / 释放播放器的全部原生资源。
  Future<void> disposePlayer(int playerId) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.xue_hua_audio_platform_interface.AudioPlayerHostApi.disposePlayer$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[playerId],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }
}

/// Host API implemented natively for microphone recording control.
/// 由原生端实现的麦克风录音控制接口。
class AudioRecorderHostApi {
  /// Constructor for [AudioRecorderHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  AudioRecorderHostApi({
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) : pigeonVar_binaryMessenger = binaryMessenger,
       pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty
           ? '.$messageChannelSuffix'
           : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// Creates a native recorder instance and returns its id.
  /// 创建一个原生录音机实例并返回其 id。
  Future<int> createRecorder() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.xue_hua_audio_platform_interface.AudioRecorderHostApi.createRecorder$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as int;
  }

  /// Checks (and requests when possible) microphone permission.
  /// Returns `true` when recording is permitted.
  /// 检查（并在可能时请求）麦克风权限；允许录音时返回 `true`。
  Future<bool> hasPermission() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.xue_hua_audio_platform_interface.AudioRecorderHostApi.hasPermission$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as bool;
  }

  /// Lists the available audio input devices. / 列出可用的音频输入设备。
  Future<List<AudioDeviceMessage>> listInputDevices() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.xue_hua_audio_platform_interface.AudioRecorderHostApi.listInputDevices$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return (pigeonVar_replyValue! as List<Object?>).cast<AudioDeviceMessage>();
  }

  /// Returns the input device used by the recorder, or `null` when following
  /// the system default. / 返回录音机当前使用的输入设备；跟随系统默认时返回 `null`。
  Future<AudioDeviceMessage?> getInputDevice(int recorderId) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.xue_hua_audio_platform_interface.AudioRecorderHostApi.getInputDevice$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[recorderId],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
    return pigeonVar_replyValue as AudioDeviceMessage?;
  }

  /// Selects the input device [deviceId] for the recorder, or the system
  /// default when `null`. Live switching support is platform dependent.
  /// 为录音机选择输入设备 [deviceId]；传 `null` 使用系统默认设备。
  /// 录音过程中切换的支持情况视平台而定。
  Future<void> setInputDevice(int recorderId, String? deviceId) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.xue_hua_audio_platform_interface.AudioRecorderHostApi.setInputDevice$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[recorderId, deviceId],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  /// Starts recording to [path] using [config]. Completes once recording
  /// has actually started.
  /// 使用 [config] 开始录音并写入 [path]；录音真正启动后才完成。
  Future<void> start(
    int recorderId,
    RecordConfigMessage config,
    String path,
  ) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.xue_hua_audio_platform_interface.AudioRecorderHostApi.start$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[recorderId, config, path],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  /// Pauses recording. / 暂停录音。
  Future<void> pause(int recorderId) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.xue_hua_audio_platform_interface.AudioRecorderHostApi.pause$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[recorderId],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  /// Resumes a paused recording. / 恢复已暂停的录音。
  Future<void> resume(int recorderId) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.xue_hua_audio_platform_interface.AudioRecorderHostApi.resume$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[recorderId],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  /// Stops recording and returns the recorded file path, or `null` when
  /// nothing was recorded.
  /// 停止录音并返回录音文件路径；未产生录音时返回 `null`。
  Future<String?> stop(int recorderId) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.xue_hua_audio_platform_interface.AudioRecorderHostApi.stop$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[recorderId],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
    return pigeonVar_replyValue as String?;
  }

  /// Stops recording and deletes the partial file. / 停止录音并删除未完成的文件。
  Future<void> cancel(int recorderId) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.xue_hua_audio_platform_interface.AudioRecorderHostApi.cancel$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[recorderId],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  /// Releases all native resources of the recorder. / 释放录音机的全部原生资源。
  Future<void> disposeRecorder(int recorderId) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.xue_hua_audio_platform_interface.AudioRecorderHostApi.disposeRecorder$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[recorderId],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }
}
