// Autogenerated from Pigeon (v27.3.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.xuehua.xue_hua_audio_android

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object MessagesPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

/** The kind of an audio source. / 音频源的种类。 */
enum class SourceTypeMessage(val raw: Int) {
  /** A local file path. / 本地文件路径。 */
  FILE(0),
  /** A remote HTTP(S) URL. / 远程 HTTP(S) 网络地址。 */
  URL(1),
  /** A Flutter asset key. / Flutter Asset 资源键。 */
  ASSET(2);

  companion object {
    fun ofRaw(raw: Int): SourceTypeMessage? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** The audio encoder used when recording. / 录音时使用的编码器。 */
enum class EncoderMessage(val raw: Int) {
  /** Linear PCM in a WAV container. / WAV 容器中的线性 PCM。 */
  WAV(0),
  /** AAC-LC in an MPEG-4 container. / MPEG-4 容器中的 AAC-LC。 */
  AAC_LC(1),
  /** Opus (Ogg or WebM container, platform dependent). / Opus 编码（Ogg 或 WebM 容器，视平台而定）。 */
  OPUS(2);

  companion object {
    fun ofRaw(raw: Int): EncoderMessage? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * Wire representation of an audio source. / 音频源的跨端传输结构。
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class AudioSourceMessage (
  /** The kind of source. / 源的种类。 */
  val type: SourceTypeMessage,
  /**
   * File path, URL, or fully-resolved asset key depending on [type].
   * 依据 [type] 不同，可能是文件路径、URL 或已解析的 asset 键。
   */
  val uri: String,
  /**
   * Optional HTTP headers, only meaningful for [SourceTypeMessage.url].
   * 可选的 HTTP 请求头，仅对 [SourceTypeMessage.url] 有意义。
   */
  val headers: Map<String, String>? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): AudioSourceMessage {
      val type = pigeonVar_list[0] as SourceTypeMessage
      val uri = pigeonVar_list[1] as String
      val headers = pigeonVar_list[2] as Map<String, String>?
      return AudioSourceMessage(type, uri, headers)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      type,
      uri,
      headers,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as AudioSourceMessage
    return MessagesPigeonUtils.deepEquals(this.type, other.type) && MessagesPigeonUtils.deepEquals(this.uri, other.uri) && MessagesPigeonUtils.deepEquals(this.headers, other.headers)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.type)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.uri)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.headers)
    return result
  }
  override fun toString(): String {
    return "AudioSourceMessage(type=$type, uri=$uri, headers=$headers)"
  }
}

/**
 * Wire representation of a recording configuration. / 录音配置的跨端传输结构。
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class RecordConfigMessage (
  /** Encoder to use. / 使用的编码器。 */
  val encoder: EncoderMessage,
  /** Sample rate in Hz. / 采样率（Hz）。 */
  val sampleRate: Long,
  /** Number of channels (1 = mono, 2 = stereo). / 声道数（1 单声道，2 立体声）。 */
  val numChannels: Long,
  /**
   * Bit rate in bits per second (compressed encoders only).
   * 比特率（bit/s，仅压缩编码器使用）。
   */
  val bitRate: Long,
  /**
   * Interval between amplitude events in milliseconds.
   * 振幅事件的推送间隔（毫秒）。
   */
  val amplitudeIntervalMs: Long,
  /**
   * Preferred input device id, `null` for the system default.
   * 期望使用的输入设备 id，`null` 表示系统默认设备。
   */
  val deviceId: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): RecordConfigMessage {
      val encoder = pigeonVar_list[0] as EncoderMessage
      val sampleRate = pigeonVar_list[1] as Long
      val numChannels = pigeonVar_list[2] as Long
      val bitRate = pigeonVar_list[3] as Long
      val amplitudeIntervalMs = pigeonVar_list[4] as Long
      val deviceId = pigeonVar_list[5] as String?
      return RecordConfigMessage(encoder, sampleRate, numChannels, bitRate, amplitudeIntervalMs, deviceId)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      encoder,
      sampleRate,
      numChannels,
      bitRate,
      amplitudeIntervalMs,
      deviceId,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as RecordConfigMessage
    return MessagesPigeonUtils.deepEquals(this.encoder, other.encoder) && MessagesPigeonUtils.deepEquals(this.sampleRate, other.sampleRate) && MessagesPigeonUtils.deepEquals(this.numChannels, other.numChannels) && MessagesPigeonUtils.deepEquals(this.bitRate, other.bitRate) && MessagesPigeonUtils.deepEquals(this.amplitudeIntervalMs, other.amplitudeIntervalMs) && MessagesPigeonUtils.deepEquals(this.deviceId, other.deviceId)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.encoder)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.sampleRate)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.numChannels)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.bitRate)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.amplitudeIntervalMs)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.deviceId)
    return result
  }
  override fun toString(): String {
    return "RecordConfigMessage(encoder=$encoder, sampleRate=$sampleRate, numChannels=$numChannels, bitRate=$bitRate, amplitudeIntervalMs=$amplitudeIntervalMs, deviceId=$deviceId)"
  }
}

/**
 * Wire representation of an audio device (input or output).
 * 音频设备（输入或输出）的跨端传输结构。
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class AudioDeviceMessage (
  /** Platform-specific stable device identifier. / 平台相关的稳定设备标识。 */
  val id: String,
  /** Human-readable device name. / 供人阅读的设备名称。 */
  val label: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): AudioDeviceMessage {
      val id = pigeonVar_list[0] as String
      val label = pigeonVar_list[1] as String
      return AudioDeviceMessage(id, label)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      label,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as AudioDeviceMessage
    return MessagesPigeonUtils.deepEquals(this.id, other.id) && MessagesPigeonUtils.deepEquals(this.label, other.label)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.id)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.label)
    return result
  }
  override fun toString(): String {
    return "AudioDeviceMessage(id=$id, label=$label)"
  }
}
private open class MessagesPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          SourceTypeMessage.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          EncoderMessage.ofRaw(it.toInt())
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          AudioSourceMessage.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          RecordConfigMessage.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          AudioDeviceMessage.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is SourceTypeMessage -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is EncoderMessage -> {
        stream.write(130)
        writeValue(stream, value.raw.toLong())
      }
      is AudioSourceMessage -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is RecordConfigMessage -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is AudioDeviceMessage -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/**
 * Host API implemented natively for audio playback control.
 * 由原生端实现的音频播放控制接口。
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface AudioPlayerHostApi {
  /**
   * Creates a native player instance and returns its id.
   * 创建一个原生播放器实例并返回其 id。
   */
  fun createPlayer(): Long
  /**
   * Loads [source] into the player and returns the duration in
   * milliseconds, or `null` when unknown (e.g. live streams).
   * 加载音频源 [source]，返回音频时长（毫秒）；未知时（如直播流）返回 `null`。
   */
  fun setSource(playerId: Long, source: AudioSourceMessage, callback: (Result<Long?>) -> Unit)
  /** Starts or resumes playback. / 开始或恢复播放。 */
  fun play(playerId: Long)
  /** Pauses playback keeping the position. / 暂停播放并保留进度。 */
  fun pause(playerId: Long)
  /** Stops playback and rewinds to the beginning. / 停止播放并回到起点。 */
  fun stop(playerId: Long)
  /** Seeks to [positionMs] milliseconds. / 跳转到 [positionMs]（毫秒）。 */
  fun seekTo(playerId: Long, positionMs: Long, callback: (Result<Unit>) -> Unit)
  /** Sets the volume, 0.0 to 1.0. / 设置音量（0.0 ~ 1.0）。 */
  fun setVolume(playerId: Long, volume: Double)
  /** Sets the playback speed, e.g. 0.5 to 2.0. / 设置播放速度（如 0.5 ~ 2.0）。 */
  fun setSpeed(playerId: Long, speed: Double)
  /** Enables or disables looping. / 开启或关闭循环播放。 */
  fun setLooping(playerId: Long, looping: Boolean)
  /** Returns the current position in milliseconds. / 返回当前播放位置（毫秒）。 */
  fun getPosition(playerId: Long): Long
  /**
   * Returns the duration in milliseconds or `null` when unknown.
   * 返回音频时长（毫秒），未知时返回 `null`。
   */
  fun getDuration(playerId: Long): Long?
  /** Lists the available audio output devices. / 列出可用的音频输出设备。 */
  fun listOutputDevices(callback: (Result<List<AudioDeviceMessage>>) -> Unit)
  /**
   * Returns the output device used by the player, or `null` when following
   * the system default. / 返回播放器当前使用的输出设备；跟随系统默认时返回 `null`。
   */
  fun getOutputDevice(playerId: Long, callback: (Result<AudioDeviceMessage?>) -> Unit)
  /**
   * Routes the player to the output device [deviceId], or back to the
   * system default when `null`.
   * 将播放器路由到输出设备 [deviceId]；传 `null` 恢复系统默认设备。
   */
  fun setOutputDevice(playerId: Long, deviceId: String?, callback: (Result<Unit>) -> Unit)
  /** Releases all native resources of the player. / 释放播放器的全部原生资源。 */
  fun disposePlayer(playerId: Long)

  companion object {
    /** The codec used by AudioPlayerHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
    /** Sets up an instance of `AudioPlayerHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: AudioPlayerHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.xue_hua_audio_platform_interface.AudioPlayerHostApi.createPlayer$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.createPlayer())
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.xue_hua_audio_platform_interface.AudioPlayerHostApi.setSource$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val playerIdArg = args[0] as Long
            val sourceArg = args[1] as AudioSourceMessage
            api.setSource(playerIdArg, sourceArg) { result: Result<Long?> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.xue_hua_audio_platform_interface.AudioPlayerHostApi.play$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val playerIdArg = args[0] as Long
            val wrapped: List<Any?> = try {
              api.play(playerIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.xue_hua_audio_platform_interface.AudioPlayerHostApi.pause$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val playerIdArg = args[0] as Long
            val wrapped: List<Any?> = try {
              api.pause(playerIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.xue_hua_audio_platform_interface.AudioPlayerHostApi.stop$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val playerIdArg = args[0] as Long
            val wrapped: List<Any?> = try {
              api.stop(playerIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.xue_hua_audio_platform_interface.AudioPlayerHostApi.seekTo$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val playerIdArg = args[0] as Long
            val positionMsArg = args[1] as Long
            api.seekTo(playerIdArg, positionMsArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                reply.reply(MessagesPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.xue_hua_audio_platform_interface.AudioPlayerHostApi.setVolume$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val playerIdArg = args[0] as Long
            val volumeArg = args[1] as Double
            val wrapped: List<Any?> = try {
              api.setVolume(playerIdArg, volumeArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.xue_hua_audio_platform_interface.AudioPlayerHostApi.setSpeed$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val playerIdArg = args[0] as Long
            val speedArg = args[1] as Double
            val wrapped: List<Any?> = try {
              api.setSpeed(playerIdArg, speedArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.xue_hua_audio_platform_interface.AudioPlayerHostApi.setLooping$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val playerIdArg = args[0] as Long
            val loopingArg = args[1] as Boolean
            val wrapped: List<Any?> = try {
              api.setLooping(playerIdArg, loopingArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.xue_hua_audio_platform_interface.AudioPlayerHostApi.getPosition$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val playerIdArg = args[0] as Long
            val wrapped: List<Any?> = try {
              listOf(api.getPosition(playerIdArg))
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.xue_hua_audio_platform_interface.AudioPlayerHostApi.getDuration$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val playerIdArg = args[0] as Long
            val wrapped: List<Any?> = try {
              listOf(api.getDuration(playerIdArg))
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.xue_hua_audio_platform_interface.AudioPlayerHostApi.listOutputDevices$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.listOutputDevices{ result: Result<List<AudioDeviceMessage>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.xue_hua_audio_platform_interface.AudioPlayerHostApi.getOutputDevice$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val playerIdArg = args[0] as Long
            api.getOutputDevice(playerIdArg) { result: Result<AudioDeviceMessage?> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.xue_hua_audio_platform_interface.AudioPlayerHostApi.setOutputDevice$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val playerIdArg = args[0] as Long
            val deviceIdArg = args[1] as String?
            api.setOutputDevice(playerIdArg, deviceIdArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                reply.reply(MessagesPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.xue_hua_audio_platform_interface.AudioPlayerHostApi.disposePlayer$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val playerIdArg = args[0] as Long
            val wrapped: List<Any?> = try {
              api.disposePlayer(playerIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/**
 * Host API implemented natively for microphone recording control.
 * 由原生端实现的麦克风录音控制接口。
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface AudioRecorderHostApi {
  /**
   * Creates a native recorder instance and returns its id.
   * 创建一个原生录音机实例并返回其 id。
   */
  fun createRecorder(): Long
  /**
   * Checks (and requests when possible) microphone permission.
   * Returns `true` when recording is permitted.
   * 检查（并在可能时请求）麦克风权限；允许录音时返回 `true`。
   */
  fun hasPermission(callback: (Result<Boolean>) -> Unit)
  /** Lists the available audio input devices. / 列出可用的音频输入设备。 */
  fun listInputDevices(callback: (Result<List<AudioDeviceMessage>>) -> Unit)
  /**
   * Returns the input device used by the recorder, or `null` when following
   * the system default. / 返回录音机当前使用的输入设备；跟随系统默认时返回 `null`。
   */
  fun getInputDevice(recorderId: Long, callback: (Result<AudioDeviceMessage?>) -> Unit)
  /**
   * Selects the input device [deviceId] for the recorder, or the system
   * default when `null`. Live switching support is platform dependent.
   * 为录音机选择输入设备 [deviceId]；传 `null` 使用系统默认设备。
   * 录音过程中切换的支持情况视平台而定。
   */
  fun setInputDevice(recorderId: Long, deviceId: String?, callback: (Result<Unit>) -> Unit)
  /**
   * Starts recording to [path] using [config]. Completes once recording
   * has actually started.
   * 使用 [config] 开始录音并写入 [path]；录音真正启动后才完成。
   */
  fun start(recorderId: Long, config: RecordConfigMessage, path: String, callback: (Result<Unit>) -> Unit)
  /** Pauses recording. / 暂停录音。 */
  fun pause(recorderId: Long)
  /** Resumes a paused recording. / 恢复已暂停的录音。 */
  fun resume(recorderId: Long)
  /**
   * Stops recording and returns the recorded file path, or `null` when
   * nothing was recorded.
   * 停止录音并返回录音文件路径；未产生录音时返回 `null`。
   */
  fun stop(recorderId: Long, callback: (Result<String?>) -> Unit)
  /** Stops recording and deletes the partial file. / 停止录音并删除未完成的文件。 */
  fun cancel(recorderId: Long, callback: (Result<Unit>) -> Unit)
  /** Releases all native resources of the recorder. / 释放录音机的全部原生资源。 */
  fun disposeRecorder(recorderId: Long)

  companion object {
    /** The codec used by AudioRecorderHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
    /** Sets up an instance of `AudioRecorderHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: AudioRecorderHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.xue_hua_audio_platform_interface.AudioRecorderHostApi.createRecorder$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.createRecorder())
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.xue_hua_audio_platform_interface.AudioRecorderHostApi.hasPermission$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.hasPermission{ result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.xue_hua_audio_platform_interface.AudioRecorderHostApi.listInputDevices$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.listInputDevices{ result: Result<List<AudioDeviceMessage>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.xue_hua_audio_platform_interface.AudioRecorderHostApi.getInputDevice$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val recorderIdArg = args[0] as Long
            api.getInputDevice(recorderIdArg) { result: Result<AudioDeviceMessage?> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.xue_hua_audio_platform_interface.AudioRecorderHostApi.setInputDevice$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val recorderIdArg = args[0] as Long
            val deviceIdArg = args[1] as String?
            api.setInputDevice(recorderIdArg, deviceIdArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                reply.reply(MessagesPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.xue_hua_audio_platform_interface.AudioRecorderHostApi.start$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val recorderIdArg = args[0] as Long
            val configArg = args[1] as RecordConfigMessage
            val pathArg = args[2] as String
            api.start(recorderIdArg, configArg, pathArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                reply.reply(MessagesPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.xue_hua_audio_platform_interface.AudioRecorderHostApi.pause$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val recorderIdArg = args[0] as Long
            val wrapped: List<Any?> = try {
              api.pause(recorderIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.xue_hua_audio_platform_interface.AudioRecorderHostApi.resume$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val recorderIdArg = args[0] as Long
            val wrapped: List<Any?> = try {
              api.resume(recorderIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.xue_hua_audio_platform_interface.AudioRecorderHostApi.stop$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val recorderIdArg = args[0] as Long
            api.stop(recorderIdArg) { result: Result<String?> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.xue_hua_audio_platform_interface.AudioRecorderHostApi.cancel$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val recorderIdArg = args[0] as Long
            api.cancel(recorderIdArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                reply.reply(MessagesPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.xue_hua_audio_platform_interface.AudioRecorderHostApi.disposeRecorder$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val recorderIdArg = args[0] as Long
            val wrapped: List<Any?> = try {
              api.disposeRecorder(recorderIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
